// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aMovieFieldNames          = builder.RawFieldNames(&AMovie{})
	aMovieRows                = strings.Join(aMovieFieldNames, ",")
	aMovieRowsExpectAutoSet   = strings.Join(stringx.Remove(aMovieFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	aMovieRowsWithPlaceHolder = strings.Join(stringx.Remove(aMovieFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcAMovieIdPrefix    = "cache:rudyGc:aMovie:id:"
	cacheRudyGcAMovieJavIdPrefix = "cache:rudyGc:aMovie:javId:"
)

type (
	aMovieModel interface {
		Insert(ctx context.Context, data *AMovie) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AMovie, error)
		FindOneByJavId(ctx context.Context, javId string) (*AMovie, error)
		Update(ctx context.Context, data *AMovie) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAMovieModel struct {
		sqlc.CachedConn
		table string
	}

	AMovie struct {
		Id                   int64  `db:"id"`
		JavId                string `db:"jav_id"`
		Name                 string `db:"name"`
		Title                string `db:"title"`
		EncodeName           string `db:"encode_name"`
		Length               int64  `db:"length"`
		ViewersNumberWant    int64  `db:"viewers_number_want"`
		ViewersNumberOwned   int64  `db:"viewers_number_owned"`
		ViewersNumberWatched int64  `db:"viewers_number_watched"`
		DetailUpdateTime     int64  `db:"detail_update_time"`
		ReleasingDate        int64  `db:"releasing_date"`
		Score                int64  `db:"score"`
		PrefixId             int64  `db:"prefix_id"`
		MakerId              int64  `db:"maker_id"`
		LabelId              int64  `db:"label_id"`
		DirectorId           int64  `db:"director_id"`
		CastNumber           int64  `db:"cast_number"`
		CastAverageAge       int64  `db:"cast_average_age"` // '平均年龄*10，例如237表示23.7岁'
		CreatedOn            int64  `db:"created_on"`
		UpdatedOn            int64  `db:"updated_on"`
	}
)

func newAMovieModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAMovieModel {
	return &defaultAMovieModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`a_movie`",
	}
}

func (m *defaultAMovieModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcAMovieIdKey := fmt.Sprintf("%s%v", cacheRudyGcAMovieIdPrefix, id)
	rudyGcAMovieJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcAMovieJavIdPrefix, data.JavId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcAMovieIdKey, rudyGcAMovieJavIdKey)
	return err
}

func (m *defaultAMovieModel) FindOne(ctx context.Context, id int64) (*AMovie, error) {
	rudyGcAMovieIdKey := fmt.Sprintf("%s%v", cacheRudyGcAMovieIdPrefix, id)
	var resp AMovie
	err := m.QueryRowCtx(ctx, &resp, rudyGcAMovieIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", aMovieRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAMovieModel) FindOneByJavId(ctx context.Context, javId string) (*AMovie, error) {
	rudyGcAMovieJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcAMovieJavIdPrefix, javId)
	var resp AMovie
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcAMovieJavIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `jav_id` = ? limit 1", aMovieRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, javId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAMovieModel) Insert(ctx context.Context, data *AMovie) (sql.Result, error) {
	rudyGcAMovieIdKey := fmt.Sprintf("%s%v", cacheRudyGcAMovieIdPrefix, data.Id)
	rudyGcAMovieJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcAMovieJavIdPrefix, data.JavId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, aMovieRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.JavId, data.Name, data.Title, data.EncodeName, data.Length, data.ViewersNumberWant, data.ViewersNumberOwned, data.ViewersNumberWatched, data.DetailUpdateTime, data.ReleasingDate, data.Score, data.PrefixId, data.MakerId, data.LabelId, data.DirectorId, data.CastNumber, data.CastAverageAge, data.CreatedOn, data.UpdatedOn)
	}, rudyGcAMovieIdKey, rudyGcAMovieJavIdKey)
	return ret, err
}

func (m *defaultAMovieModel) Update(ctx context.Context, newData *AMovie) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcAMovieIdKey := fmt.Sprintf("%s%v", cacheRudyGcAMovieIdPrefix, data.Id)
	rudyGcAMovieJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcAMovieJavIdPrefix, data.JavId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, aMovieRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.JavId, newData.Name, newData.Title, newData.EncodeName, newData.Length, newData.ViewersNumberWant, newData.ViewersNumberOwned, newData.ViewersNumberWatched, newData.DetailUpdateTime, newData.ReleasingDate, newData.Score, newData.PrefixId, newData.MakerId, newData.LabelId, newData.DirectorId, newData.CastNumber, newData.CastAverageAge, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcAMovieIdKey, rudyGcAMovieJavIdKey)
	return err
}

func (m *defaultAMovieModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcAMovieIdPrefix, primary)
}

func (m *defaultAMovieModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", aMovieRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAMovieModel) tableName() string {
	return m.table
}
