// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	amPrefixFieldNames          = builder.RawFieldNames(&AmPrefix{})
	amPrefixRows                = strings.Join(amPrefixFieldNames, ",")
	amPrefixRowsExpectAutoSet   = strings.Join(stringx.Remove(amPrefixFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	amPrefixRowsWithPlaceHolder = strings.Join(stringx.Remove(amPrefixFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcAmPrefixIdPrefix   = "cache:rudyGc:amPrefix:id:"
	cacheRudyGcAmPrefixNamePrefix = "cache:rudyGc:amPrefix:name:"
)

type (
	amPrefixModel interface {
		Insert(ctx context.Context, data *AmPrefix) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AmPrefix, error)
		FindOneByName(ctx context.Context, name string) (*AmPrefix, error)
		Update(ctx context.Context, data *AmPrefix) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAmPrefixModel struct {
		sqlc.CachedConn
		table string
	}

	AmPrefix struct {
		Id               int64  `db:"id"`
		Name             string `db:"name"`
		MovieNumber      int64  `db:"movie_number"`
		OwnedMovieNumber int64  `db:"owned_movie_number"`
		CreatedOn        int64  `db:"created_on"`
		UpdatedOn        int64  `db:"updated_on"`
	}
)

func newAmPrefixModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAmPrefixModel {
	return &defaultAmPrefixModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`am_prefix`",
	}
}

func (m *defaultAmPrefixModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcAmPrefixIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmPrefixIdPrefix, id)
	rudyGcAmPrefixNameKey := fmt.Sprintf("%s%v", cacheRudyGcAmPrefixNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcAmPrefixIdKey, rudyGcAmPrefixNameKey)
	return err
}

func (m *defaultAmPrefixModel) FindOne(ctx context.Context, id int64) (*AmPrefix, error) {
	rudyGcAmPrefixIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmPrefixIdPrefix, id)
	var resp AmPrefix
	err := m.QueryRowCtx(ctx, &resp, rudyGcAmPrefixIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amPrefixRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmPrefixModel) FindOneByName(ctx context.Context, name string) (*AmPrefix, error) {
	rudyGcAmPrefixNameKey := fmt.Sprintf("%s%v", cacheRudyGcAmPrefixNamePrefix, name)
	var resp AmPrefix
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcAmPrefixNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", amPrefixRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmPrefixModel) Insert(ctx context.Context, data *AmPrefix) (sql.Result, error) {
	rudyGcAmPrefixIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmPrefixIdPrefix, data.Id)
	rudyGcAmPrefixNameKey := fmt.Sprintf("%s%v", cacheRudyGcAmPrefixNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, amPrefixRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.MovieNumber, data.OwnedMovieNumber, data.CreatedOn, data.UpdatedOn)
	}, rudyGcAmPrefixIdKey, rudyGcAmPrefixNameKey)
	return ret, err
}

func (m *defaultAmPrefixModel) Update(ctx context.Context, newData *AmPrefix) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcAmPrefixIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmPrefixIdPrefix, data.Id)
	rudyGcAmPrefixNameKey := fmt.Sprintf("%s%v", cacheRudyGcAmPrefixNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, amPrefixRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.MovieNumber, newData.OwnedMovieNumber, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcAmPrefixIdKey, rudyGcAmPrefixNameKey)
	return err
}

func (m *defaultAmPrefixModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcAmPrefixIdPrefix, primary)
}

func (m *defaultAmPrefixModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amPrefixRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAmPrefixModel) tableName() string {
	return m.table
}
