// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	amrMovieGenreFieldNames          = builder.RawFieldNames(&AmrMovieGenre{})
	amrMovieGenreRows                = strings.Join(amrMovieGenreFieldNames, ",")
	amrMovieGenreRowsExpectAutoSet   = strings.Join(stringx.Remove(amrMovieGenreFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	amrMovieGenreRowsWithPlaceHolder = strings.Join(stringx.Remove(amrMovieGenreFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcAmrMovieGenreIdPrefix                = "cache:rudyGc:amrMovieGenre:id:"
	cacheRudyGcAmrMovieGenreMovieJavIdGenreIdPrefix = "cache:rudyGc:amrMovieGenre:movieJavId:genreId:"
)

type (
	amrMovieGenreModel interface {
		Insert(ctx context.Context, data *AmrMovieGenre) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AmrMovieGenre, error)
		FindOneByMovieJavIdGenreId(ctx context.Context, movieJavId string, genreId int64) (*AmrMovieGenre, error)
		Update(ctx context.Context, data *AmrMovieGenre) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAmrMovieGenreModel struct {
		sqlc.CachedConn
		table string
	}

	AmrMovieGenre struct {
		Id         int64  `db:"id"`
		MovieJavId string `db:"movie_jav_id"`
		GenreId    int64  `db:"genre_id"`
		CreatedOn  int64  `db:"created_on"`
		UpdatedOn  int64  `db:"updated_on"`
	}
)

func newAmrMovieGenreModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAmrMovieGenreModel {
	return &defaultAmrMovieGenreModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`amr_movie_genre`",
	}
}

func (m *defaultAmrMovieGenreModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcAmrMovieGenreIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmrMovieGenreIdPrefix, id)
	rudyGcAmrMovieGenreMovieJavIdGenreIdKey := fmt.Sprintf("%s%v:%v", cacheRudyGcAmrMovieGenreMovieJavIdGenreIdPrefix, data.MovieJavId, data.GenreId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcAmrMovieGenreIdKey, rudyGcAmrMovieGenreMovieJavIdGenreIdKey)
	return err
}

func (m *defaultAmrMovieGenreModel) FindOne(ctx context.Context, id int64) (*AmrMovieGenre, error) {
	rudyGcAmrMovieGenreIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmrMovieGenreIdPrefix, id)
	var resp AmrMovieGenre
	err := m.QueryRowCtx(ctx, &resp, rudyGcAmrMovieGenreIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amrMovieGenreRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmrMovieGenreModel) FindOneByMovieJavIdGenreId(ctx context.Context, movieJavId string, genreId int64) (*AmrMovieGenre, error) {
	rudyGcAmrMovieGenreMovieJavIdGenreIdKey := fmt.Sprintf("%s%v:%v", cacheRudyGcAmrMovieGenreMovieJavIdGenreIdPrefix, movieJavId, genreId)
	var resp AmrMovieGenre
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcAmrMovieGenreMovieJavIdGenreIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `movie_jav_id` = ? and `genre_id` = ? limit 1", amrMovieGenreRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, movieJavId, genreId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmrMovieGenreModel) Insert(ctx context.Context, data *AmrMovieGenre) (sql.Result, error) {
	rudyGcAmrMovieGenreIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmrMovieGenreIdPrefix, data.Id)
	rudyGcAmrMovieGenreMovieJavIdGenreIdKey := fmt.Sprintf("%s%v:%v", cacheRudyGcAmrMovieGenreMovieJavIdGenreIdPrefix, data.MovieJavId, data.GenreId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, amrMovieGenreRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MovieJavId, data.GenreId, data.CreatedOn, data.UpdatedOn)
	}, rudyGcAmrMovieGenreIdKey, rudyGcAmrMovieGenreMovieJavIdGenreIdKey)
	return ret, err
}

func (m *defaultAmrMovieGenreModel) Update(ctx context.Context, newData *AmrMovieGenre) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcAmrMovieGenreIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmrMovieGenreIdPrefix, data.Id)
	rudyGcAmrMovieGenreMovieJavIdGenreIdKey := fmt.Sprintf("%s%v:%v", cacheRudyGcAmrMovieGenreMovieJavIdGenreIdPrefix, data.MovieJavId, data.GenreId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, amrMovieGenreRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MovieJavId, newData.GenreId, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcAmrMovieGenreIdKey, rudyGcAmrMovieGenreMovieJavIdGenreIdKey)
	return err
}

func (m *defaultAmrMovieGenreModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcAmrMovieGenreIdPrefix, primary)
}

func (m *defaultAmrMovieGenreModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amrMovieGenreRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAmrMovieGenreModel) tableName() string {
	return m.table
}
