// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cCafoFieldNames          = builder.RawFieldNames(&CCafo{})
	cCafoRows                = strings.Join(cCafoFieldNames, ",")
	cCafoRowsExpectAutoSet   = strings.Join(stringx.Remove(cCafoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cCafoRowsWithPlaceHolder = strings.Join(stringx.Remove(cCafoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcCCafoIdPrefix      = "cache:rudyGc:cCafo:id:"
	cacheRudyGcCCafoChinesePrefix = "cache:rudyGc:cCafo:chinese:"
	cacheRudyGcCCafoNamePrefix    = "cache:rudyGc:cCafo:name:"
)

type (
	cCafoModel interface {
		Insert(ctx context.Context, data *CCafo) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CCafo, error)
		FindOneByChinese(ctx context.Context, chinese string) (*CCafo, error)
		FindOneByName(ctx context.Context, name string) (*CCafo, error)
		Update(ctx context.Context, data *CCafo) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCCafoModel struct {
		sqlc.CachedConn
		table string
	}

	CCafo struct {
		Id        int64  `db:"id"`
		Name      string `db:"name"`
		Alias     string `db:"alias"`
		Chinese   string `db:"chinese"`
		BirthDay  int64  `db:"birth_day"`
		Height    int64  `db:"height"`
		Cup       string `db:"cup"`
		Bwh       string `db:"bwh"`
		Avtar     string `db:"avtar"`
		CreatedOn int64  `db:"created_on"`
		UpdatedOn int64  `db:"updated_on"`
	}
)

func newCCafoModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCCafoModel {
	return &defaultCCafoModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`c_cafo`",
	}
}

func (m *defaultCCafoModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcCCafoChineseKey := fmt.Sprintf("%s%v", cacheRudyGcCCafoChinesePrefix, data.Chinese)
	rudyGcCCafoIdKey := fmt.Sprintf("%s%v", cacheRudyGcCCafoIdPrefix, id)
	rudyGcCCafoNameKey := fmt.Sprintf("%s%v", cacheRudyGcCCafoNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcCCafoChineseKey, rudyGcCCafoIdKey, rudyGcCCafoNameKey)
	return err
}

func (m *defaultCCafoModel) FindOne(ctx context.Context, id int64) (*CCafo, error) {
	rudyGcCCafoIdKey := fmt.Sprintf("%s%v", cacheRudyGcCCafoIdPrefix, id)
	var resp CCafo
	err := m.QueryRowCtx(ctx, &resp, rudyGcCCafoIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cCafoRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCCafoModel) FindOneByChinese(ctx context.Context, chinese string) (*CCafo, error) {
	rudyGcCCafoChineseKey := fmt.Sprintf("%s%v", cacheRudyGcCCafoChinesePrefix, chinese)
	var resp CCafo
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcCCafoChineseKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `chinese` = ? limit 1", cCafoRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, chinese); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCCafoModel) FindOneByName(ctx context.Context, name string) (*CCafo, error) {
	rudyGcCCafoNameKey := fmt.Sprintf("%s%v", cacheRudyGcCCafoNamePrefix, name)
	var resp CCafo
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcCCafoNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", cCafoRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCCafoModel) Insert(ctx context.Context, data *CCafo) (sql.Result, error) {
	rudyGcCCafoChineseKey := fmt.Sprintf("%s%v", cacheRudyGcCCafoChinesePrefix, data.Chinese)
	rudyGcCCafoIdKey := fmt.Sprintf("%s%v", cacheRudyGcCCafoIdPrefix, data.Id)
	rudyGcCCafoNameKey := fmt.Sprintf("%s%v", cacheRudyGcCCafoNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, cCafoRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Alias, data.Chinese, data.BirthDay, data.Height, data.Cup, data.Bwh, data.Avtar, data.CreatedOn, data.UpdatedOn)
	}, rudyGcCCafoChineseKey, rudyGcCCafoIdKey, rudyGcCCafoNameKey)
	return ret, err
}

func (m *defaultCCafoModel) Update(ctx context.Context, newData *CCafo) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcCCafoChineseKey := fmt.Sprintf("%s%v", cacheRudyGcCCafoChinesePrefix, data.Chinese)
	rudyGcCCafoIdKey := fmt.Sprintf("%s%v", cacheRudyGcCCafoIdPrefix, data.Id)
	rudyGcCCafoNameKey := fmt.Sprintf("%s%v", cacheRudyGcCCafoNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cCafoRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Alias, newData.Chinese, newData.BirthDay, newData.Height, newData.Cup, newData.Bwh, newData.Avtar, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcCCafoChineseKey, rudyGcCCafoIdKey, rudyGcCCafoNameKey)
	return err
}

func (m *defaultCCafoModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcCCafoIdPrefix, primary)
}

func (m *defaultCCafoModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cCafoRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCCafoModel) tableName() string {
	return m.table
}
