// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cMovieAlbumFieldNames          = builder.RawFieldNames(&CMovieAlbum{})
	cMovieAlbumRows                = strings.Join(cMovieAlbumFieldNames, ",")
	cMovieAlbumRowsExpectAutoSet   = strings.Join(stringx.Remove(cMovieAlbumFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cMovieAlbumRowsWithPlaceHolder = strings.Join(stringx.Remove(cMovieAlbumFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcCMovieAlbumIdPrefix   = "cache:rudyGc:cMovieAlbum:id:"
	cacheRudyGcCMovieAlbumNamePrefix = "cache:rudyGc:cMovieAlbum:name:"
)

type (
	cMovieAlbumModel interface {
		Insert(ctx context.Context, data *CMovieAlbum) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CMovieAlbum, error)
		FindOneByName(ctx context.Context, name string) (*CMovieAlbum, error)
		Update(ctx context.Context, data *CMovieAlbum) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCMovieAlbumModel struct {
		sqlc.CachedConn
		table string
	}

	CMovieAlbum struct {
		Id        int64  `db:"id"`
		Name      string `db:"name"`
		Remark    string `db:"remark"`
		CreatedOn int64  `db:"created_on"`
		UpdatedOn int64  `db:"updated_on"`
	}
)

func newCMovieAlbumModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCMovieAlbumModel {
	return &defaultCMovieAlbumModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`c_movie_album`",
	}
}

func (m *defaultCMovieAlbumModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcCMovieAlbumIdKey := fmt.Sprintf("%s%v", cacheRudyGcCMovieAlbumIdPrefix, id)
	rudyGcCMovieAlbumNameKey := fmt.Sprintf("%s%v", cacheRudyGcCMovieAlbumNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcCMovieAlbumIdKey, rudyGcCMovieAlbumNameKey)
	return err
}

func (m *defaultCMovieAlbumModel) FindOne(ctx context.Context, id int64) (*CMovieAlbum, error) {
	rudyGcCMovieAlbumIdKey := fmt.Sprintf("%s%v", cacheRudyGcCMovieAlbumIdPrefix, id)
	var resp CMovieAlbum
	err := m.QueryRowCtx(ctx, &resp, rudyGcCMovieAlbumIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cMovieAlbumRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCMovieAlbumModel) FindOneByName(ctx context.Context, name string) (*CMovieAlbum, error) {
	rudyGcCMovieAlbumNameKey := fmt.Sprintf("%s%v", cacheRudyGcCMovieAlbumNamePrefix, name)
	var resp CMovieAlbum
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcCMovieAlbumNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", cMovieAlbumRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCMovieAlbumModel) Insert(ctx context.Context, data *CMovieAlbum) (sql.Result, error) {
	rudyGcCMovieAlbumIdKey := fmt.Sprintf("%s%v", cacheRudyGcCMovieAlbumIdPrefix, data.Id)
	rudyGcCMovieAlbumNameKey := fmt.Sprintf("%s%v", cacheRudyGcCMovieAlbumNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, cMovieAlbumRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Remark, data.CreatedOn, data.UpdatedOn)
	}, rudyGcCMovieAlbumIdKey, rudyGcCMovieAlbumNameKey)
	return ret, err
}

func (m *defaultCMovieAlbumModel) Update(ctx context.Context, newData *CMovieAlbum) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcCMovieAlbumIdKey := fmt.Sprintf("%s%v", cacheRudyGcCMovieAlbumIdPrefix, data.Id)
	rudyGcCMovieAlbumNameKey := fmt.Sprintf("%s%v", cacheRudyGcCMovieAlbumNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cMovieAlbumRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Remark, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcCMovieAlbumIdKey, rudyGcCMovieAlbumNameKey)
	return err
}

func (m *defaultCMovieAlbumModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcCMovieAlbumIdPrefix, primary)
}

func (m *defaultCMovieAlbumModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cMovieAlbumRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCMovieAlbumModel) tableName() string {
	return m.table
}
