// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cMovieAlbumItemFieldNames          = builder.RawFieldNames(&CMovieAlbumItem{})
	cMovieAlbumItemRows                = strings.Join(cMovieAlbumItemFieldNames, ",")
	cMovieAlbumItemRowsExpectAutoSet   = strings.Join(stringx.Remove(cMovieAlbumItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cMovieAlbumItemRowsWithPlaceHolder = strings.Join(stringx.Remove(cMovieAlbumItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcCMovieAlbumItemIdPrefix                = "cache:rudyGc:cMovieAlbumItem:id:"
	cacheRudyGcCMovieAlbumItemAlbumIdMovieJavIdPrefix = "cache:rudyGc:cMovieAlbumItem:albumId:movieJavId:"
)

type (
	cMovieAlbumItemModel interface {
		Insert(ctx context.Context, data *CMovieAlbumItem) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CMovieAlbumItem, error)
		FindOneByAlbumIdMovieJavId(ctx context.Context, albumId int64, movieJavId string) (*CMovieAlbumItem, error)
		Update(ctx context.Context, data *CMovieAlbumItem) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCMovieAlbumItemModel struct {
		sqlc.CachedConn
		table string
	}

	CMovieAlbumItem struct {
		Id            int64  `db:"id"`
		AlbumId       int64  `db:"album_id"`
		MovieJavId    string `db:"movie_jav_id"`
		MovieName     string `db:"movie_name"`
		ReleasingDate int64  `db:"releasing_date"`
		SortNo        int64  `db:"sort_no"`
		CreatedOn     int64  `db:"created_on"`
		UpdatedOn     int64  `db:"updated_on"`
	}
)

func newCMovieAlbumItemModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCMovieAlbumItemModel {
	return &defaultCMovieAlbumItemModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`c_movie_album_item`",
	}
}

func (m *defaultCMovieAlbumItemModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcCMovieAlbumItemAlbumIdMovieJavIdKey := fmt.Sprintf("%s%v:%v", cacheRudyGcCMovieAlbumItemAlbumIdMovieJavIdPrefix, data.AlbumId, data.MovieJavId)
	rudyGcCMovieAlbumItemIdKey := fmt.Sprintf("%s%v", cacheRudyGcCMovieAlbumItemIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcCMovieAlbumItemAlbumIdMovieJavIdKey, rudyGcCMovieAlbumItemIdKey)
	return err
}

func (m *defaultCMovieAlbumItemModel) FindOne(ctx context.Context, id int64) (*CMovieAlbumItem, error) {
	rudyGcCMovieAlbumItemIdKey := fmt.Sprintf("%s%v", cacheRudyGcCMovieAlbumItemIdPrefix, id)
	var resp CMovieAlbumItem
	err := m.QueryRowCtx(ctx, &resp, rudyGcCMovieAlbumItemIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cMovieAlbumItemRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCMovieAlbumItemModel) FindOneByAlbumIdMovieJavId(ctx context.Context, albumId int64, movieJavId string) (*CMovieAlbumItem, error) {
	rudyGcCMovieAlbumItemAlbumIdMovieJavIdKey := fmt.Sprintf("%s%v:%v", cacheRudyGcCMovieAlbumItemAlbumIdMovieJavIdPrefix, albumId, movieJavId)
	var resp CMovieAlbumItem
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcCMovieAlbumItemAlbumIdMovieJavIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `album_id` = ? and `movie_jav_id` = ? limit 1", cMovieAlbumItemRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, albumId, movieJavId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCMovieAlbumItemModel) Insert(ctx context.Context, data *CMovieAlbumItem) (sql.Result, error) {
	rudyGcCMovieAlbumItemAlbumIdMovieJavIdKey := fmt.Sprintf("%s%v:%v", cacheRudyGcCMovieAlbumItemAlbumIdMovieJavIdPrefix, data.AlbumId, data.MovieJavId)
	rudyGcCMovieAlbumItemIdKey := fmt.Sprintf("%s%v", cacheRudyGcCMovieAlbumItemIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, cMovieAlbumItemRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.AlbumId, data.MovieJavId, data.MovieName, data.ReleasingDate, data.SortNo, data.CreatedOn, data.UpdatedOn)
	}, rudyGcCMovieAlbumItemAlbumIdMovieJavIdKey, rudyGcCMovieAlbumItemIdKey)
	return ret, err
}

func (m *defaultCMovieAlbumItemModel) Update(ctx context.Context, newData *CMovieAlbumItem) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcCMovieAlbumItemAlbumIdMovieJavIdKey := fmt.Sprintf("%s%v:%v", cacheRudyGcCMovieAlbumItemAlbumIdMovieJavIdPrefix, data.AlbumId, data.MovieJavId)
	rudyGcCMovieAlbumItemIdKey := fmt.Sprintf("%s%v", cacheRudyGcCMovieAlbumItemIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cMovieAlbumItemRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.AlbumId, newData.MovieJavId, newData.MovieName, newData.ReleasingDate, newData.SortNo, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcCMovieAlbumItemAlbumIdMovieJavIdKey, rudyGcCMovieAlbumItemIdKey)
	return err
}

func (m *defaultCMovieAlbumItemModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcCMovieAlbumItemIdPrefix, primary)
}

func (m *defaultCMovieAlbumItemModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cMovieAlbumItemRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCMovieAlbumItemModel) tableName() string {
	return m.table
}
