// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cPersonScFieldNames          = builder.RawFieldNames(&CPersonSc{})
	cPersonScRows                = strings.Join(cPersonScFieldNames, ",")
	cPersonScRowsExpectAutoSet   = strings.Join(stringx.Remove(cPersonScFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cPersonScRowsWithPlaceHolder = strings.Join(stringx.Remove(cPersonScFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcCPersonScIdPrefix             = "cache:rudyGc:cPersonSc:id:"
	cacheRudyGcCPersonScPersonIdScNamePrefix = "cache:rudyGc:cPersonSc:personId:scName:"
)

type (
	cPersonScModel interface {
		Insert(ctx context.Context, data *CPersonSc) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CPersonSc, error)
		FindOneByPersonIdScName(ctx context.Context, personId int64, scName string) (*CPersonSc, error)
		Update(ctx context.Context, data *CPersonSc) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCPersonScModel struct {
		sqlc.CachedConn
		table string
	}

	CPersonSc struct {
		Id          int64  `db:"id"`
		PersonId    int64  `db:"person_id"`
		ScName      string `db:"sc_name"`
		ScTime      int64  `db:"sc_time"`
		Cooldown    int64  `db:"cooldown"`
		MovieCount  int64  `db:"movie_count"`
		HasCome     int64  `db:"has_come"`
		MoviesJson  string `db:"movies_json"`
		CreatedTime int64  `db:"created_time"`
		UpdatedTime int64  `db:"updated_time"`
	}
)

func newCPersonScModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCPersonScModel {
	return &defaultCPersonScModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`c_person_sc`",
	}
}

func (m *defaultCPersonScModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcCPersonScIdKey := fmt.Sprintf("%s%v", cacheRudyGcCPersonScIdPrefix, id)
	rudyGcCPersonScPersonIdScNameKey := fmt.Sprintf("%s%v:%v", cacheRudyGcCPersonScPersonIdScNamePrefix, data.PersonId, data.ScName)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcCPersonScIdKey, rudyGcCPersonScPersonIdScNameKey)
	return err
}

func (m *defaultCPersonScModel) FindOne(ctx context.Context, id int64) (*CPersonSc, error) {
	rudyGcCPersonScIdKey := fmt.Sprintf("%s%v", cacheRudyGcCPersonScIdPrefix, id)
	var resp CPersonSc
	err := m.QueryRowCtx(ctx, &resp, rudyGcCPersonScIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cPersonScRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCPersonScModel) FindOneByPersonIdScName(ctx context.Context, personId int64, scName string) (*CPersonSc, error) {
	rudyGcCPersonScPersonIdScNameKey := fmt.Sprintf("%s%v:%v", cacheRudyGcCPersonScPersonIdScNamePrefix, personId, scName)
	var resp CPersonSc
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcCPersonScPersonIdScNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `person_id` = ? and `sc_name` = ? limit 1", cPersonScRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, personId, scName); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCPersonScModel) Insert(ctx context.Context, data *CPersonSc) (sql.Result, error) {
	rudyGcCPersonScIdKey := fmt.Sprintf("%s%v", cacheRudyGcCPersonScIdPrefix, data.Id)
	rudyGcCPersonScPersonIdScNameKey := fmt.Sprintf("%s%v:%v", cacheRudyGcCPersonScPersonIdScNamePrefix, data.PersonId, data.ScName)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, cPersonScRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.PersonId, data.ScName, data.ScTime, data.Cooldown, data.MovieCount, data.HasCome, data.MoviesJson, data.CreatedTime, data.UpdatedTime)
	}, rudyGcCPersonScIdKey, rudyGcCPersonScPersonIdScNameKey)
	return ret, err
}

func (m *defaultCPersonScModel) Update(ctx context.Context, newData *CPersonSc) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcCPersonScIdKey := fmt.Sprintf("%s%v", cacheRudyGcCPersonScIdPrefix, data.Id)
	rudyGcCPersonScPersonIdScNameKey := fmt.Sprintf("%s%v:%v", cacheRudyGcCPersonScPersonIdScNamePrefix, data.PersonId, data.ScName)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cPersonScRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.PersonId, newData.ScName, newData.ScTime, newData.Cooldown, newData.MovieCount, newData.HasCome, newData.MoviesJson, newData.CreatedTime, newData.UpdatedTime, newData.Id)
	}, rudyGcCPersonScIdKey, rudyGcCPersonScPersonIdScNameKey)
	return err
}

func (m *defaultCPersonScModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcCPersonScIdPrefix, primary)
}

func (m *defaultCPersonScModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cPersonScRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCPersonScModel) tableName() string {
	return m.table
}
