// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cRankPeriodFieldNames          = builder.RawFieldNames(&CRankPeriod{})
	cRankPeriodRows                = strings.Join(cRankPeriodFieldNames, ",")
	cRankPeriodRowsExpectAutoSet   = strings.Join(stringx.Remove(cRankPeriodFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cRankPeriodRowsWithPlaceHolder = strings.Join(stringx.Remove(cRankPeriodFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcCRankPeriodIdPrefix                          = "cache:rudyGc:cRankPeriod:id:"
	cacheRudyGcCRankPeriodPeriodTypePeriodKeyCategoryPrefix = "cache:rudyGc:cRankPeriod:periodType:periodKey:category:"
)

type (
	cRankPeriodModel interface {
		Insert(ctx context.Context, data *CRankPeriod) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CRankPeriod, error)
		FindOneByPeriodTypePeriodKeyCategory(ctx context.Context, periodType int64, periodKey string, category int64) (*CRankPeriod, error)
		Update(ctx context.Context, data *CRankPeriod) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCRankPeriodModel struct {
		sqlc.CachedConn
		table string
	}

	CRankPeriod struct {
		Id             int64  `db:"id"`
		PeriodType     int64  `db:"period_type"`      // 周期类型(周/月/季/年)
		PeriodKey      string `db:"period_key"`       // 周期键
		Category       int64  `db:"category"`         // 榜单类别
		StartDayNumber int64  `db:"start_day_number"` // 周期开始日序号
		EndDayNumber   int64  `db:"end_day_number"`   // 周期结束日序号
		PickDays       int64  `db:"pick_days"`        // 固定取样天数
		TopN           int64  `db:"top_n"`            // 固定榜单数量
		Status         int64  `db:"status"`           // 状态
		CreatedOn      int64  `db:"created_on"`
		UpdatedOn      int64  `db:"updated_on"`
	}
)

func newCRankPeriodModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCRankPeriodModel {
	return &defaultCRankPeriodModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`c_rank_period`",
	}
}

func (m *defaultCRankPeriodModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcCRankPeriodIdKey := fmt.Sprintf("%s%v", cacheRudyGcCRankPeriodIdPrefix, id)
	rudyGcCRankPeriodPeriodTypePeriodKeyCategoryKey := fmt.Sprintf("%s%v:%v:%v", cacheRudyGcCRankPeriodPeriodTypePeriodKeyCategoryPrefix, data.PeriodType, data.PeriodKey, data.Category)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcCRankPeriodIdKey, rudyGcCRankPeriodPeriodTypePeriodKeyCategoryKey)
	return err
}

func (m *defaultCRankPeriodModel) FindOne(ctx context.Context, id int64) (*CRankPeriod, error) {
	rudyGcCRankPeriodIdKey := fmt.Sprintf("%s%v", cacheRudyGcCRankPeriodIdPrefix, id)
	var resp CRankPeriod
	err := m.QueryRowCtx(ctx, &resp, rudyGcCRankPeriodIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cRankPeriodRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCRankPeriodModel) FindOneByPeriodTypePeriodKeyCategory(ctx context.Context, periodType int64, periodKey string, category int64) (*CRankPeriod, error) {
	rudyGcCRankPeriodPeriodTypePeriodKeyCategoryKey := fmt.Sprintf("%s%v:%v:%v", cacheRudyGcCRankPeriodPeriodTypePeriodKeyCategoryPrefix, periodType, periodKey, category)
	var resp CRankPeriod
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcCRankPeriodPeriodTypePeriodKeyCategoryKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `period_type` = ? and `period_key` = ? and `category` = ? limit 1", cRankPeriodRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, periodType, periodKey, category); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCRankPeriodModel) Insert(ctx context.Context, data *CRankPeriod) (sql.Result, error) {
	rudyGcCRankPeriodIdKey := fmt.Sprintf("%s%v", cacheRudyGcCRankPeriodIdPrefix, data.Id)
	rudyGcCRankPeriodPeriodTypePeriodKeyCategoryKey := fmt.Sprintf("%s%v:%v:%v", cacheRudyGcCRankPeriodPeriodTypePeriodKeyCategoryPrefix, data.PeriodType, data.PeriodKey, data.Category)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, cRankPeriodRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.PeriodType, data.PeriodKey, data.Category, data.StartDayNumber, data.EndDayNumber, data.PickDays, data.TopN, data.Status, data.CreatedOn, data.UpdatedOn)
	}, rudyGcCRankPeriodIdKey, rudyGcCRankPeriodPeriodTypePeriodKeyCategoryKey)
	return ret, err
}

func (m *defaultCRankPeriodModel) Update(ctx context.Context, newData *CRankPeriod) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcCRankPeriodIdKey := fmt.Sprintf("%s%v", cacheRudyGcCRankPeriodIdPrefix, data.Id)
	rudyGcCRankPeriodPeriodTypePeriodKeyCategoryKey := fmt.Sprintf("%s%v:%v:%v", cacheRudyGcCRankPeriodPeriodTypePeriodKeyCategoryPrefix, data.PeriodType, data.PeriodKey, data.Category)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cRankPeriodRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.PeriodType, newData.PeriodKey, newData.Category, newData.StartDayNumber, newData.EndDayNumber, newData.PickDays, newData.TopN, newData.Status, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcCRankPeriodIdKey, rudyGcCRankPeriodPeriodTypePeriodKeyCategoryKey)
	return err
}

func (m *defaultCRankPeriodModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcCRankPeriodIdPrefix, primary)
}

func (m *defaultCRankPeriodModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cRankPeriodRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCRankPeriodModel) tableName() string {
	return m.table
}
