// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cRankPeriodItemFieldNames          = builder.RawFieldNames(&CRankPeriodItem{})
	cRankPeriodItemRows                = strings.Join(cRankPeriodItemFieldNames, ",")
	cRankPeriodItemRowsExpectAutoSet   = strings.Join(stringx.Remove(cRankPeriodItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cRankPeriodItemRowsWithPlaceHolder = strings.Join(stringx.Remove(cRankPeriodItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcCRankPeriodItemIdPrefix                 = "cache:rudyGc:cRankPeriodItem:id:"
	cacheRudyGcCRankPeriodItemPeriodIdMovieJavIdPrefix = "cache:rudyGc:cRankPeriodItem:periodId:movieJavId:"
)

type (
	cRankPeriodItemModel interface {
		Insert(ctx context.Context, data *CRankPeriodItem) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CRankPeriodItem, error)
		FindOneByPeriodIdMovieJavId(ctx context.Context, periodId int64, movieJavId string) (*CRankPeriodItem, error)
		Update(ctx context.Context, data *CRankPeriodItem) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCRankPeriodItemModel struct {
		sqlc.CachedConn
		table string
	}

	CRankPeriodItem struct {
		Id                 int64   `db:"id"`
		PeriodId           int64   `db:"period_id"`             // 周期榜ID
		MovieJavId         string  `db:"movie_jav_id"`          // 影片ID
		RankPos            int64   `db:"rank_pos"`              // 周期名次
		Score              float64 `db:"score"`                 // 周期得分
		DaysInRank         int64   `db:"days_in_rank"`          // 周期内上榜天数
		UsedPickDays       int64   `db:"used_pick_days"`        // 实际参与计算的天数
		FirstRankDayNumber int64   `db:"first_rank_day_number"` // 周期内首次上榜日序号
		LastRankDayNumber  int64   `db:"last_rank_day_number"`  // 周期内最后上榜日序号
		BestRank           int64   `db:"best_rank"`             // 最佳日名次
		WorstPickedRank    int64   `db:"worst_picked_rank"`     // 入选样本中的最差名次
		PrevRank           int64   `db:"prev_rank"`             // 上期名次
		RankChange         int64   `db:"rank_change"`           // 相对上期名次变化
		PeakRank           int64   `db:"peak_rank"`             // 历史最佳周期名次
		CreatedOn          int64   `db:"created_on"`
		UpdatedOn          int64   `db:"updated_on"`
	}
)

func newCRankPeriodItemModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCRankPeriodItemModel {
	return &defaultCRankPeriodItemModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`c_rank_period_item`",
	}
}

func (m *defaultCRankPeriodItemModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcCRankPeriodItemIdKey := fmt.Sprintf("%s%v", cacheRudyGcCRankPeriodItemIdPrefix, id)
	rudyGcCRankPeriodItemPeriodIdMovieJavIdKey := fmt.Sprintf("%s%v:%v", cacheRudyGcCRankPeriodItemPeriodIdMovieJavIdPrefix, data.PeriodId, data.MovieJavId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcCRankPeriodItemIdKey, rudyGcCRankPeriodItemPeriodIdMovieJavIdKey)
	return err
}

func (m *defaultCRankPeriodItemModel) FindOne(ctx context.Context, id int64) (*CRankPeriodItem, error) {
	rudyGcCRankPeriodItemIdKey := fmt.Sprintf("%s%v", cacheRudyGcCRankPeriodItemIdPrefix, id)
	var resp CRankPeriodItem
	err := m.QueryRowCtx(ctx, &resp, rudyGcCRankPeriodItemIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cRankPeriodItemRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCRankPeriodItemModel) FindOneByPeriodIdMovieJavId(ctx context.Context, periodId int64, movieJavId string) (*CRankPeriodItem, error) {
	rudyGcCRankPeriodItemPeriodIdMovieJavIdKey := fmt.Sprintf("%s%v:%v", cacheRudyGcCRankPeriodItemPeriodIdMovieJavIdPrefix, periodId, movieJavId)
	var resp CRankPeriodItem
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcCRankPeriodItemPeriodIdMovieJavIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `period_id` = ? and `movie_jav_id` = ? limit 1", cRankPeriodItemRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, periodId, movieJavId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCRankPeriodItemModel) Insert(ctx context.Context, data *CRankPeriodItem) (sql.Result, error) {
	rudyGcCRankPeriodItemIdKey := fmt.Sprintf("%s%v", cacheRudyGcCRankPeriodItemIdPrefix, data.Id)
	rudyGcCRankPeriodItemPeriodIdMovieJavIdKey := fmt.Sprintf("%s%v:%v", cacheRudyGcCRankPeriodItemPeriodIdMovieJavIdPrefix, data.PeriodId, data.MovieJavId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, cRankPeriodItemRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.PeriodId, data.MovieJavId, data.RankPos, data.Score, data.DaysInRank, data.UsedPickDays, data.FirstRankDayNumber, data.LastRankDayNumber, data.BestRank, data.WorstPickedRank, data.PrevRank, data.RankChange, data.PeakRank, data.CreatedOn, data.UpdatedOn)
	}, rudyGcCRankPeriodItemIdKey, rudyGcCRankPeriodItemPeriodIdMovieJavIdKey)
	return ret, err
}

func (m *defaultCRankPeriodItemModel) Update(ctx context.Context, newData *CRankPeriodItem) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcCRankPeriodItemIdKey := fmt.Sprintf("%s%v", cacheRudyGcCRankPeriodItemIdPrefix, data.Id)
	rudyGcCRankPeriodItemPeriodIdMovieJavIdKey := fmt.Sprintf("%s%v:%v", cacheRudyGcCRankPeriodItemPeriodIdMovieJavIdPrefix, data.PeriodId, data.MovieJavId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cRankPeriodItemRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.PeriodId, newData.MovieJavId, newData.RankPos, newData.Score, newData.DaysInRank, newData.UsedPickDays, newData.FirstRankDayNumber, newData.LastRankDayNumber, newData.BestRank, newData.WorstPickedRank, newData.PrevRank, newData.RankChange, newData.PeakRank, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcCRankPeriodItemIdKey, rudyGcCRankPeriodItemPeriodIdMovieJavIdKey)
	return err
}

func (m *defaultCRankPeriodItemModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcCRankPeriodItemIdPrefix, primary)
}

func (m *defaultCRankPeriodItemModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cRankPeriodItemRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCRankPeriodItemModel) tableName() string {
	return m.table
}
