// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dDetailFieldNames          = builder.RawFieldNames(&DDetail{})
	dDetailRows                = strings.Join(dDetailFieldNames, ",")
	dDetailRowsExpectAutoSet   = strings.Join(stringx.Remove(dDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	dDetailRowsWithPlaceHolder = strings.Join(stringx.Remove(dDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcDDetailIdPrefix    = "cache:rudyGc:dDetail:id:"
	cacheRudyGcDDetailJavIdPrefix = "cache:rudyGc:dDetail:javId:"
)

type (
	dDetailModel interface {
		Insert(ctx context.Context, data *DDetail) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*DDetail, error)
		FindOneByJavId(ctx context.Context, javId string) (*DDetail, error)
		Update(ctx context.Context, data *DDetail) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDDetailModel struct {
		sqlc.CachedConn
		table string
	}

	DDetail struct {
		Id        int64  `db:"id"`
		Name      string `db:"name"`      // 影片名称
		JavId     string `db:"jav_id"`    // JavId唯一标识
		Prefix    string `db:"prefix"`    // 前缀，如 ABC
		QueryUrl  string `db:"query_url"` // 来源请求URL
		Content   string `db:"content"`   // 详情页HTML内容
		CreatedOn int64  `db:"created_on"`
		UpdatedOn int64  `db:"updated_on"`
	}
)

func newDDetailModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultDDetailModel {
	return &defaultDDetailModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`d_detail`",
	}
}

func (m *defaultDDetailModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcDDetailIdKey := fmt.Sprintf("%s%v", cacheRudyGcDDetailIdPrefix, id)
	rudyGcDDetailJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcDDetailJavIdPrefix, data.JavId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcDDetailIdKey, rudyGcDDetailJavIdKey)
	return err
}

func (m *defaultDDetailModel) FindOne(ctx context.Context, id int64) (*DDetail, error) {
	rudyGcDDetailIdKey := fmt.Sprintf("%s%v", cacheRudyGcDDetailIdPrefix, id)
	var resp DDetail
	err := m.QueryRowCtx(ctx, &resp, rudyGcDDetailIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dDetailRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDDetailModel) FindOneByJavId(ctx context.Context, javId string) (*DDetail, error) {
	rudyGcDDetailJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcDDetailJavIdPrefix, javId)
	var resp DDetail
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcDDetailJavIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `jav_id` = ? limit 1", dDetailRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, javId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDDetailModel) Insert(ctx context.Context, data *DDetail) (sql.Result, error) {
	rudyGcDDetailIdKey := fmt.Sprintf("%s%v", cacheRudyGcDDetailIdPrefix, data.Id)
	rudyGcDDetailJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcDDetailJavIdPrefix, data.JavId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, dDetailRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.JavId, data.Prefix, data.QueryUrl, data.Content, data.CreatedOn, data.UpdatedOn)
	}, rudyGcDDetailIdKey, rudyGcDDetailJavIdKey)
	return ret, err
}

func (m *defaultDDetailModel) Update(ctx context.Context, newData *DDetail) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcDDetailIdKey := fmt.Sprintf("%s%v", cacheRudyGcDDetailIdPrefix, data.Id)
	rudyGcDDetailJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcDDetailJavIdPrefix, data.JavId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dDetailRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.JavId, newData.Prefix, newData.QueryUrl, newData.Content, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcDDetailIdKey, rudyGcDDetailJavIdKey)
	return err
}

func (m *defaultDDetailModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcDDetailIdPrefix, primary)
}

func (m *defaultDDetailModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dDetailRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDDetailModel) tableName() string {
	return m.table
}
