// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dSeedFieldNames          = builder.RawFieldNames(&DSeed{})
	dSeedRows                = strings.Join(dSeedFieldNames, ",")
	dSeedRowsExpectAutoSet   = strings.Join(stringx.Remove(dSeedFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	dSeedRowsWithPlaceHolder = strings.Join(stringx.Remove(dSeedFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcDSeedIdPrefix   = "cache:rudyGc:dSeed:id:"
	cacheRudyGcDSeedNamePrefix = "cache:rudyGc:dSeed:name:"
)

type (
	dSeedModel interface {
		Insert(ctx context.Context, data *DSeed) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*DSeed, error)
		FindOneByName(ctx context.Context, name string) (*DSeed, error)
		Update(ctx context.Context, data *DSeed) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDSeedModel struct {
		sqlc.CachedConn
		table string
	}

	DSeed struct {
		Id                             int64  `db:"id"`
		Name                           string `db:"name"`            // '查询名'
		Active                         int64  `db:"active"`          // '状态'
		SearchType                     int64  `db:"search_type"`     // '查询类型'
		NameType                       int64  `db:"name_type"`       // '名称类型'
		PageNow                        int64  `db:"page_now"`        // '当前页'
		Offset                         int64  `db:"offset"`          // '偏移量'
		StartPage                      int64  `db:"start_page"`      // '起始页'
		EndPage                        int64  `db:"end_page"`        // '结束页'
		LastQueryTime                  int64  `db:"last_query_time"` // '最后一次抓取时间'
		LastStatus                     int64  `db:"last_status"`     // '最后状态'
		LastError                      string `db:"last_error"`      // '最后错误摘要'
		CreatedOn                      int64  `db:"created_on"`
		UpdatedOn                      int64  `db:"updated_on"`
		MovieTotal                     int64  `db:"movie_total"`                         // '当前 seed 对应 movie 总量'
		MovieLastAddedTime             int64  `db:"movie_last_added_time"`               // '最后一次 movie 增加时间'
		LastInsertCount                int64  `db:"last_insert_count"`                   // '本轮新增 movie 数'
		MovieLatestReleasingDate       int64  `db:"movie_latest_releasing_date"`         // '当前 seed 最新 movie 的上映时间'
		MovieLatestReleasingMovieJavId string `db:"movie_latest_releasing_movie_jav_id"` // '最新上映 movie 的 jav_id'
		MovieLatestReleasingMovieName  string `db:"movie_latest_releasing_movie_name"`   // '最新上映 movie 的番号 name'
	}
)

func newDSeedModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultDSeedModel {
	return &defaultDSeedModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`d_seed`",
	}
}

func (m *defaultDSeedModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcDSeedIdKey := fmt.Sprintf("%s%v", cacheRudyGcDSeedIdPrefix, id)
	rudyGcDSeedNameKey := fmt.Sprintf("%s%v", cacheRudyGcDSeedNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcDSeedIdKey, rudyGcDSeedNameKey)
	return err
}

func (m *defaultDSeedModel) FindOne(ctx context.Context, id int64) (*DSeed, error) {
	rudyGcDSeedIdKey := fmt.Sprintf("%s%v", cacheRudyGcDSeedIdPrefix, id)
	var resp DSeed
	err := m.QueryRowCtx(ctx, &resp, rudyGcDSeedIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dSeedRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDSeedModel) FindOneByName(ctx context.Context, name string) (*DSeed, error) {
	rudyGcDSeedNameKey := fmt.Sprintf("%s%v", cacheRudyGcDSeedNamePrefix, name)
	var resp DSeed
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcDSeedNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", dSeedRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDSeedModel) Insert(ctx context.Context, data *DSeed) (sql.Result, error) {
	rudyGcDSeedIdKey := fmt.Sprintf("%s%v", cacheRudyGcDSeedIdPrefix, data.Id)
	rudyGcDSeedNameKey := fmt.Sprintf("%s%v", cacheRudyGcDSeedNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, dSeedRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Active, data.SearchType, data.NameType, data.PageNow, data.Offset, data.StartPage, data.EndPage, data.LastQueryTime, data.LastStatus, data.LastError, data.CreatedOn, data.UpdatedOn, data.MovieTotal, data.MovieLastAddedTime, data.LastInsertCount, data.MovieLatestReleasingDate, data.MovieLatestReleasingMovieJavId, data.MovieLatestReleasingMovieName)
	}, rudyGcDSeedIdKey, rudyGcDSeedNameKey)
	return ret, err
}

func (m *defaultDSeedModel) Update(ctx context.Context, newData *DSeed) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcDSeedIdKey := fmt.Sprintf("%s%v", cacheRudyGcDSeedIdPrefix, data.Id)
	rudyGcDSeedNameKey := fmt.Sprintf("%s%v", cacheRudyGcDSeedNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dSeedRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Active, newData.SearchType, newData.NameType, newData.PageNow, newData.Offset, newData.StartPage, newData.EndPage, newData.LastQueryTime, newData.LastStatus, newData.LastError, newData.CreatedOn, newData.UpdatedOn, newData.MovieTotal, newData.MovieLastAddedTime, newData.LastInsertCount, newData.MovieLatestReleasingDate, newData.MovieLatestReleasingMovieJavId, newData.MovieLatestReleasingMovieName, newData.Id)
	}, rudyGcDSeedIdKey, rudyGcDSeedNameKey)
	return err
}

func (m *defaultDSeedModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcDSeedIdPrefix, primary)
}

func (m *defaultDSeedModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dSeedRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDSeedModel) tableName() string {
	return m.table
}
