// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gListFieldNames          = builder.RawFieldNames(&GList{})
	gListRows                = strings.Join(gListFieldNames, ",")
	gListRowsExpectAutoSet   = strings.Join(stringx.Remove(gListFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gListRowsWithPlaceHolder = strings.Join(stringx.Remove(gListFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcGListIdPrefix   = "cache:rudyGc:gList:id:"
	cacheRudyGcGListNamePrefix = "cache:rudyGc:gList:name:"
)

type (
	gListModel interface {
		Insert(ctx context.Context, data *GList) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GList, error)
		FindOneByName(ctx context.Context, name string) (*GList, error)
		Update(ctx context.Context, data *GList) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGListModel struct {
		sqlc.CachedConn
		table string
	}

	GList struct {
		Id         int64  `db:"id"`
		Name       string `db:"name"`
		ScName     string `db:"sc_name"`
		MovieJavId string `db:"movie_jav_id"`
		IsCome     int64  `db:"is_come"`
		CreatedOn  int64  `db:"created_on"`
		UpdatedOn  int64  `db:"updated_on"`
		IsSc       int64  `db:"is_sc"`
	}
)

func newGListModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGListModel {
	return &defaultGListModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`g_list`",
	}
}

func (m *defaultGListModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcGListIdKey := fmt.Sprintf("%s%v", cacheRudyGcGListIdPrefix, id)
	rudyGcGListNameKey := fmt.Sprintf("%s%v", cacheRudyGcGListNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcGListIdKey, rudyGcGListNameKey)
	return err
}

func (m *defaultGListModel) FindOne(ctx context.Context, id int64) (*GList, error) {
	rudyGcGListIdKey := fmt.Sprintf("%s%v", cacheRudyGcGListIdPrefix, id)
	var resp GList
	err := m.QueryRowCtx(ctx, &resp, rudyGcGListIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gListRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGListModel) FindOneByName(ctx context.Context, name string) (*GList, error) {
	rudyGcGListNameKey := fmt.Sprintf("%s%v", cacheRudyGcGListNamePrefix, name)
	var resp GList
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcGListNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", gListRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGListModel) Insert(ctx context.Context, data *GList) (sql.Result, error) {
	rudyGcGListIdKey := fmt.Sprintf("%s%v", cacheRudyGcGListIdPrefix, data.Id)
	rudyGcGListNameKey := fmt.Sprintf("%s%v", cacheRudyGcGListNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, gListRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.ScName, data.MovieJavId, data.IsCome, data.CreatedOn, data.UpdatedOn, data.IsSc)
	}, rudyGcGListIdKey, rudyGcGListNameKey)
	return ret, err
}

func (m *defaultGListModel) Update(ctx context.Context, newData *GList) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcGListIdKey := fmt.Sprintf("%s%v", cacheRudyGcGListIdPrefix, data.Id)
	rudyGcGListNameKey := fmt.Sprintf("%s%v", cacheRudyGcGListNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gListRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.ScName, newData.MovieJavId, newData.IsCome, newData.CreatedOn, newData.UpdatedOn, newData.IsSc, newData.Id)
	}, rudyGcGListIdKey, rudyGcGListNameKey)
	return err
}

func (m *defaultGListModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcGListIdPrefix, primary)
}

func (m *defaultGListModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gListRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGListModel) tableName() string {
	return m.table
}
