// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gScStatFieldNames          = builder.RawFieldNames(&GScStat{})
	gScStatRows                = strings.Join(gScStatFieldNames, ",")
	gScStatRowsExpectAutoSet   = strings.Join(stringx.Remove(gScStatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gScStatRowsWithPlaceHolder = strings.Join(stringx.Remove(gScStatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcGScStatIdPrefix         = "cache:rudyGc:gScStat:id:"
	cacheRudyGcGScStatMovieJavIdPrefix = "cache:rudyGc:gScStat:movieJavId:"
)

type (
	gScStatModel interface {
		Insert(ctx context.Context, data *GScStat) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GScStat, error)
		FindOneByMovieJavId(ctx context.Context, movieJavId string) (*GScStat, error)
		Update(ctx context.Context, data *GScStat) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGScStatModel struct {
		sqlc.CachedConn
		table string
	}

	GScStat struct {
		Id             int64  `db:"id"`
		MovieJavId     string `db:"movie_jav_id"`
		MovieName      string `db:"movie_name"`
		ScTimes        int64  `db:"sc_times"`
		ComeTimes      int64  `db:"come_times"`
		LastScTime     int64  `db:"last_sc_time"`
		ReleasingDate  int64  `db:"releasing_date"`
		MediaBirthTime int64  `db:"media_birth_time"`
		CreatedOn      int64  `db:"created_on"`
		UpdatedOn      int64  `db:"updated_on"`
		ScEventTimes   int64  `db:"sc_event_times"`
	}
)

func newGScStatModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGScStatModel {
	return &defaultGScStatModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`g_sc_stat`",
	}
}

func (m *defaultGScStatModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcGScStatIdKey := fmt.Sprintf("%s%v", cacheRudyGcGScStatIdPrefix, id)
	rudyGcGScStatMovieJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcGScStatMovieJavIdPrefix, data.MovieJavId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcGScStatIdKey, rudyGcGScStatMovieJavIdKey)
	return err
}

func (m *defaultGScStatModel) FindOne(ctx context.Context, id int64) (*GScStat, error) {
	rudyGcGScStatIdKey := fmt.Sprintf("%s%v", cacheRudyGcGScStatIdPrefix, id)
	var resp GScStat
	err := m.QueryRowCtx(ctx, &resp, rudyGcGScStatIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gScStatRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGScStatModel) FindOneByMovieJavId(ctx context.Context, movieJavId string) (*GScStat, error) {
	rudyGcGScStatMovieJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcGScStatMovieJavIdPrefix, movieJavId)
	var resp GScStat
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcGScStatMovieJavIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `movie_jav_id` = ? limit 1", gScStatRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, movieJavId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGScStatModel) Insert(ctx context.Context, data *GScStat) (sql.Result, error) {
	rudyGcGScStatIdKey := fmt.Sprintf("%s%v", cacheRudyGcGScStatIdPrefix, data.Id)
	rudyGcGScStatMovieJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcGScStatMovieJavIdPrefix, data.MovieJavId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, gScStatRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MovieJavId, data.MovieName, data.ScTimes, data.ComeTimes, data.LastScTime, data.ReleasingDate, data.MediaBirthTime, data.CreatedOn, data.UpdatedOn, data.ScEventTimes)
	}, rudyGcGScStatIdKey, rudyGcGScStatMovieJavIdKey)
	return ret, err
}

func (m *defaultGScStatModel) Update(ctx context.Context, newData *GScStat) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcGScStatIdKey := fmt.Sprintf("%s%v", cacheRudyGcGScStatIdPrefix, data.Id)
	rudyGcGScStatMovieJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcGScStatMovieJavIdPrefix, data.MovieJavId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gScStatRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MovieJavId, newData.MovieName, newData.ScTimes, newData.ComeTimes, newData.LastScTime, newData.ReleasingDate, newData.MediaBirthTime, newData.CreatedOn, newData.UpdatedOn, newData.ScEventTimes, newData.Id)
	}, rudyGcGScStatIdKey, rudyGcGScStatMovieJavIdKey)
	return err
}

func (m *defaultGScStatModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcGScStatIdPrefix, primary)
}

func (m *defaultGScStatModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gScStatRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGScStatModel) tableName() string {
	return m.table
}
