// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tAlbumFieldNames          = builder.RawFieldNames(&TAlbum{})
	tAlbumRows                = strings.Join(tAlbumFieldNames, ",")
	tAlbumRowsExpectAutoSet   = strings.Join(stringx.Remove(tAlbumFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tAlbumRowsWithPlaceHolder = strings.Join(stringx.Remove(tAlbumFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcTAlbumIdPrefix   = "cache:rudyGc:tAlbum:id:"
	cacheRudyGcTAlbumNamePrefix = "cache:rudyGc:tAlbum:name:"
)

type (
	tAlbumModel interface {
		Insert(ctx context.Context, data *TAlbum) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TAlbum, error)
		FindOneByName(ctx context.Context, name string) (*TAlbum, error)
		Update(ctx context.Context, data *TAlbum) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTAlbumModel struct {
		sqlc.CachedConn
		table string
	}

	TAlbum struct {
		Id        int64  `db:"id"`
		Name      string `db:"name"`
		Remark    string `db:"remark"`
		CreatedOn int64  `db:"created_on"`
		UpdatedOn int64  `db:"updated_on"`
	}
)

func newTAlbumModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTAlbumModel {
	return &defaultTAlbumModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_album`",
	}
}

func (m *defaultTAlbumModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcTAlbumIdKey := fmt.Sprintf("%s%v", cacheRudyGcTAlbumIdPrefix, id)
	rudyGcTAlbumNameKey := fmt.Sprintf("%s%v", cacheRudyGcTAlbumNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcTAlbumIdKey, rudyGcTAlbumNameKey)
	return err
}

func (m *defaultTAlbumModel) FindOne(ctx context.Context, id int64) (*TAlbum, error) {
	rudyGcTAlbumIdKey := fmt.Sprintf("%s%v", cacheRudyGcTAlbumIdPrefix, id)
	var resp TAlbum
	err := m.QueryRowCtx(ctx, &resp, rudyGcTAlbumIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tAlbumRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTAlbumModel) FindOneByName(ctx context.Context, name string) (*TAlbum, error) {
	rudyGcTAlbumNameKey := fmt.Sprintf("%s%v", cacheRudyGcTAlbumNamePrefix, name)
	var resp TAlbum
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcTAlbumNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", tAlbumRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTAlbumModel) Insert(ctx context.Context, data *TAlbum) (sql.Result, error) {
	rudyGcTAlbumIdKey := fmt.Sprintf("%s%v", cacheRudyGcTAlbumIdPrefix, data.Id)
	rudyGcTAlbumNameKey := fmt.Sprintf("%s%v", cacheRudyGcTAlbumNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, tAlbumRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Remark, data.CreatedOn, data.UpdatedOn)
	}, rudyGcTAlbumIdKey, rudyGcTAlbumNameKey)
	return ret, err
}

func (m *defaultTAlbumModel) Update(ctx context.Context, newData *TAlbum) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcTAlbumIdKey := fmt.Sprintf("%s%v", cacheRudyGcTAlbumIdPrefix, data.Id)
	rudyGcTAlbumNameKey := fmt.Sprintf("%s%v", cacheRudyGcTAlbumNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tAlbumRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Remark, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcTAlbumIdKey, rudyGcTAlbumNameKey)
	return err
}

func (m *defaultTAlbumModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcTAlbumIdPrefix, primary)
}

func (m *defaultTAlbumModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tAlbumRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTAlbumModel) tableName() string {
	return m.table
}
