// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tFetchSiteFieldNames          = builder.RawFieldNames(&TFetchSite{})
	tFetchSiteRows                = strings.Join(tFetchSiteFieldNames, ",")
	tFetchSiteRowsExpectAutoSet   = strings.Join(stringx.Remove(tFetchSiteFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tFetchSiteRowsWithPlaceHolder = strings.Join(stringx.Remove(tFetchSiteFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcTFetchSiteIdPrefix       = "cache:rudyGc:tFetchSite:id:"
	cacheRudyGcTFetchSiteSiteCodePrefix = "cache:rudyGc:tFetchSite:siteCode:"
)

type (
	tFetchSiteModel interface {
		Insert(ctx context.Context, data *TFetchSite) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TFetchSite, error)
		FindOneBySiteCode(ctx context.Context, siteCode string) (*TFetchSite, error)
		Update(ctx context.Context, data *TFetchSite) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTFetchSiteModel struct {
		sqlc.CachedConn
		table string
	}

	TFetchSite struct {
		Id             int64  `db:"id"`
		SiteCode       string `db:"site_code"`
		SiteName       string `db:"site_name"`
		BaseUrl        string `db:"base_url"`
		UserAgent      string `db:"user_agent"`
		Cookie         string `db:"cookie"`
		Proxy          string `db:"proxy"`
		TimeoutSeconds int64  `db:"timeout_seconds"`
		RequestSleepMs int64  `db:"request_sleep_ms"`
		RetrySleepMs   int64  `db:"retry_sleep_ms"`
		MaxRetryTimes  int64  `db:"max_retry_times"`
		Status         int64  `db:"status"`
		CreatedOn      int64  `db:"created_on"`
		UpdatedOn      int64  `db:"updated_on"`
	}
)

func newTFetchSiteModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTFetchSiteModel {
	return &defaultTFetchSiteModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_fetch_site`",
	}
}

func (m *defaultTFetchSiteModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcTFetchSiteIdKey := fmt.Sprintf("%s%v", cacheRudyGcTFetchSiteIdPrefix, id)
	rudyGcTFetchSiteSiteCodeKey := fmt.Sprintf("%s%v", cacheRudyGcTFetchSiteSiteCodePrefix, data.SiteCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcTFetchSiteIdKey, rudyGcTFetchSiteSiteCodeKey)
	return err
}

func (m *defaultTFetchSiteModel) FindOne(ctx context.Context, id int64) (*TFetchSite, error) {
	rudyGcTFetchSiteIdKey := fmt.Sprintf("%s%v", cacheRudyGcTFetchSiteIdPrefix, id)
	var resp TFetchSite
	err := m.QueryRowCtx(ctx, &resp, rudyGcTFetchSiteIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tFetchSiteRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTFetchSiteModel) FindOneBySiteCode(ctx context.Context, siteCode string) (*TFetchSite, error) {
	rudyGcTFetchSiteSiteCodeKey := fmt.Sprintf("%s%v", cacheRudyGcTFetchSiteSiteCodePrefix, siteCode)
	var resp TFetchSite
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcTFetchSiteSiteCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `site_code` = ? limit 1", tFetchSiteRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, siteCode); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTFetchSiteModel) Insert(ctx context.Context, data *TFetchSite) (sql.Result, error) {
	rudyGcTFetchSiteIdKey := fmt.Sprintf("%s%v", cacheRudyGcTFetchSiteIdPrefix, data.Id)
	rudyGcTFetchSiteSiteCodeKey := fmt.Sprintf("%s%v", cacheRudyGcTFetchSiteSiteCodePrefix, data.SiteCode)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tFetchSiteRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.SiteCode, data.SiteName, data.BaseUrl, data.UserAgent, data.Cookie, data.Proxy, data.TimeoutSeconds, data.RequestSleepMs, data.RetrySleepMs, data.MaxRetryTimes, data.Status, data.CreatedOn, data.UpdatedOn)
	}, rudyGcTFetchSiteIdKey, rudyGcTFetchSiteSiteCodeKey)
	return ret, err
}

func (m *defaultTFetchSiteModel) Update(ctx context.Context, newData *TFetchSite) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcTFetchSiteIdKey := fmt.Sprintf("%s%v", cacheRudyGcTFetchSiteIdPrefix, data.Id)
	rudyGcTFetchSiteSiteCodeKey := fmt.Sprintf("%s%v", cacheRudyGcTFetchSiteSiteCodePrefix, data.SiteCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tFetchSiteRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.SiteCode, newData.SiteName, newData.BaseUrl, newData.UserAgent, newData.Cookie, newData.Proxy, newData.TimeoutSeconds, newData.RequestSleepMs, newData.RetrySleepMs, newData.MaxRetryTimes, newData.Status, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcTFetchSiteIdKey, rudyGcTFetchSiteSiteCodeKey)
	return err
}

func (m *defaultTFetchSiteModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcTFetchSiteIdPrefix, primary)
}

func (m *defaultTFetchSiteModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tFetchSiteRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTFetchSiteModel) tableName() string {
	return m.table
}
