// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	wMediaBirthTopStatFieldNames          = builder.RawFieldNames(&WMediaBirthTopStat{})
	wMediaBirthTopStatRows                = strings.Join(wMediaBirthTopStatFieldNames, ",")
	wMediaBirthTopStatRowsExpectAutoSet   = strings.Join(stringx.Remove(wMediaBirthTopStatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	wMediaBirthTopStatRowsWithPlaceHolder = strings.Join(stringx.Remove(wMediaBirthTopStatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcWMediaBirthTopStatIdPrefix                    = "cache:rudyGc:wMediaBirthTopStat:id:"
	cacheRudyGcWMediaBirthTopStatScopeKeyAggTypeAggKeyPrefix = "cache:rudyGc:wMediaBirthTopStat:scopeKey:aggType:aggKey:"
)

type (
	wMediaBirthTopStatModel interface {
		Insert(ctx context.Context, data *WMediaBirthTopStat) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*WMediaBirthTopStat, error)
		FindOneByScopeKeyAggTypeAggKey(ctx context.Context, scopeKey string, aggType string, aggKey string) (*WMediaBirthTopStat, error)
		Update(ctx context.Context, data *WMediaBirthTopStat) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWMediaBirthTopStatModel struct {
		sqlc.CachedConn
		table string
	}

	WMediaBirthTopStat struct {
		Id         int64  `db:"id"`
		ScopeKey   string `db:"scope_key"`
		Level      string `db:"level"`
		Year       int64  `db:"year"`
		Quarter    int64  `db:"quarter"`
		Month      int64  `db:"month"`
		Day        int64  `db:"day"`
		AggType    string `db:"agg_type"`
		AggKey     string `db:"agg_key"`
		AggId      int64  `db:"agg_id"`
		AggName    string `db:"agg_name"`
		MediaCount int64  `db:"media_count"`
		SizeBytes  int64  `db:"size_bytes"`
		RankNo     int64  `db:"rank_no"`
		CreatedOn  int64  `db:"created_on"`
		UpdatedOn  int64  `db:"updated_on"`
	}
)

func newWMediaBirthTopStatModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultWMediaBirthTopStatModel {
	return &defaultWMediaBirthTopStatModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`w_media_birth_top_stat`",
	}
}

func (m *defaultWMediaBirthTopStatModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcWMediaBirthTopStatIdKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaBirthTopStatIdPrefix, id)
	rudyGcWMediaBirthTopStatScopeKeyAggTypeAggKeyKey := fmt.Sprintf("%s%v:%v:%v", cacheRudyGcWMediaBirthTopStatScopeKeyAggTypeAggKeyPrefix, data.ScopeKey, data.AggType, data.AggKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcWMediaBirthTopStatIdKey, rudyGcWMediaBirthTopStatScopeKeyAggTypeAggKeyKey)
	return err
}

func (m *defaultWMediaBirthTopStatModel) FindOne(ctx context.Context, id int64) (*WMediaBirthTopStat, error) {
	rudyGcWMediaBirthTopStatIdKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaBirthTopStatIdPrefix, id)
	var resp WMediaBirthTopStat
	err := m.QueryRowCtx(ctx, &resp, rudyGcWMediaBirthTopStatIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", wMediaBirthTopStatRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWMediaBirthTopStatModel) FindOneByScopeKeyAggTypeAggKey(ctx context.Context, scopeKey string, aggType string, aggKey string) (*WMediaBirthTopStat, error) {
	rudyGcWMediaBirthTopStatScopeKeyAggTypeAggKeyKey := fmt.Sprintf("%s%v:%v:%v", cacheRudyGcWMediaBirthTopStatScopeKeyAggTypeAggKeyPrefix, scopeKey, aggType, aggKey)
	var resp WMediaBirthTopStat
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcWMediaBirthTopStatScopeKeyAggTypeAggKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `scope_key` = ? and `agg_type` = ? and `agg_key` = ? limit 1", wMediaBirthTopStatRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, scopeKey, aggType, aggKey); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWMediaBirthTopStatModel) Insert(ctx context.Context, data *WMediaBirthTopStat) (sql.Result, error) {
	rudyGcWMediaBirthTopStatIdKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaBirthTopStatIdPrefix, data.Id)
	rudyGcWMediaBirthTopStatScopeKeyAggTypeAggKeyKey := fmt.Sprintf("%s%v:%v:%v", cacheRudyGcWMediaBirthTopStatScopeKeyAggTypeAggKeyPrefix, data.ScopeKey, data.AggType, data.AggKey)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, wMediaBirthTopStatRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ScopeKey, data.Level, data.Year, data.Quarter, data.Month, data.Day, data.AggType, data.AggKey, data.AggId, data.AggName, data.MediaCount, data.SizeBytes, data.RankNo, data.CreatedOn, data.UpdatedOn)
	}, rudyGcWMediaBirthTopStatIdKey, rudyGcWMediaBirthTopStatScopeKeyAggTypeAggKeyKey)
	return ret, err
}

func (m *defaultWMediaBirthTopStatModel) Update(ctx context.Context, newData *WMediaBirthTopStat) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcWMediaBirthTopStatIdKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaBirthTopStatIdPrefix, data.Id)
	rudyGcWMediaBirthTopStatScopeKeyAggTypeAggKeyKey := fmt.Sprintf("%s%v:%v:%v", cacheRudyGcWMediaBirthTopStatScopeKeyAggTypeAggKeyPrefix, data.ScopeKey, data.AggType, data.AggKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, wMediaBirthTopStatRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ScopeKey, newData.Level, newData.Year, newData.Quarter, newData.Month, newData.Day, newData.AggType, newData.AggKey, newData.AggId, newData.AggName, newData.MediaCount, newData.SizeBytes, newData.RankNo, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcWMediaBirthTopStatIdKey, rudyGcWMediaBirthTopStatScopeKeyAggTypeAggKeyKey)
	return err
}

func (m *defaultWMediaBirthTopStatModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcWMediaBirthTopStatIdPrefix, primary)
}

func (m *defaultWMediaBirthTopStatModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", wMediaBirthTopStatRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultWMediaBirthTopStatModel) tableName() string {
	return m.table
}
