// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	wMediaBirthBucketStatFieldNames          = builder.RawFieldNames(&WMediaBirthBucketStat{})
	wMediaBirthBucketStatRows                = strings.Join(wMediaBirthBucketStatFieldNames, ",")
	wMediaBirthBucketStatRowsExpectAutoSet   = strings.Join(stringx.Remove(wMediaBirthBucketStatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	wMediaBirthBucketStatRowsWithPlaceHolder = strings.Join(stringx.Remove(wMediaBirthBucketStatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcWMediaBirthBucketStatIdPrefix       = "cache:rudyGc:wMediaBirthBucketStat:id:"
	cacheRudyGcWMediaBirthBucketStatScopeKeyPrefix = "cache:rudyGc:wMediaBirthBucketStat:scopeKey:"
)

type (
	wMediaBirthBucketStatModel interface {
		Insert(ctx context.Context, data *WMediaBirthBucketStat) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*WMediaBirthBucketStat, error)
		FindOneByScopeKey(ctx context.Context, scopeKey string) (*WMediaBirthBucketStat, error)
		Update(ctx context.Context, data *WMediaBirthBucketStat) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWMediaBirthBucketStatModel struct {
		sqlc.CachedConn
		table string
	}

	WMediaBirthBucketStat struct {
		Id              int64  `db:"id"`
		ScopeKey        string `db:"scope_key"`
		Level           string `db:"level"`
		Year            int64  `db:"year"`
		Quarter         int64  `db:"quarter"`
		Month           int64  `db:"month"`
		Day             int64  `db:"day"`
		MediaCount      int64  `db:"media_count"`
		RemovedCount    int64  `db:"removed_count"`
		SizeBytes       int64  `db:"size_bytes"`
		HasSubCount     int64  `db:"has_sub_count"`
		LatestBirthTime int64  `db:"latest_birth_time"`
		CreatedOn       int64  `db:"created_on"`
		UpdatedOn       int64  `db:"updated_on"`
	}
)

func newWMediaBirthBucketStatModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultWMediaBirthBucketStatModel {
	return &defaultWMediaBirthBucketStatModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`w_media_birth_bucket_stat`",
	}
}

func (m *defaultWMediaBirthBucketStatModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcWMediaBirthBucketStatIdKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaBirthBucketStatIdPrefix, id)
	rudyGcWMediaBirthBucketStatScopeKeyKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaBirthBucketStatScopeKeyPrefix, data.ScopeKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcWMediaBirthBucketStatIdKey, rudyGcWMediaBirthBucketStatScopeKeyKey)
	return err
}

func (m *defaultWMediaBirthBucketStatModel) FindOne(ctx context.Context, id int64) (*WMediaBirthBucketStat, error) {
	rudyGcWMediaBirthBucketStatIdKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaBirthBucketStatIdPrefix, id)
	var resp WMediaBirthBucketStat
	err := m.QueryRowCtx(ctx, &resp, rudyGcWMediaBirthBucketStatIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", wMediaBirthBucketStatRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWMediaBirthBucketStatModel) FindOneByScopeKey(ctx context.Context, scopeKey string) (*WMediaBirthBucketStat, error) {
	rudyGcWMediaBirthBucketStatScopeKeyKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaBirthBucketStatScopeKeyPrefix, scopeKey)
	var resp WMediaBirthBucketStat
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcWMediaBirthBucketStatScopeKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `scope_key` = ? limit 1", wMediaBirthBucketStatRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, scopeKey); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWMediaBirthBucketStatModel) Insert(ctx context.Context, data *WMediaBirthBucketStat) (sql.Result, error) {
	rudyGcWMediaBirthBucketStatIdKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaBirthBucketStatIdPrefix, data.Id)
	rudyGcWMediaBirthBucketStatScopeKeyKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaBirthBucketStatScopeKeyPrefix, data.ScopeKey)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, wMediaBirthBucketStatRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ScopeKey, data.Level, data.Year, data.Quarter, data.Month, data.Day, data.MediaCount, data.RemovedCount, data.SizeBytes, data.HasSubCount, data.LatestBirthTime, data.CreatedOn, data.UpdatedOn)
	}, rudyGcWMediaBirthBucketStatIdKey, rudyGcWMediaBirthBucketStatScopeKeyKey)
	return ret, err
}

func (m *defaultWMediaBirthBucketStatModel) Update(ctx context.Context, newData *WMediaBirthBucketStat) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcWMediaBirthBucketStatIdKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaBirthBucketStatIdPrefix, data.Id)
	rudyGcWMediaBirthBucketStatScopeKeyKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaBirthBucketStatScopeKeyPrefix, data.ScopeKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, wMediaBirthBucketStatRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ScopeKey, newData.Level, newData.Year, newData.Quarter, newData.Month, newData.Day, newData.MediaCount, newData.RemovedCount, newData.SizeBytes, newData.HasSubCount, newData.LatestBirthTime, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcWMediaBirthBucketStatIdKey, rudyGcWMediaBirthBucketStatScopeKeyKey)
	return err
}

func (m *defaultWMediaBirthBucketStatModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcWMediaBirthBucketStatIdPrefix, primary)
}

func (m *defaultWMediaBirthBucketStatModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", wMediaBirthBucketStatRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultWMediaBirthBucketStatModel) tableName() string {
	return m.table
}
