// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package spiderx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dBestinvFieldNames          = builder.RawFieldNames(&DBestinv{})
	dBestinvRows                = strings.Join(dBestinvFieldNames, ",")
	dBestinvRowsExpectAutoSet   = strings.Join(stringx.Remove(dBestinvFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	dBestinvRowsWithPlaceHolder = strings.Join(stringx.Remove(dBestinvFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	dBestinvModel interface {
		Insert(ctx context.Context, data *DBestinv) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*DBestinv, error)
		FindOneByName(ctx context.Context, name string) (*DBestinv, error)
		Update(ctx context.Context, data *DBestinv) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDBestinvModel struct {
		conn  sqlx.SqlConn
		table string
	}

	DBestinv struct {
		Id            int64  `db:"id"`
		Name          string `db:"name"`            // 唯一名(由query+page组合)
		NeedScan      int64  `db:"need_scan"`       // 是否需要进一步扫描(由业务常量定义)
		NeedRankCheck int64  `db:"need_rank_check"` // 是否需要检查排名(由业务常量定义)
		Category      int64  `db:"category"`        // 类别(取值由业务常量定义)
		Page          int64  `db:"page"`            // 页码
		DayNumber     int64  `db:"day_number"`      // 排名对应的日序号
		Content       string `db:"content"`         // 页面HTML原文
		LastQueryTime int64  `db:"last_query_time"` // 最后抓取时间(Unix秒)
		Date          string `db:"date"`            // 抓取日期字符串
		CreatedOn     int64  `db:"created_on"`      // 创建时间(Unix秒)
		UpdatedOn     int64  `db:"updated_on"`      // 更新时间(Unix秒)
	}
)

func newDBestinvModel(conn sqlx.SqlConn) *defaultDBestinvModel {
	return &defaultDBestinvModel{
		conn:  conn,
		table: "`d_bestinv`",
	}
}

func (m *defaultDBestinvModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDBestinvModel) FindOne(ctx context.Context, id int64) (*DBestinv, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dBestinvRows, m.table)
	var resp DBestinv
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDBestinvModel) FindOneByName(ctx context.Context, name string) (*DBestinv, error) {
	var resp DBestinv
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", dBestinvRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDBestinvModel) Insert(ctx context.Context, data *DBestinv) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, dBestinvRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.NeedScan, data.NeedRankCheck, data.Category, data.Page, data.DayNumber, data.Content, data.LastQueryTime, data.Date, data.CreatedOn, data.UpdatedOn)
	return ret, err
}

func (m *defaultDBestinvModel) Update(ctx context.Context, newData *DBestinv) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dBestinvRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.NeedScan, newData.NeedRankCheck, newData.Category, newData.Page, newData.DayNumber, newData.Content, newData.LastQueryTime, newData.Date, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	return err
}

func (m *defaultDBestinvModel) tableName() string {
	return m.table
}
