// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package spiderx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dInventoryFieldNames          = builder.RawFieldNames(&DInventory{})
	dInventoryRows                = strings.Join(dInventoryFieldNames, ",")
	dInventoryRowsExpectAutoSet   = strings.Join(stringx.Remove(dInventoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	dInventoryRowsWithPlaceHolder = strings.Join(stringx.Remove(dInventoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	dInventoryModel interface {
		Insert(ctx context.Context, data *DInventory) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*DInventory, error)
		FindOneByName(ctx context.Context, name string) (*DInventory, error)
		Update(ctx context.Context, data *DInventory) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDInventoryModel struct {
		conn  sqlx.SqlConn
		table string
	}

	DInventory struct {
		Id            int64  `db:"id"`
		Name          string `db:"name"`            // 唯一名(由query+page组合)
		NeedScan      int64  `db:"need_scan"`       // 是否需要扫描(0=不需要,1=需要)
		Keyword       string `db:"keyword"`         // 来源的关键字(前缀或标签)
		Parent        string `db:"parent"`          // 上级queryBy
		Page          int64  `db:"page"`            // 页码
		Content       string `db:"content"`         // 页面HTML内容
		Category      int64  `db:"category"`        // 类别(1=Prefix,2=Label)
		LastQueryTime int64  `db:"last_query_time"` // 最后抓取时间(Unix秒)
		CreatedOn     int64  `db:"created_on"`
		UpdatedOn     int64  `db:"updated_on"`
	}
)

func newDInventoryModel(conn sqlx.SqlConn) *defaultDInventoryModel {
	return &defaultDInventoryModel{
		conn:  conn,
		table: "`d_inventory`",
	}
}

func (m *defaultDInventoryModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDInventoryModel) FindOne(ctx context.Context, id int64) (*DInventory, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dInventoryRows, m.table)
	var resp DInventory
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDInventoryModel) FindOneByName(ctx context.Context, name string) (*DInventory, error) {
	var resp DInventory
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", dInventoryRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDInventoryModel) Insert(ctx context.Context, data *DInventory) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, dInventoryRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.NeedScan, data.Keyword, data.Parent, data.Page, data.Content, data.Category, data.LastQueryTime, data.CreatedOn, data.UpdatedOn)
	return ret, err
}

func (m *defaultDInventoryModel) Update(ctx context.Context, newData *DInventory) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dInventoryRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.NeedScan, newData.Keyword, newData.Parent, newData.Page, newData.Content, newData.Category, newData.LastQueryTime, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	return err
}

func (m *defaultDInventoryModel) tableName() string {
	return m.table
}
