// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	amCastFieldNames          = builder.RawFieldNames(&AmCast{})
	amCastRows                = strings.Join(amCastFieldNames, ",")
	amCastRowsExpectAutoSet   = strings.Join(stringx.Remove(amCastFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	amCastRowsWithPlaceHolder = strings.Join(stringx.Remove(amCastFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcAmCastIdPrefix   = "cache:rudyGc:amCast:id:"
	cacheRudyGcAmCastNamePrefix = "cache:rudyGc:amCast:name:"
)

type (
	amCastModel interface {
		Insert(ctx context.Context, data *AmCast) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AmCast, error)
		FindOneByName(ctx context.Context, name string) (*AmCast, error)
		Update(ctx context.Context, data *AmCast) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAmCastModel struct {
		sqlc.CachedConn
		table string
	}

	AmCast struct {
		Id                 int64  `db:"id"`
		Name               string `db:"name"`
		JavId              string `db:"jav_id"`
		MovieNumber        int64  `db:"movie_number"`
		OwnedMovieNumber   int64  `db:"owned_movie_number"`
		OwnedWMediaNumber  int64  `db:"owned_w_media_number"`
		ScTimes            int64  `db:"sc_times"`
		ComeTimes          int64  `db:"come_times"`
		LastScTime         int64  `db:"last_sc_time"`
		Rank500MovieNumber int64  `db:"rank500_movie_number"`
		Rank20MovieNumber  int64  `db:"rank20_movie_number"`
		Rank1MovieNumber   int64  `db:"rank1_movie_number"`
		HighestRank        int64  `db:"highest_rank"`
		RankTimes          int64  `db:"rank_times"`
		CreatedOn          int64  `db:"created_on"`
		UpdatedOn          int64  `db:"updated_on"`
		PersonId           int64  `db:"person_id"`
	}
)

func newAmCastModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAmCastModel {
	return &defaultAmCastModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`am_cast`",
	}
}

func (m *defaultAmCastModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcAmCastIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmCastIdPrefix, id)
	rudyGcAmCastNameKey := fmt.Sprintf("%s%v", cacheRudyGcAmCastNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcAmCastIdKey, rudyGcAmCastNameKey)
	return err
}

func (m *defaultAmCastModel) FindOne(ctx context.Context, id int64) (*AmCast, error) {
	rudyGcAmCastIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmCastIdPrefix, id)
	var resp AmCast
	err := m.QueryRowCtx(ctx, &resp, rudyGcAmCastIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amCastRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmCastModel) FindOneByName(ctx context.Context, name string) (*AmCast, error) {
	rudyGcAmCastNameKey := fmt.Sprintf("%s%v", cacheRudyGcAmCastNamePrefix, name)
	var resp AmCast
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcAmCastNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", amCastRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmCastModel) Insert(ctx context.Context, data *AmCast) (sql.Result, error) {
	rudyGcAmCastIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmCastIdPrefix, data.Id)
	rudyGcAmCastNameKey := fmt.Sprintf("%s%v", cacheRudyGcAmCastNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, amCastRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.JavId, data.MovieNumber, data.OwnedMovieNumber, data.OwnedWMediaNumber, data.ScTimes, data.ComeTimes, data.LastScTime, data.Rank500MovieNumber, data.Rank20MovieNumber, data.Rank1MovieNumber, data.HighestRank, data.RankTimes, data.CreatedOn, data.UpdatedOn, data.PersonId)
	}, rudyGcAmCastIdKey, rudyGcAmCastNameKey)
	return ret, err
}

func (m *defaultAmCastModel) Update(ctx context.Context, newData *AmCast) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcAmCastIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmCastIdPrefix, data.Id)
	rudyGcAmCastNameKey := fmt.Sprintf("%s%v", cacheRudyGcAmCastNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, amCastRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.JavId, newData.MovieNumber, newData.OwnedMovieNumber, newData.OwnedWMediaNumber, newData.ScTimes, newData.ComeTimes, newData.LastScTime, newData.Rank500MovieNumber, newData.Rank20MovieNumber, newData.Rank1MovieNumber, newData.HighestRank, newData.RankTimes, newData.CreatedOn, newData.UpdatedOn, newData.PersonId, newData.Id)
	}, rudyGcAmCastIdKey, rudyGcAmCastNameKey)
	return err
}

func (m *defaultAmCastModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcAmCastIdPrefix, primary)
}

func (m *defaultAmCastModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amCastRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAmCastModel) tableName() string {
	return m.table
}
