// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bmMinfoFieldNames          = builder.RawFieldNames(&BmMinfo{})
	bmMinfoRows                = strings.Join(bmMinfoFieldNames, ",")
	bmMinfoRowsExpectAutoSet   = strings.Join(stringx.Remove(bmMinfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	bmMinfoRowsWithPlaceHolder = strings.Join(stringx.Remove(bmMinfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcBmMinfoIdPrefix    = "cache:rudyGc:bmMinfo:id:"
	cacheRudyGcBmMinfoJavIdPrefix = "cache:rudyGc:bmMinfo:javId:"
)

type (
	bmMinfoModel interface {
		Insert(ctx context.Context, data *BmMinfo) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BmMinfo, error)
		FindOneByJavId(ctx context.Context, javId string) (*BmMinfo, error)
		Update(ctx context.Context, data *BmMinfo) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBmMinfoModel struct {
		sqlc.CachedConn
		table string
	}

	BmMinfo struct {
		Id                 int64  `db:"id"`
		JavId              string `db:"jav_id"`
		Name               string `db:"name"`
		Chinese            string `db:"chinese"`
		FirstRankDayNumber int64  `db:"first_rank_day_number"`
		HighestRank        int64  `db:"highest_rank"`
		DaysInRank         int64  `db:"days_in_rank"`
		CreatedOn          int64  `db:"created_on"`
		UpdatedOn          int64  `db:"updated_on"`
		ReleasingDate      int64  `db:"releasing_date"`
	}
)

func newBmMinfoModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultBmMinfoModel {
	return &defaultBmMinfoModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`bm_minfo`",
	}
}

func (m *defaultBmMinfoModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcBmMinfoIdKey := fmt.Sprintf("%s%v", cacheRudyGcBmMinfoIdPrefix, id)
	rudyGcBmMinfoJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcBmMinfoJavIdPrefix, data.JavId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcBmMinfoIdKey, rudyGcBmMinfoJavIdKey)
	return err
}

func (m *defaultBmMinfoModel) FindOne(ctx context.Context, id int64) (*BmMinfo, error) {
	rudyGcBmMinfoIdKey := fmt.Sprintf("%s%v", cacheRudyGcBmMinfoIdPrefix, id)
	var resp BmMinfo
	err := m.QueryRowCtx(ctx, &resp, rudyGcBmMinfoIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bmMinfoRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmMinfoModel) FindOneByJavId(ctx context.Context, javId string) (*BmMinfo, error) {
	rudyGcBmMinfoJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcBmMinfoJavIdPrefix, javId)
	var resp BmMinfo
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcBmMinfoJavIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `jav_id` = ? limit 1", bmMinfoRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, javId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmMinfoModel) Insert(ctx context.Context, data *BmMinfo) (sql.Result, error) {
	rudyGcBmMinfoIdKey := fmt.Sprintf("%s%v", cacheRudyGcBmMinfoIdPrefix, data.Id)
	rudyGcBmMinfoJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcBmMinfoJavIdPrefix, data.JavId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, bmMinfoRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.JavId, data.Name, data.Chinese, data.FirstRankDayNumber, data.HighestRank, data.DaysInRank, data.CreatedOn, data.UpdatedOn, data.ReleasingDate)
	}, rudyGcBmMinfoIdKey, rudyGcBmMinfoJavIdKey)
	return ret, err
}

func (m *defaultBmMinfoModel) Update(ctx context.Context, newData *BmMinfo) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcBmMinfoIdKey := fmt.Sprintf("%s%v", cacheRudyGcBmMinfoIdPrefix, data.Id)
	rudyGcBmMinfoJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcBmMinfoJavIdPrefix, data.JavId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, bmMinfoRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.JavId, newData.Name, newData.Chinese, newData.FirstRankDayNumber, newData.HighestRank, newData.DaysInRank, newData.CreatedOn, newData.UpdatedOn, newData.ReleasingDate, newData.Id)
	}, rudyGcBmMinfoIdKey, rudyGcBmMinfoJavIdKey)
	return err
}

func (m *defaultBmMinfoModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcBmMinfoIdPrefix, primary)
}

func (m *defaultBmMinfoModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bmMinfoRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBmMinfoModel) tableName() string {
	return m.table
}
