// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	eRecordFieldNames          = builder.RawFieldNames(&ERecord{})
	eRecordRows                = strings.Join(eRecordFieldNames, ",")
	eRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(eRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	eRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(eRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcERecordIdPrefix   = "cache:rudyGc:eRecord:id:"
	cacheRudyGcERecordNamePrefix = "cache:rudyGc:eRecord:name:"
)

type (
	eRecordModel interface {
		Insert(ctx context.Context, data *ERecord) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ERecord, error)
		FindOneByName(ctx context.Context, name string) (*ERecord, error)
		Update(ctx context.Context, data *ERecord) error
		Delete(ctx context.Context, id int64) error
	}

	defaultERecordModel struct {
		sqlc.CachedConn
		table string
	}

	ERecord struct {
		Id           int64  `db:"id"`
		Name         string `db:"name"`
		StartTime    int64  `db:"start_time"`
		EndTime      int64  `db:"end_time"`
		Type         string `db:"type"`
		DetailNumber int64  `db:"detail_number"`
		CreatedOn    int64  `db:"created_on"`
		UpdatedOn    int64  `db:"updated_on"`
	}
)

func newERecordModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultERecordModel {
	return &defaultERecordModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`e_record`",
	}
}

func (m *defaultERecordModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcERecordIdKey := fmt.Sprintf("%s%v", cacheRudyGcERecordIdPrefix, id)
	rudyGcERecordNameKey := fmt.Sprintf("%s%v", cacheRudyGcERecordNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcERecordIdKey, rudyGcERecordNameKey)
	return err
}

func (m *defaultERecordModel) FindOne(ctx context.Context, id int64) (*ERecord, error) {
	rudyGcERecordIdKey := fmt.Sprintf("%s%v", cacheRudyGcERecordIdPrefix, id)
	var resp ERecord
	err := m.QueryRowCtx(ctx, &resp, rudyGcERecordIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", eRecordRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultERecordModel) FindOneByName(ctx context.Context, name string) (*ERecord, error) {
	rudyGcERecordNameKey := fmt.Sprintf("%s%v", cacheRudyGcERecordNamePrefix, name)
	var resp ERecord
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcERecordNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", eRecordRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultERecordModel) Insert(ctx context.Context, data *ERecord) (sql.Result, error) {
	rudyGcERecordIdKey := fmt.Sprintf("%s%v", cacheRudyGcERecordIdPrefix, data.Id)
	rudyGcERecordNameKey := fmt.Sprintf("%s%v", cacheRudyGcERecordNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, eRecordRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.StartTime, data.EndTime, data.Type, data.DetailNumber, data.CreatedOn, data.UpdatedOn)
	}, rudyGcERecordIdKey, rudyGcERecordNameKey)
	return ret, err
}

func (m *defaultERecordModel) Update(ctx context.Context, newData *ERecord) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcERecordIdKey := fmt.Sprintf("%s%v", cacheRudyGcERecordIdPrefix, data.Id)
	rudyGcERecordNameKey := fmt.Sprintf("%s%v", cacheRudyGcERecordNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, eRecordRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.StartTime, newData.EndTime, newData.Type, newData.DetailNumber, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcERecordIdKey, rudyGcERecordNameKey)
	return err
}

func (m *defaultERecordModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcERecordIdPrefix, primary)
}

func (m *defaultERecordModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", eRecordRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultERecordModel) tableName() string {
	return m.table
}
