// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	movieReleaseAggDirtyFieldNames          = builder.RawFieldNames(&MovieReleaseAggDirty{})
	movieReleaseAggDirtyRows                = strings.Join(movieReleaseAggDirtyFieldNames, ",")
	movieReleaseAggDirtyRowsExpectAutoSet   = strings.Join(stringx.Remove(movieReleaseAggDirtyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	movieReleaseAggDirtyRowsWithPlaceHolder = strings.Join(stringx.Remove(movieReleaseAggDirtyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcMovieReleaseAggDirtyIdPrefix          = "cache:rudyGc:movieReleaseAggDirty:id:"
	cacheRudyGcMovieReleaseAggDirtyBucketMonthPrefix = "cache:rudyGc:movieReleaseAggDirty:bucketMonth:"
)

type (
	movieReleaseAggDirtyModel interface {
		Insert(ctx context.Context, data *MovieReleaseAggDirty) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MovieReleaseAggDirty, error)
		FindOneByBucketMonth(ctx context.Context, bucketMonth int64) (*MovieReleaseAggDirty, error)
		Update(ctx context.Context, data *MovieReleaseAggDirty) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMovieReleaseAggDirtyModel struct {
		sqlc.CachedConn
		table string
	}

	MovieReleaseAggDirty struct {
		Id          int64  `db:"id"`
		BucketMonth int64  `db:"bucket_month"`
		ScopeKey    string `db:"scope_key"`
		CreatedOn   int64  `db:"created_on"`
		UpdatedOn   int64  `db:"updated_on"`
	}
)

func newMovieReleaseAggDirtyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMovieReleaseAggDirtyModel {
	return &defaultMovieReleaseAggDirtyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`movie_release_agg_dirty`",
	}
}

func (m *defaultMovieReleaseAggDirtyModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcMovieReleaseAggDirtyBucketMonthKey := fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseAggDirtyBucketMonthPrefix, data.BucketMonth)
	rudyGcMovieReleaseAggDirtyIdKey := fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseAggDirtyIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcMovieReleaseAggDirtyBucketMonthKey, rudyGcMovieReleaseAggDirtyIdKey)
	return err
}

func (m *defaultMovieReleaseAggDirtyModel) FindOne(ctx context.Context, id int64) (*MovieReleaseAggDirty, error) {
	rudyGcMovieReleaseAggDirtyIdKey := fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseAggDirtyIdPrefix, id)
	var resp MovieReleaseAggDirty
	err := m.QueryRowCtx(ctx, &resp, rudyGcMovieReleaseAggDirtyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", movieReleaseAggDirtyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMovieReleaseAggDirtyModel) FindOneByBucketMonth(ctx context.Context, bucketMonth int64) (*MovieReleaseAggDirty, error) {
	rudyGcMovieReleaseAggDirtyBucketMonthKey := fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseAggDirtyBucketMonthPrefix, bucketMonth)
	var resp MovieReleaseAggDirty
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcMovieReleaseAggDirtyBucketMonthKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `bucket_month` = ? limit 1", movieReleaseAggDirtyRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, bucketMonth); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMovieReleaseAggDirtyModel) Insert(ctx context.Context, data *MovieReleaseAggDirty) (sql.Result, error) {
	rudyGcMovieReleaseAggDirtyBucketMonthKey := fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseAggDirtyBucketMonthPrefix, data.BucketMonth)
	rudyGcMovieReleaseAggDirtyIdKey := fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseAggDirtyIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, movieReleaseAggDirtyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.BucketMonth, data.ScopeKey, data.CreatedOn, data.UpdatedOn)
	}, rudyGcMovieReleaseAggDirtyBucketMonthKey, rudyGcMovieReleaseAggDirtyIdKey)
	return ret, err
}

func (m *defaultMovieReleaseAggDirtyModel) Update(ctx context.Context, newData *MovieReleaseAggDirty) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcMovieReleaseAggDirtyBucketMonthKey := fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseAggDirtyBucketMonthPrefix, data.BucketMonth)
	rudyGcMovieReleaseAggDirtyIdKey := fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseAggDirtyIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, movieReleaseAggDirtyRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.BucketMonth, newData.ScopeKey, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcMovieReleaseAggDirtyBucketMonthKey, rudyGcMovieReleaseAggDirtyIdKey)
	return err
}

func (m *defaultMovieReleaseAggDirtyModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseAggDirtyIdPrefix, primary)
}

func (m *defaultMovieReleaseAggDirtyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", movieReleaseAggDirtyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMovieReleaseAggDirtyModel) tableName() string {
	return m.table
}
