// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	movieReleaseBucketStatFieldNames          = builder.RawFieldNames(&MovieReleaseBucketStat{})
	movieReleaseBucketStatRows                = strings.Join(movieReleaseBucketStatFieldNames, ",")
	movieReleaseBucketStatRowsExpectAutoSet   = strings.Join(stringx.Remove(movieReleaseBucketStatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	movieReleaseBucketStatRowsWithPlaceHolder = strings.Join(stringx.Remove(movieReleaseBucketStatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcMovieReleaseBucketStatIdPrefix       = "cache:rudyGc:movieReleaseBucketStat:id:"
	cacheRudyGcMovieReleaseBucketStatScopeKeyPrefix = "cache:rudyGc:movieReleaseBucketStat:scopeKey:"
)

type (
	movieReleaseBucketStatModel interface {
		Insert(ctx context.Context, data *MovieReleaseBucketStat) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MovieReleaseBucketStat, error)
		FindOneByScopeKey(ctx context.Context, scopeKey string) (*MovieReleaseBucketStat, error)
		Update(ctx context.Context, data *MovieReleaseBucketStat) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMovieReleaseBucketStatModel struct {
		sqlc.CachedConn
		table string
	}

	MovieReleaseBucketStat struct {
		Id                  int64  `db:"id"`
		ScopeKey            string `db:"scope_key"`
		Level               string `db:"level"`
		Year                int64  `db:"year"`
		Quarter             int64  `db:"quarter"`
		Month               int64  `db:"month"`
		Day                 int64  `db:"day"`
		CountAll            int64  `db:"count_all"`
		CountOwned          int64  `db:"count_owned"`
		SizeBytes           int64  `db:"size_bytes"`
		LatestReleasingDate int64  `db:"latest_releasing_date"`
		CreatedOn           int64  `db:"created_on"`
		UpdatedOn           int64  `db:"updated_on"`
	}
)

func newMovieReleaseBucketStatModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMovieReleaseBucketStatModel {
	return &defaultMovieReleaseBucketStatModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`movie_release_bucket_stat`",
	}
}

func (m *defaultMovieReleaseBucketStatModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcMovieReleaseBucketStatIdKey := fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseBucketStatIdPrefix, id)
	rudyGcMovieReleaseBucketStatScopeKeyKey := fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseBucketStatScopeKeyPrefix, data.ScopeKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcMovieReleaseBucketStatIdKey, rudyGcMovieReleaseBucketStatScopeKeyKey)
	return err
}

func (m *defaultMovieReleaseBucketStatModel) FindOne(ctx context.Context, id int64) (*MovieReleaseBucketStat, error) {
	rudyGcMovieReleaseBucketStatIdKey := fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseBucketStatIdPrefix, id)
	var resp MovieReleaseBucketStat
	err := m.QueryRowCtx(ctx, &resp, rudyGcMovieReleaseBucketStatIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", movieReleaseBucketStatRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMovieReleaseBucketStatModel) FindOneByScopeKey(ctx context.Context, scopeKey string) (*MovieReleaseBucketStat, error) {
	rudyGcMovieReleaseBucketStatScopeKeyKey := fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseBucketStatScopeKeyPrefix, scopeKey)
	var resp MovieReleaseBucketStat
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcMovieReleaseBucketStatScopeKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `scope_key` = ? limit 1", movieReleaseBucketStatRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, scopeKey); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMovieReleaseBucketStatModel) Insert(ctx context.Context, data *MovieReleaseBucketStat) (sql.Result, error) {
	rudyGcMovieReleaseBucketStatIdKey := fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseBucketStatIdPrefix, data.Id)
	rudyGcMovieReleaseBucketStatScopeKeyKey := fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseBucketStatScopeKeyPrefix, data.ScopeKey)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, movieReleaseBucketStatRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ScopeKey, data.Level, data.Year, data.Quarter, data.Month, data.Day, data.CountAll, data.CountOwned, data.SizeBytes, data.LatestReleasingDate, data.CreatedOn, data.UpdatedOn)
	}, rudyGcMovieReleaseBucketStatIdKey, rudyGcMovieReleaseBucketStatScopeKeyKey)
	return ret, err
}

func (m *defaultMovieReleaseBucketStatModel) Update(ctx context.Context, newData *MovieReleaseBucketStat) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcMovieReleaseBucketStatIdKey := fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseBucketStatIdPrefix, data.Id)
	rudyGcMovieReleaseBucketStatScopeKeyKey := fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseBucketStatScopeKeyPrefix, data.ScopeKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, movieReleaseBucketStatRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ScopeKey, newData.Level, newData.Year, newData.Quarter, newData.Month, newData.Day, newData.CountAll, newData.CountOwned, newData.SizeBytes, newData.LatestReleasingDate, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcMovieReleaseBucketStatIdKey, rudyGcMovieReleaseBucketStatScopeKeyKey)
	return err
}

func (m *defaultMovieReleaseBucketStatModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseBucketStatIdPrefix, primary)
}

func (m *defaultMovieReleaseBucketStatModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", movieReleaseBucketStatRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMovieReleaseBucketStatModel) tableName() string {
	return m.table
}
