// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tJavbusMagnetFieldNames          = builder.RawFieldNames(&TJavbusMagnet{})
	tJavbusMagnetRows                = strings.Join(tJavbusMagnetFieldNames, ",")
	tJavbusMagnetRowsExpectAutoSet   = strings.Join(stringx.Remove(tJavbusMagnetFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tJavbusMagnetRowsWithPlaceHolder = strings.Join(stringx.Remove(tJavbusMagnetFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcTJavbusMagnetIdPrefix                 = "cache:rudyGc:tJavbusMagnet:id:"
	cacheRudyGcTJavbusMagnetMovieJavIdInfoHashPrefix = "cache:rudyGc:tJavbusMagnet:movieJavId:infoHash:"
)

type (
	tJavbusMagnetModel interface {
		Insert(ctx context.Context, data *TJavbusMagnet) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TJavbusMagnet, error)
		FindOneByMovieJavIdInfoHash(ctx context.Context, movieJavId string, infoHash string) (*TJavbusMagnet, error)
		Update(ctx context.Context, data *TJavbusMagnet) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTJavbusMagnetModel struct {
		sqlc.CachedConn
		table string
	}

	TJavbusMagnet struct {
		Id           int64  `db:"id"`
		MovieJavId   string `db:"movie_jav_id"`
		PageUrl      string `db:"page_url"`
		MagnetName   string `db:"magnet_name"`
		MagnetUrl    string `db:"magnet_url"`
		InfoHash     string `db:"info_hash"`
		Dn           string `db:"dn"`
		SizeBytes    int64  `db:"size_bytes"`
		SizeText     string `db:"size_text"`
		ShareDate    int64  `db:"share_date"`
		HasHd        int64  `db:"has_hd"`
		HasSubtitle  int64  `db:"has_subtitle"`
		RowSort      int64  `db:"row_sort"`
		LastSeenTime int64  `db:"last_seen_time"`
		CreatedOn    int64  `db:"created_on"`
		UpdatedOn    int64  `db:"updated_on"`
	}
)

func newTJavbusMagnetModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTJavbusMagnetModel {
	return &defaultTJavbusMagnetModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_javbus_magnet`",
	}
}

func (m *defaultTJavbusMagnetModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcTJavbusMagnetIdKey := fmt.Sprintf("%s%v", cacheRudyGcTJavbusMagnetIdPrefix, id)
	rudyGcTJavbusMagnetMovieJavIdInfoHashKey := fmt.Sprintf("%s%v:%v", cacheRudyGcTJavbusMagnetMovieJavIdInfoHashPrefix, data.MovieJavId, data.InfoHash)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcTJavbusMagnetIdKey, rudyGcTJavbusMagnetMovieJavIdInfoHashKey)
	return err
}

func (m *defaultTJavbusMagnetModel) FindOne(ctx context.Context, id int64) (*TJavbusMagnet, error) {
	rudyGcTJavbusMagnetIdKey := fmt.Sprintf("%s%v", cacheRudyGcTJavbusMagnetIdPrefix, id)
	var resp TJavbusMagnet
	err := m.QueryRowCtx(ctx, &resp, rudyGcTJavbusMagnetIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tJavbusMagnetRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTJavbusMagnetModel) FindOneByMovieJavIdInfoHash(ctx context.Context, movieJavId string, infoHash string) (*TJavbusMagnet, error) {
	rudyGcTJavbusMagnetMovieJavIdInfoHashKey := fmt.Sprintf("%s%v:%v", cacheRudyGcTJavbusMagnetMovieJavIdInfoHashPrefix, movieJavId, infoHash)
	var resp TJavbusMagnet
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcTJavbusMagnetMovieJavIdInfoHashKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `movie_jav_id` = ? and `info_hash` = ? limit 1", tJavbusMagnetRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, movieJavId, infoHash); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTJavbusMagnetModel) Insert(ctx context.Context, data *TJavbusMagnet) (sql.Result, error) {
	rudyGcTJavbusMagnetIdKey := fmt.Sprintf("%s%v", cacheRudyGcTJavbusMagnetIdPrefix, data.Id)
	rudyGcTJavbusMagnetMovieJavIdInfoHashKey := fmt.Sprintf("%s%v:%v", cacheRudyGcTJavbusMagnetMovieJavIdInfoHashPrefix, data.MovieJavId, data.InfoHash)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tJavbusMagnetRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MovieJavId, data.PageUrl, data.MagnetName, data.MagnetUrl, data.InfoHash, data.Dn, data.SizeBytes, data.SizeText, data.ShareDate, data.HasHd, data.HasSubtitle, data.RowSort, data.LastSeenTime, data.CreatedOn, data.UpdatedOn)
	}, rudyGcTJavbusMagnetIdKey, rudyGcTJavbusMagnetMovieJavIdInfoHashKey)
	return ret, err
}

func (m *defaultTJavbusMagnetModel) Update(ctx context.Context, newData *TJavbusMagnet) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcTJavbusMagnetIdKey := fmt.Sprintf("%s%v", cacheRudyGcTJavbusMagnetIdPrefix, data.Id)
	rudyGcTJavbusMagnetMovieJavIdInfoHashKey := fmt.Sprintf("%s%v:%v", cacheRudyGcTJavbusMagnetMovieJavIdInfoHashPrefix, data.MovieJavId, data.InfoHash)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tJavbusMagnetRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MovieJavId, newData.PageUrl, newData.MagnetName, newData.MagnetUrl, newData.InfoHash, newData.Dn, newData.SizeBytes, newData.SizeText, newData.ShareDate, newData.HasHd, newData.HasSubtitle, newData.RowSort, newData.LastSeenTime, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcTJavbusMagnetIdKey, rudyGcTJavbusMagnetMovieJavIdInfoHashKey)
	return err
}

func (m *defaultTJavbusMagnetModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcTJavbusMagnetIdPrefix, primary)
}

func (m *defaultTJavbusMagnetModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tJavbusMagnetRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTJavbusMagnetModel) tableName() string {
	return m.table
}
