// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tSehuatangMagnetFieldNames          = builder.RawFieldNames(&TSehuatangMagnet{})
	tSehuatangMagnetRows                = strings.Join(tSehuatangMagnetFieldNames, ",")
	tSehuatangMagnetRowsExpectAutoSet   = strings.Join(stringx.Remove(tSehuatangMagnetFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tSehuatangMagnetRowsWithPlaceHolder = strings.Join(stringx.Remove(tSehuatangMagnetFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcTSehuatangMagnetIdPrefix       = "cache:rudyGc:tSehuatangMagnet:id:"
	cacheRudyGcTSehuatangMagnetInfoHashPrefix = "cache:rudyGc:tSehuatangMagnet:infoHash:"
)

type (
	tSehuatangMagnetModel interface {
		Insert(ctx context.Context, data *TSehuatangMagnet) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TSehuatangMagnet, error)
		FindOneByInfoHash(ctx context.Context, infoHash string) (*TSehuatangMagnet, error)
		Update(ctx context.Context, data *TSehuatangMagnet) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTSehuatangMagnetModel struct {
		sqlc.CachedConn
		table string
	}

	TSehuatangMagnet struct {
		Id           int64  `db:"id"`
		MovieJavId   string `db:"movie_jav_id"`
		MovieName    string `db:"movie_name"`
		Tag          string `db:"tag"`
		ThreadTitle  string `db:"thread_title"`
		ThreadUrl    string `db:"thread_url"`
		PostTime     int64  `db:"post_time"`
		PostDate     int64  `db:"post_date"`
		InfoHash     string `db:"info_hash"`
		LastSeenTime int64  `db:"last_seen_time"`
		CreatedOn    int64  `db:"created_on"`
		UpdatedOn    int64  `db:"updated_on"`
	}
)

func newTSehuatangMagnetModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTSehuatangMagnetModel {
	return &defaultTSehuatangMagnetModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_sehuatang_magnet`",
	}
}

func (m *defaultTSehuatangMagnetModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcTSehuatangMagnetIdKey := fmt.Sprintf("%s%v", cacheRudyGcTSehuatangMagnetIdPrefix, id)
	rudyGcTSehuatangMagnetInfoHashKey := fmt.Sprintf("%s%v", cacheRudyGcTSehuatangMagnetInfoHashPrefix, data.InfoHash)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcTSehuatangMagnetIdKey, rudyGcTSehuatangMagnetInfoHashKey)
	return err
}

func (m *defaultTSehuatangMagnetModel) FindOne(ctx context.Context, id int64) (*TSehuatangMagnet, error) {
	rudyGcTSehuatangMagnetIdKey := fmt.Sprintf("%s%v", cacheRudyGcTSehuatangMagnetIdPrefix, id)
	var resp TSehuatangMagnet
	err := m.QueryRowCtx(ctx, &resp, rudyGcTSehuatangMagnetIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tSehuatangMagnetRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTSehuatangMagnetModel) FindOneByInfoHash(ctx context.Context, infoHash string) (*TSehuatangMagnet, error) {
	rudyGcTSehuatangMagnetInfoHashKey := fmt.Sprintf("%s%v", cacheRudyGcTSehuatangMagnetInfoHashPrefix, infoHash)
	var resp TSehuatangMagnet
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcTSehuatangMagnetInfoHashKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `info_hash` = ? limit 1", tSehuatangMagnetRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, infoHash); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTSehuatangMagnetModel) Insert(ctx context.Context, data *TSehuatangMagnet) (sql.Result, error) {
	rudyGcTSehuatangMagnetIdKey := fmt.Sprintf("%s%v", cacheRudyGcTSehuatangMagnetIdPrefix, data.Id)
	rudyGcTSehuatangMagnetInfoHashKey := fmt.Sprintf("%s%v", cacheRudyGcTSehuatangMagnetInfoHashPrefix, data.InfoHash)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tSehuatangMagnetRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MovieJavId, data.MovieName, data.Tag, data.ThreadTitle, data.ThreadUrl, data.PostTime, data.PostDate, data.InfoHash, data.LastSeenTime, data.CreatedOn, data.UpdatedOn)
	}, rudyGcTSehuatangMagnetIdKey, rudyGcTSehuatangMagnetInfoHashKey)
	return ret, err
}

func (m *defaultTSehuatangMagnetModel) Update(ctx context.Context, newData *TSehuatangMagnet) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcTSehuatangMagnetIdKey := fmt.Sprintf("%s%v", cacheRudyGcTSehuatangMagnetIdPrefix, data.Id)
	rudyGcTSehuatangMagnetOldInfoHashKey := fmt.Sprintf("%s%v", cacheRudyGcTSehuatangMagnetInfoHashPrefix, data.InfoHash)
	rudyGcTSehuatangMagnetNewInfoHashKey := fmt.Sprintf("%s%v", cacheRudyGcTSehuatangMagnetInfoHashPrefix, newData.InfoHash)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tSehuatangMagnetRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MovieJavId, newData.MovieName, newData.Tag, newData.ThreadTitle, newData.ThreadUrl, newData.PostTime, newData.PostDate, newData.InfoHash, newData.LastSeenTime, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcTSehuatangMagnetIdKey, rudyGcTSehuatangMagnetOldInfoHashKey, rudyGcTSehuatangMagnetNewInfoHashKey)
	return err
}

func (m *defaultTSehuatangMagnetModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcTSehuatangMagnetIdPrefix, primary)
}

func (m *defaultTSehuatangMagnetModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tSehuatangMagnetRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTSehuatangMagnetModel) tableName() string {
	return m.table
}
