// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tmAlbumItemFieldNames          = builder.RawFieldNames(&TmAlbumItem{})
	tmAlbumItemRows                = strings.Join(tmAlbumItemFieldNames, ",")
	tmAlbumItemRowsExpectAutoSet   = strings.Join(stringx.Remove(tmAlbumItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tmAlbumItemRowsWithPlaceHolder = strings.Join(stringx.Remove(tmAlbumItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcTmAlbumItemIdPrefix                           = "cache:rudyGc:tmAlbumItem:id:"
	cacheRudyGcTmAlbumItemAlbumIdSourceTypeSourceRowIdPrefix = "cache:rudyGc:tmAlbumItem:albumId:sourceType:sourceRowId:"
)

type (
	tmAlbumItemModel interface {
		Insert(ctx context.Context, data *TmAlbumItem) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TmAlbumItem, error)
		FindOneByAlbumIdSourceTypeSourceRowId(ctx context.Context, albumId int64, sourceType string, sourceRowId int64) (*TmAlbumItem, error)
		Update(ctx context.Context, data *TmAlbumItem) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTmAlbumItemModel struct {
		sqlc.CachedConn
		table string
	}

	TmAlbumItem struct {
		Id          int64  `db:"id"`
		AlbumId     int64  `db:"album_id"`
		SourceType  string `db:"source_type"`
		SourceRowId int64  `db:"source_row_id"`
		MovieJavId  string `db:"movie_jav_id"`
		InfoHash    string `db:"info_hash"`
		CreatedOn   int64  `db:"created_on"`
		UpdatedOn   int64  `db:"updated_on"`
		MovieName   string `db:"movie_name"`
		Size        string `db:"size"`
		PublishTime int64  `db:"publish_time"`
	}
)

func newTmAlbumItemModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTmAlbumItemModel {
	return &defaultTmAlbumItemModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`tm_album_item`",
	}
}

func (m *defaultTmAlbumItemModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcTmAlbumItemAlbumIdSourceTypeSourceRowIdKey := fmt.Sprintf("%s%v:%v:%v", cacheRudyGcTmAlbumItemAlbumIdSourceTypeSourceRowIdPrefix, data.AlbumId, data.SourceType, data.SourceRowId)
	rudyGcTmAlbumItemIdKey := fmt.Sprintf("%s%v", cacheRudyGcTmAlbumItemIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcTmAlbumItemAlbumIdSourceTypeSourceRowIdKey, rudyGcTmAlbumItemIdKey)
	return err
}

func (m *defaultTmAlbumItemModel) FindOne(ctx context.Context, id int64) (*TmAlbumItem, error) {
	rudyGcTmAlbumItemIdKey := fmt.Sprintf("%s%v", cacheRudyGcTmAlbumItemIdPrefix, id)
	var resp TmAlbumItem
	err := m.QueryRowCtx(ctx, &resp, rudyGcTmAlbumItemIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tmAlbumItemRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTmAlbumItemModel) FindOneByAlbumIdSourceTypeSourceRowId(ctx context.Context, albumId int64, sourceType string, sourceRowId int64) (*TmAlbumItem, error) {
	rudyGcTmAlbumItemAlbumIdSourceTypeSourceRowIdKey := fmt.Sprintf("%s%v:%v:%v", cacheRudyGcTmAlbumItemAlbumIdSourceTypeSourceRowIdPrefix, albumId, sourceType, sourceRowId)
	var resp TmAlbumItem
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcTmAlbumItemAlbumIdSourceTypeSourceRowIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `album_id` = ? and `source_type` = ? and `source_row_id` = ? limit 1", tmAlbumItemRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, albumId, sourceType, sourceRowId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTmAlbumItemModel) Insert(ctx context.Context, data *TmAlbumItem) (sql.Result, error) {
	rudyGcTmAlbumItemAlbumIdSourceTypeSourceRowIdKey := fmt.Sprintf("%s%v:%v:%v", cacheRudyGcTmAlbumItemAlbumIdSourceTypeSourceRowIdPrefix, data.AlbumId, data.SourceType, data.SourceRowId)
	rudyGcTmAlbumItemIdKey := fmt.Sprintf("%s%v", cacheRudyGcTmAlbumItemIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tmAlbumItemRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.AlbumId, data.SourceType, data.SourceRowId, data.MovieJavId, data.InfoHash, data.CreatedOn, data.UpdatedOn, data.MovieName, data.Size, data.PublishTime)
	}, rudyGcTmAlbumItemAlbumIdSourceTypeSourceRowIdKey, rudyGcTmAlbumItemIdKey)
	return ret, err
}

func (m *defaultTmAlbumItemModel) Update(ctx context.Context, newData *TmAlbumItem) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcTmAlbumItemAlbumIdSourceTypeSourceRowIdKey := fmt.Sprintf("%s%v:%v:%v", cacheRudyGcTmAlbumItemAlbumIdSourceTypeSourceRowIdPrefix, data.AlbumId, data.SourceType, data.SourceRowId)
	rudyGcTmAlbumItemIdKey := fmt.Sprintf("%s%v", cacheRudyGcTmAlbumItemIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tmAlbumItemRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.AlbumId, newData.SourceType, newData.SourceRowId, newData.MovieJavId, newData.InfoHash, newData.CreatedOn, newData.UpdatedOn, newData.MovieName, newData.Size, newData.PublishTime, newData.Id)
	}, rudyGcTmAlbumItemAlbumIdSourceTypeSourceRowIdKey, rudyGcTmAlbumItemIdKey)
	return err
}

func (m *defaultTmAlbumItemModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcTmAlbumItemIdPrefix, primary)
}

func (m *defaultTmAlbumItemModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tmAlbumItemRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTmAlbumItemModel) tableName() string {
	return m.table
}
