// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	wMediaFieldNames          = builder.RawFieldNames(&WMedia{})
	wMediaRows                = strings.Join(wMediaFieldNames, ",")
	wMediaRowsExpectAutoSet   = strings.Join(stringx.Remove(wMediaFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	wMediaRowsWithPlaceHolder = strings.Join(stringx.Remove(wMediaFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcWMediaIdPrefix         = "cache:rudyGc:wMedia:id:"
	cacheRudyGcWMediaFileNamePrefix   = "cache:rudyGc:wMedia:fileName:"
	cacheRudyGcWMediaMovieJavIdPrefix = "cache:rudyGc:wMedia:movieJavId:"
	cacheRudyGcWMediaMovieNamePrefix  = "cache:rudyGc:wMedia:movieName:"
)

type (
	wMediaModel interface {
		Insert(ctx context.Context, data *WMedia) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*WMedia, error)
		FindOneByFileName(ctx context.Context, fileName string) (*WMedia, error)
		FindOneByMovieJavId(ctx context.Context, movieJavId string) (*WMedia, error)
		FindOneByMovieName(ctx context.Context, movieName string) (*WMedia, error)
		Update(ctx context.Context, data *WMedia) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWMediaModel struct {
		sqlc.CachedConn
		table string
	}

	WMedia struct {
		Id                int64   `db:"id"`
		MovieJavId        string  `db:"movie_jav_id"`
		MovieName         string  `db:"movie_name"`
		FileName          string  `db:"file_name"`
		SourceTorrentHash string  `db:"source_torrent_hash"`
		DirectoryId       int64   `db:"directory_id"`
		RootDir           string  `db:"root_dir"`
		FullDir           string  `db:"full_dir"`
		Alias             string  `db:"alias"`
		Size              int64   `db:"size"`
		Width             int64   `db:"width"`
		Height            int64   `db:"height"`
		BitRate           int64   `db:"bit_rate"`
		Duration          int64   `db:"duration"`
		FrameAverage      float64 `db:"frame_average"`
		HasSub            int64   `db:"has_sub"`
		SelfMake          int64   `db:"self_make"`
		HasMask           int64   `db:"has_mask"`
		NeedScanMeta      int64   `db:"need_scan_meta"`
		IsRemoved         int64   `db:"is_removed"`
		RemoveTime        int64   `db:"remove_time"`
		BirthTime         int64   `db:"birth_time"`
		ReleasingDate     int64   `db:"releasing_date"`
		CreatedOn         int64   `db:"created_on"`
		UpdatedOn         int64   `db:"updated_on"`
	}
)

func newWMediaModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultWMediaModel {
	return &defaultWMediaModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`w_media`",
	}
}

func (m *defaultWMediaModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcWMediaFileNameKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaFileNamePrefix, data.FileName)
	rudyGcWMediaIdKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaIdPrefix, id)
	rudyGcWMediaMovieJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaMovieJavIdPrefix, data.MovieJavId)
	rudyGcWMediaMovieNameKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaMovieNamePrefix, data.MovieName)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcWMediaFileNameKey, rudyGcWMediaIdKey, rudyGcWMediaMovieJavIdKey, rudyGcWMediaMovieNameKey)
	return err
}

func (m *defaultWMediaModel) FindOne(ctx context.Context, id int64) (*WMedia, error) {
	rudyGcWMediaIdKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaIdPrefix, id)
	var resp WMedia
	err := m.QueryRowCtx(ctx, &resp, rudyGcWMediaIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", wMediaRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWMediaModel) FindOneByFileName(ctx context.Context, fileName string) (*WMedia, error) {
	rudyGcWMediaFileNameKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaFileNamePrefix, fileName)
	var resp WMedia
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcWMediaFileNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `file_name` = ? limit 1", wMediaRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, fileName); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWMediaModel) FindOneByMovieJavId(ctx context.Context, movieJavId string) (*WMedia, error) {
	rudyGcWMediaMovieJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaMovieJavIdPrefix, movieJavId)
	var resp WMedia
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcWMediaMovieJavIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `movie_jav_id` = ? limit 1", wMediaRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, movieJavId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWMediaModel) FindOneByMovieName(ctx context.Context, movieName string) (*WMedia, error) {
	rudyGcWMediaMovieNameKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaMovieNamePrefix, movieName)
	var resp WMedia
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcWMediaMovieNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `movie_name` = ? limit 1", wMediaRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, movieName); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWMediaModel) Insert(ctx context.Context, data *WMedia) (sql.Result, error) {
	rudyGcWMediaFileNameKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaFileNamePrefix, data.FileName)
	rudyGcWMediaIdKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaIdPrefix, data.Id)
	rudyGcWMediaMovieJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaMovieJavIdPrefix, data.MovieJavId)
	rudyGcWMediaMovieNameKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaMovieNamePrefix, data.MovieName)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, wMediaRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MovieJavId, data.MovieName, data.FileName, data.SourceTorrentHash, data.DirectoryId, data.RootDir, data.FullDir, data.Alias, data.Size, data.Width, data.Height, data.BitRate, data.Duration, data.FrameAverage, data.HasSub, data.SelfMake, data.HasMask, data.NeedScanMeta, data.IsRemoved, data.RemoveTime, data.BirthTime, data.ReleasingDate, data.CreatedOn, data.UpdatedOn)
	}, rudyGcWMediaFileNameKey, rudyGcWMediaIdKey, rudyGcWMediaMovieJavIdKey, rudyGcWMediaMovieNameKey)
	return ret, err
}

func (m *defaultWMediaModel) Update(ctx context.Context, newData *WMedia) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcWMediaFileNameKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaFileNamePrefix, data.FileName)
	rudyGcWMediaIdKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaIdPrefix, data.Id)
	rudyGcWMediaMovieJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaMovieJavIdPrefix, data.MovieJavId)
	rudyGcWMediaMovieNameKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaMovieNamePrefix, data.MovieName)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, wMediaRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MovieJavId, newData.MovieName, newData.FileName, newData.SourceTorrentHash, newData.DirectoryId, newData.RootDir, newData.FullDir, newData.Alias, newData.Size, newData.Width, newData.Height, newData.BitRate, newData.Duration, newData.FrameAverage, newData.HasSub, newData.SelfMake, newData.HasMask, newData.NeedScanMeta, newData.IsRemoved, newData.RemoveTime, newData.BirthTime, newData.ReleasingDate, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcWMediaFileNameKey, rudyGcWMediaIdKey, rudyGcWMediaMovieJavIdKey, rudyGcWMediaMovieNameKey)
	return err
}

func (m *defaultWMediaModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcWMediaIdPrefix, primary)
}

func (m *defaultWMediaModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", wMediaRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultWMediaModel) tableName() string {
	return m.table
}
