// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	wMediaAggDirtyFieldNames          = builder.RawFieldNames(&WMediaAggDirty{})
	wMediaAggDirtyRows                = strings.Join(wMediaAggDirtyFieldNames, ",")
	wMediaAggDirtyRowsExpectAutoSet   = strings.Join(stringx.Remove(wMediaAggDirtyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	wMediaAggDirtyRowsWithPlaceHolder = strings.Join(stringx.Remove(wMediaAggDirtyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcWMediaAggDirtyIdPrefix        = "cache:rudyGc:wMediaAggDirty:id:"
	cacheRudyGcWMediaAggDirtyBucketDayPrefix = "cache:rudyGc:wMediaAggDirty:bucketDay:"
)

type (
	wMediaAggDirtyModel interface {
		Insert(ctx context.Context, data *WMediaAggDirty) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*WMediaAggDirty, error)
		FindOneByBucketDay(ctx context.Context, bucketDay int64) (*WMediaAggDirty, error)
		Update(ctx context.Context, data *WMediaAggDirty) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWMediaAggDirtyModel struct {
		sqlc.CachedConn
		table string
	}

	WMediaAggDirty struct {
		Id        int64  `db:"id"`
		BucketDay int64  `db:"bucket_day"`
		ScopeKey  string `db:"scope_key"`
		CreatedOn int64  `db:"created_on"`
		UpdatedOn int64  `db:"updated_on"`
	}
)

func newWMediaAggDirtyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultWMediaAggDirtyModel {
	return &defaultWMediaAggDirtyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`w_media_agg_dirty`",
	}
}

func (m *defaultWMediaAggDirtyModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcWMediaAggDirtyBucketDayKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaAggDirtyBucketDayPrefix, data.BucketDay)
	rudyGcWMediaAggDirtyIdKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaAggDirtyIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcWMediaAggDirtyBucketDayKey, rudyGcWMediaAggDirtyIdKey)
	return err
}

func (m *defaultWMediaAggDirtyModel) FindOne(ctx context.Context, id int64) (*WMediaAggDirty, error) {
	rudyGcWMediaAggDirtyIdKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaAggDirtyIdPrefix, id)
	var resp WMediaAggDirty
	err := m.QueryRowCtx(ctx, &resp, rudyGcWMediaAggDirtyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", wMediaAggDirtyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWMediaAggDirtyModel) FindOneByBucketDay(ctx context.Context, bucketDay int64) (*WMediaAggDirty, error) {
	rudyGcWMediaAggDirtyBucketDayKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaAggDirtyBucketDayPrefix, bucketDay)
	var resp WMediaAggDirty
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcWMediaAggDirtyBucketDayKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `bucket_day` = ? limit 1", wMediaAggDirtyRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, bucketDay); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWMediaAggDirtyModel) Insert(ctx context.Context, data *WMediaAggDirty) (sql.Result, error) {
	rudyGcWMediaAggDirtyBucketDayKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaAggDirtyBucketDayPrefix, data.BucketDay)
	rudyGcWMediaAggDirtyIdKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaAggDirtyIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, wMediaAggDirtyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.BucketDay, data.ScopeKey, data.CreatedOn, data.UpdatedOn)
	}, rudyGcWMediaAggDirtyBucketDayKey, rudyGcWMediaAggDirtyIdKey)
	return ret, err
}

func (m *defaultWMediaAggDirtyModel) Update(ctx context.Context, newData *WMediaAggDirty) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcWMediaAggDirtyBucketDayKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaAggDirtyBucketDayPrefix, data.BucketDay)
	rudyGcWMediaAggDirtyIdKey := fmt.Sprintf("%s%v", cacheRudyGcWMediaAggDirtyIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, wMediaAggDirtyRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.BucketDay, newData.ScopeKey, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcWMediaAggDirtyBucketDayKey, rudyGcWMediaAggDirtyIdKey)
	return err
}

func (m *defaultWMediaAggDirtyModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcWMediaAggDirtyIdPrefix, primary)
}

func (m *defaultWMediaAggDirtyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", wMediaAggDirtyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultWMediaAggDirtyModel) tableName() string {
	return m.table
}
