// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cPersonFieldNames          = builder.RawFieldNames(&CPerson{})
	cPersonRows                = strings.Join(cPersonFieldNames, ",")
	cPersonRowsExpectAutoSet   = strings.Join(stringx.Remove(cPersonFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cPersonRowsWithPlaceHolder = strings.Join(stringx.Remove(cPersonFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcCPersonIdPrefix = "cache:rudyGc:cPerson:id:"
)

type (
	cPersonModel interface {
		Insert(ctx context.Context, data *CPerson) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CPerson, error)
		Update(ctx context.Context, data *CPerson) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCPersonModel struct {
		sqlc.CachedConn
		table string
	}

	CPerson struct {
		Id                int64  `db:"id"`
		Name              string `db:"name"`
		Alias             string `db:"alias"`
		Chinese           string `db:"chinese"`
		BirthDay          int64  `db:"birth_day"`
		Height            int64  `db:"height"`
		Cup               string `db:"cup"`
		Bwh               string `db:"bwh"`
		Avatar            string `db:"avatar"`
		MovieNumber       int64  `db:"movie_number"`
		OwnedMovieNumber  int64  `db:"owned_movie_number"`
		OwnedWMediaNumber int64  `db:"owned_w_media_number"`
		OwnedWMediaRatio  int64  `db:"owned_w_media_ratio"`
		ScTimes           int64  `db:"sc_times"`
		ComeTimes         int64  `db:"come_times"`
		LastScTime        int64  `db:"last_sc_time"`
		LastScEventTime   int64  `db:"last_sc_event_time"`
		HighestRank       int64  `db:"highest_rank"`
		RankTimes         int64  `db:"rank_times"`
		CreatedOn         int64  `db:"created_on"`
		UpdatedOn         int64  `db:"updated_on"`
	}
)

func newCPersonModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCPersonModel {
	return &defaultCPersonModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`c_person`",
	}
}

func (m *defaultCPersonModel) Delete(ctx context.Context, id int64) error {
	rudyGcCPersonIdKey := fmt.Sprintf("%s%v", cacheRudyGcCPersonIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcCPersonIdKey)
	return err
}

func (m *defaultCPersonModel) FindOne(ctx context.Context, id int64) (*CPerson, error) {
	rudyGcCPersonIdKey := fmt.Sprintf("%s%v", cacheRudyGcCPersonIdPrefix, id)
	var resp CPerson
	err := m.QueryRowCtx(ctx, &resp, rudyGcCPersonIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cPersonRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCPersonModel) Insert(ctx context.Context, data *CPerson) (sql.Result, error) {
	rudyGcCPersonIdKey := fmt.Sprintf("%s%v", cacheRudyGcCPersonIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, cPersonRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Alias, data.Chinese, data.BirthDay, data.Height, data.Cup, data.Bwh, data.Avatar, data.MovieNumber, data.OwnedMovieNumber, data.OwnedWMediaNumber, data.OwnedWMediaRatio, data.ScTimes, data.ComeTimes, data.LastScTime, data.LastScEventTime, data.HighestRank, data.RankTimes, data.CreatedOn, data.UpdatedOn)
	}, rudyGcCPersonIdKey)
	return ret, err
}

func (m *defaultCPersonModel) Update(ctx context.Context, data *CPerson) error {
	rudyGcCPersonIdKey := fmt.Sprintf("%s%v", cacheRudyGcCPersonIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cPersonRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Alias, data.Chinese, data.BirthDay, data.Height, data.Cup, data.Bwh, data.Avatar, data.MovieNumber, data.OwnedMovieNumber, data.OwnedWMediaNumber, data.OwnedWMediaRatio, data.ScTimes, data.ComeTimes, data.LastScTime, data.LastScEventTime, data.HighestRank, data.RankTimes, data.CreatedOn, data.UpdatedOn, data.Id)
	}, rudyGcCPersonIdKey)
	return err
}

func (m *defaultCPersonModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcCPersonIdPrefix, primary)
}

func (m *defaultCPersonModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cPersonRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCPersonModel) tableName() string {
	return m.table
}
