// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	movieReleaseTopStatFieldNames          = builder.RawFieldNames(&MovieReleaseTopStat{})
	movieReleaseTopStatRows                = strings.Join(movieReleaseTopStatFieldNames, ",")
	movieReleaseTopStatRowsExpectAutoSet   = strings.Join(stringx.Remove(movieReleaseTopStatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	movieReleaseTopStatRowsWithPlaceHolder = strings.Join(stringx.Remove(movieReleaseTopStatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcMovieReleaseTopStatIdPrefix                           = "cache:rudyGc:movieReleaseTopStat:id:"
	cacheRudyGcMovieReleaseTopStatAggModeScopeKeyAggTypeAggKeyPrefix = "cache:rudyGc:movieReleaseTopStat:aggMode:scopeKey:aggType:aggKey:"
)

type (
	movieReleaseTopStatModel interface {
		Insert(ctx context.Context, data *MovieReleaseTopStat) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MovieReleaseTopStat, error)
		FindOneByAggModeScopeKeyAggTypeAggKey(ctx context.Context, aggMode string, scopeKey string, aggType string, aggKey string) (*MovieReleaseTopStat, error)
		Update(ctx context.Context, data *MovieReleaseTopStat) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMovieReleaseTopStatModel struct {
		sqlc.CachedConn
		table string
	}

	MovieReleaseTopStat struct {
		Id         int64  `db:"id"`
		AggMode    string `db:"agg_mode"`
		ScopeKey   string `db:"scope_key"`
		Level      string `db:"level"`
		Year       int64  `db:"year"`
		Quarter    int64  `db:"quarter"`
		Month      int64  `db:"month"`
		AggType    string `db:"agg_type"`
		AggKey     string `db:"agg_key"`
		AggId      int64  `db:"agg_id"`
		AggName    string `db:"agg_name"`
		CountAll   int64  `db:"count_all"`
		CountOwned int64  `db:"count_owned"`
		RankNo     int64  `db:"rank_no"`
		CreatedOn  int64  `db:"created_on"`
		UpdatedOn  int64  `db:"updated_on"`
	}
)

func newMovieReleaseTopStatModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMovieReleaseTopStatModel {
	return &defaultMovieReleaseTopStatModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`movie_release_top_stat`",
	}
}

func (m *defaultMovieReleaseTopStatModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcMovieReleaseTopStatIdKey := fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseTopStatIdPrefix, id)
	rudyGcMovieReleaseTopStatAggModeScopeKeyAggTypeAggKeyKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheRudyGcMovieReleaseTopStatAggModeScopeKeyAggTypeAggKeyPrefix, data.AggMode, data.ScopeKey, data.AggType, data.AggKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcMovieReleaseTopStatIdKey, rudyGcMovieReleaseTopStatAggModeScopeKeyAggTypeAggKeyKey)
	return err
}

func (m *defaultMovieReleaseTopStatModel) FindOne(ctx context.Context, id int64) (*MovieReleaseTopStat, error) {
	rudyGcMovieReleaseTopStatIdKey := fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseTopStatIdPrefix, id)
	var resp MovieReleaseTopStat
	err := m.QueryRowCtx(ctx, &resp, rudyGcMovieReleaseTopStatIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", movieReleaseTopStatRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMovieReleaseTopStatModel) FindOneByAggModeScopeKeyAggTypeAggKey(ctx context.Context, aggMode string, scopeKey string, aggType string, aggKey string) (*MovieReleaseTopStat, error) {
	rudyGcMovieReleaseTopStatAggModeScopeKeyAggTypeAggKeyKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheRudyGcMovieReleaseTopStatAggModeScopeKeyAggTypeAggKeyPrefix, aggMode, scopeKey, aggType, aggKey)
	var resp MovieReleaseTopStat
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcMovieReleaseTopStatAggModeScopeKeyAggTypeAggKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `agg_mode` = ? and `scope_key` = ? and `agg_type` = ? and `agg_key` = ? limit 1", movieReleaseTopStatRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, aggMode, scopeKey, aggType, aggKey); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMovieReleaseTopStatModel) Insert(ctx context.Context, data *MovieReleaseTopStat) (sql.Result, error) {
	rudyGcMovieReleaseTopStatIdKey := fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseTopStatIdPrefix, data.Id)
	rudyGcMovieReleaseTopStatAggModeScopeKeyAggTypeAggKeyKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheRudyGcMovieReleaseTopStatAggModeScopeKeyAggTypeAggKeyPrefix, data.AggMode, data.ScopeKey, data.AggType, data.AggKey)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, movieReleaseTopStatRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.AggMode, data.ScopeKey, data.Level, data.Year, data.Quarter, data.Month, data.AggType, data.AggKey, data.AggId, data.AggName, data.CountAll, data.CountOwned, data.RankNo, data.CreatedOn, data.UpdatedOn)
	}, rudyGcMovieReleaseTopStatIdKey, rudyGcMovieReleaseTopStatAggModeScopeKeyAggTypeAggKeyKey)
	return ret, err
}

func (m *defaultMovieReleaseTopStatModel) Update(ctx context.Context, newData *MovieReleaseTopStat) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcMovieReleaseTopStatIdKey := fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseTopStatIdPrefix, data.Id)
	rudyGcMovieReleaseTopStatAggModeScopeKeyAggTypeAggKeyKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheRudyGcMovieReleaseTopStatAggModeScopeKeyAggTypeAggKeyPrefix, data.AggMode, data.ScopeKey, data.AggType, data.AggKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, movieReleaseTopStatRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.AggMode, newData.ScopeKey, newData.Level, newData.Year, newData.Quarter, newData.Month, newData.AggType, newData.AggKey, newData.AggId, newData.AggName, newData.CountAll, newData.CountOwned, newData.RankNo, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcMovieReleaseTopStatIdKey, rudyGcMovieReleaseTopStatAggModeScopeKeyAggTypeAggKeyKey)
	return err
}

func (m *defaultMovieReleaseTopStatModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcMovieReleaseTopStatIdPrefix, primary)
}

func (m *defaultMovieReleaseTopStatModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", movieReleaseTopStatRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMovieReleaseTopStatModel) tableName() string {
	return m.table
}
