// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tSukebeiTorrentFieldNames          = builder.RawFieldNames(&TSukebeiTorrent{})
	tSukebeiTorrentRows                = strings.Join(tSukebeiTorrentFieldNames, ",")
	tSukebeiTorrentRowsExpectAutoSet   = strings.Join(stringx.Remove(tSukebeiTorrentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tSukebeiTorrentRowsWithPlaceHolder = strings.Join(stringx.Remove(tSukebeiTorrentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcTSukebeiTorrentIdPrefix     = "cache:rudyGc:tSukebeiTorrent:id:"
	cacheRudyGcTSukebeiTorrentViewIdPrefix = "cache:rudyGc:tSukebeiTorrent:viewId:"
)

type (
	tSukebeiTorrentModel interface {
		Insert(ctx context.Context, data *TSukebeiTorrent) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TSukebeiTorrent, error)
		FindOneByViewId(ctx context.Context, viewId int64) (*TSukebeiTorrent, error)
		Update(ctx context.Context, data *TSukebeiTorrent) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTSukebeiTorrentModel struct {
		sqlc.CachedConn
		table string
	}

	TSukebeiTorrent struct {
		Id           int64  `db:"id"`
		MovieJavId   string `db:"movie_jav_id"`
		QueryText    string `db:"query_text"`
		TorrentTitle string `db:"torrent_title"`
		ViewId       int64  `db:"view_id"`
		InfoHash     string `db:"info_hash"`
		SizeBytes    int64  `db:"size_bytes"`
		PublishTime  int64  `db:"publish_time"`
		Seeders      int64  `db:"seeders"`
		Leechers     int64  `db:"leechers"`
		Completed    int64  `db:"completed"`
		LastSeenTime int64  `db:"last_seen_time"`
		CreatedOn    int64  `db:"created_on"`
		UpdatedOn    int64  `db:"updated_on"`
	}
)

func newTSukebeiTorrentModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTSukebeiTorrentModel {
	return &defaultTSukebeiTorrentModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_sukebei_torrent`",
	}
}

func (m *defaultTSukebeiTorrentModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcTSukebeiTorrentIdKey := fmt.Sprintf("%s%v", cacheRudyGcTSukebeiTorrentIdPrefix, id)
	rudyGcTSukebeiTorrentViewIdKey := fmt.Sprintf("%s%v", cacheRudyGcTSukebeiTorrentViewIdPrefix, data.ViewId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcTSukebeiTorrentIdKey, rudyGcTSukebeiTorrentViewIdKey)
	return err
}

func (m *defaultTSukebeiTorrentModel) FindOne(ctx context.Context, id int64) (*TSukebeiTorrent, error) {
	rudyGcTSukebeiTorrentIdKey := fmt.Sprintf("%s%v", cacheRudyGcTSukebeiTorrentIdPrefix, id)
	var resp TSukebeiTorrent
	err := m.QueryRowCtx(ctx, &resp, rudyGcTSukebeiTorrentIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tSukebeiTorrentRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTSukebeiTorrentModel) FindOneByViewId(ctx context.Context, viewId int64) (*TSukebeiTorrent, error) {
	rudyGcTSukebeiTorrentViewIdKey := fmt.Sprintf("%s%v", cacheRudyGcTSukebeiTorrentViewIdPrefix, viewId)
	var resp TSukebeiTorrent
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcTSukebeiTorrentViewIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `view_id` = ? limit 1", tSukebeiTorrentRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, viewId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTSukebeiTorrentModel) Insert(ctx context.Context, data *TSukebeiTorrent) (sql.Result, error) {
	rudyGcTSukebeiTorrentIdKey := fmt.Sprintf("%s%v", cacheRudyGcTSukebeiTorrentIdPrefix, data.Id)
	rudyGcTSukebeiTorrentViewIdKey := fmt.Sprintf("%s%v", cacheRudyGcTSukebeiTorrentViewIdPrefix, data.ViewId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tSukebeiTorrentRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MovieJavId, data.QueryText, data.TorrentTitle, data.ViewId, data.InfoHash, data.SizeBytes, data.PublishTime, data.Seeders, data.Leechers, data.Completed, data.LastSeenTime, data.CreatedOn, data.UpdatedOn)
	}, rudyGcTSukebeiTorrentIdKey, rudyGcTSukebeiTorrentViewIdKey)
	return ret, err
}

func (m *defaultTSukebeiTorrentModel) Update(ctx context.Context, newData *TSukebeiTorrent) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcTSukebeiTorrentIdKey := fmt.Sprintf("%s%v", cacheRudyGcTSukebeiTorrentIdPrefix, data.Id)
	rudyGcTSukebeiTorrentViewIdKey := fmt.Sprintf("%s%v", cacheRudyGcTSukebeiTorrentViewIdPrefix, data.ViewId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tSukebeiTorrentRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MovieJavId, newData.QueryText, newData.TorrentTitle, newData.ViewId, newData.InfoHash, newData.SizeBytes, newData.PublishTime, newData.Seeders, newData.Leechers, newData.Completed, newData.LastSeenTime, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcTSukebeiTorrentIdKey, rudyGcTSukebeiTorrentViewIdKey)
	return err
}

func (m *defaultTSukebeiTorrentModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcTSukebeiTorrentIdPrefix, primary)
}

func (m *defaultTSukebeiTorrentModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tSukebeiTorrentRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTSukebeiTorrentModel) tableName() string {
	return m.table
}
