// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tSukebeiTorrentFetchFieldNames          = builder.RawFieldNames(&TSukebeiTorrentFetch{})
	tSukebeiTorrentFetchRows                = strings.Join(tSukebeiTorrentFetchFieldNames, ",")
	tSukebeiTorrentFetchRowsExpectAutoSet   = strings.Join(stringx.Remove(tSukebeiTorrentFetchFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tSukebeiTorrentFetchRowsWithPlaceHolder = strings.Join(stringx.Remove(tSukebeiTorrentFetchFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcTSukebeiTorrentFetchIdPrefix         = "cache:rudyGc:tSukebeiTorrentFetch:id:"
	cacheRudyGcTSukebeiTorrentFetchMovieJavIdPrefix = "cache:rudyGc:tSukebeiTorrentFetch:movieJavId:"
)

type (
	tSukebeiTorrentFetchModel interface {
		Insert(ctx context.Context, data *TSukebeiTorrentFetch) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TSukebeiTorrentFetch, error)
		FindOneByMovieJavId(ctx context.Context, movieJavId string) (*TSukebeiTorrentFetch, error)
		Update(ctx context.Context, data *TSukebeiTorrentFetch) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTSukebeiTorrentFetchModel struct {
		sqlc.CachedConn
		table string
	}

	TSukebeiTorrentFetch struct {
		Id                int64  `db:"id"`
		MovieJavId        string `db:"movie_jav_id"`
		MovieName         string `db:"movie_name"`
		FetchStatus       int64  `db:"fetch_status"`
		TryCount          int64  `db:"try_count"`
		LastFetchTime     int64  `db:"last_fetch_time"`
		LastSuccessTime   int64  `db:"last_success_time"`
		LastError         string `db:"last_error"`
		LastResultCount   int64  `db:"last_result_count"`
		SourceUrl         string `db:"source_url"`
		CreatedOn         int64  `db:"created_on"`
		UpdatedOn         int64  `db:"updated_on"`
		TorrentHashCount  int64  `db:"torrent_hash_count"`
		LatestPublishTime int64  `db:"latest_publish_time"`
		ReleaseDate       int64  `db:"release_date"`
	}
)

func newTSukebeiTorrentFetchModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTSukebeiTorrentFetchModel {
	return &defaultTSukebeiTorrentFetchModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_sukebei_torrent_fetch`",
	}
}

func (m *defaultTSukebeiTorrentFetchModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcTSukebeiTorrentFetchIdKey := fmt.Sprintf("%s%v", cacheRudyGcTSukebeiTorrentFetchIdPrefix, id)
	rudyGcTSukebeiTorrentFetchMovieJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcTSukebeiTorrentFetchMovieJavIdPrefix, data.MovieJavId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcTSukebeiTorrentFetchIdKey, rudyGcTSukebeiTorrentFetchMovieJavIdKey)
	return err
}

func (m *defaultTSukebeiTorrentFetchModel) FindOne(ctx context.Context, id int64) (*TSukebeiTorrentFetch, error) {
	rudyGcTSukebeiTorrentFetchIdKey := fmt.Sprintf("%s%v", cacheRudyGcTSukebeiTorrentFetchIdPrefix, id)
	var resp TSukebeiTorrentFetch
	err := m.QueryRowCtx(ctx, &resp, rudyGcTSukebeiTorrentFetchIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tSukebeiTorrentFetchRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTSukebeiTorrentFetchModel) FindOneByMovieJavId(ctx context.Context, movieJavId string) (*TSukebeiTorrentFetch, error) {
	rudyGcTSukebeiTorrentFetchMovieJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcTSukebeiTorrentFetchMovieJavIdPrefix, movieJavId)
	var resp TSukebeiTorrentFetch
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcTSukebeiTorrentFetchMovieJavIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `movie_jav_id` = ? limit 1", tSukebeiTorrentFetchRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, movieJavId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTSukebeiTorrentFetchModel) Insert(ctx context.Context, data *TSukebeiTorrentFetch) (sql.Result, error) {
	rudyGcTSukebeiTorrentFetchIdKey := fmt.Sprintf("%s%v", cacheRudyGcTSukebeiTorrentFetchIdPrefix, data.Id)
	rudyGcTSukebeiTorrentFetchMovieJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcTSukebeiTorrentFetchMovieJavIdPrefix, data.MovieJavId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tSukebeiTorrentFetchRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MovieJavId, data.MovieName, data.FetchStatus, data.TryCount, data.LastFetchTime, data.LastSuccessTime, data.LastError, data.LastResultCount, data.SourceUrl, data.CreatedOn, data.UpdatedOn, data.TorrentHashCount, data.LatestPublishTime, data.ReleaseDate)
	}, rudyGcTSukebeiTorrentFetchIdKey, rudyGcTSukebeiTorrentFetchMovieJavIdKey)
	return ret, err
}

func (m *defaultTSukebeiTorrentFetchModel) Update(ctx context.Context, newData *TSukebeiTorrentFetch) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcTSukebeiTorrentFetchIdKey := fmt.Sprintf("%s%v", cacheRudyGcTSukebeiTorrentFetchIdPrefix, data.Id)
	rudyGcTSukebeiTorrentFetchMovieJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcTSukebeiTorrentFetchMovieJavIdPrefix, data.MovieJavId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tSukebeiTorrentFetchRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MovieJavId, newData.MovieName, newData.FetchStatus, newData.TryCount, newData.LastFetchTime, newData.LastSuccessTime, newData.LastError, newData.LastResultCount, newData.SourceUrl, newData.CreatedOn, newData.UpdatedOn, newData.TorrentHashCount, newData.LatestPublishTime, newData.ReleaseDate, newData.Id)
	}, rudyGcTSukebeiTorrentFetchIdKey, rudyGcTSukebeiTorrentFetchMovieJavIdKey)
	return err
}

func (m *defaultTSukebeiTorrentFetchModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcTSukebeiTorrentFetchIdPrefix, primary)
}

func (m *defaultTSukebeiTorrentFetchModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tSukebeiTorrentFetchRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTSukebeiTorrentFetchModel) tableName() string {
	return m.table
}
