// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	wFolderFieldNames          = builder.RawFieldNames(&WFolder{})
	wFolderRows                = strings.Join(wFolderFieldNames, ",")
	wFolderRowsExpectAutoSet   = strings.Join(stringx.Remove(wFolderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	wFolderRowsWithPlaceHolder = strings.Join(stringx.Remove(wFolderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcWFolderIdPrefix                     = "cache:rudyGc:wFolder:id:"
	cacheRudyGcWFolderParentIdNameSourceTypePrefix = "cache:rudyGc:wFolder:parentId:name:sourceType:"
	cacheRudyGcWFolderPathSourceTypePrefix         = "cache:rudyGc:wFolder:path:sourceType:"
)

type (
	wFolderModel interface {
		Insert(ctx context.Context, data *WFolder) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*WFolder, error)
		FindOneByParentIdNameSourceType(ctx context.Context, parentId int64, name string, sourceType int64) (*WFolder, error)
		FindOneByPathSourceType(ctx context.Context, path string, sourceType int64) (*WFolder, error)
		Update(ctx context.Context, data *WFolder) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWFolderModel struct {
		sqlc.CachedConn
		table string
	}

	WFolder struct {
		Id         int64  `db:"id"`
		ParentId   int64  `db:"parent_id"`
		Name       string `db:"name"`
		SourceType int64  `db:"source_type"`
		Depth      int64  `db:"depth"`
		Path       string `db:"path"`
		PathHash   string `db:"path_hash"`
		CreatedOn  int64  `db:"created_on"`
		UpdatedOn  int64  `db:"updated_on"`
	}
)

func wFolderParentIdNameSourceTypeCacheKey(parentId int64, name string, sourceType int64) string {
	return fmt.Sprintf("%s%v:%v:%v", cacheRudyGcWFolderParentIdNameSourceTypePrefix, parentId, name, sourceType)
}

func wFolderPathSourceTypeCacheKey(path string, sourceType int64) string {
	return fmt.Sprintf("%s%v:%v", cacheRudyGcWFolderPathSourceTypePrefix, path, sourceType)
}

func newWFolderModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultWFolderModel {
	return &defaultWFolderModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`w_folder`",
	}
}

func (m *defaultWFolderModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcWFolderIdKey := fmt.Sprintf("%s%v", cacheRudyGcWFolderIdPrefix, id)
	rudyGcWFolderParentIdNameSourceTypeKey := wFolderParentIdNameSourceTypeCacheKey(data.ParentId, data.Name, data.SourceType)
	rudyGcWFolderPathSourceTypeKey := wFolderPathSourceTypeCacheKey(data.Path, data.SourceType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcWFolderIdKey, rudyGcWFolderParentIdNameSourceTypeKey, rudyGcWFolderPathSourceTypeKey)
	return err
}

func (m *defaultWFolderModel) FindOne(ctx context.Context, id int64) (*WFolder, error) {
	rudyGcWFolderIdKey := fmt.Sprintf("%s%v", cacheRudyGcWFolderIdPrefix, id)
	var resp WFolder
	err := m.QueryRowCtx(ctx, &resp, rudyGcWFolderIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", wFolderRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWFolderModel) FindOneByParentIdNameSourceType(ctx context.Context, parentId int64, name string, sourceType int64) (*WFolder, error) {
	rudyGcWFolderParentIdNameSourceTypeKey := wFolderParentIdNameSourceTypeCacheKey(parentId, name, sourceType)
	var resp WFolder
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcWFolderParentIdNameSourceTypeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `parent_id` = ? and `name` = ? and `source_type` = ? limit 1", wFolderRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, parentId, name, sourceType); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWFolderModel) FindOneByPathSourceType(ctx context.Context, path string, sourceType int64) (*WFolder, error) {
	rudyGcWFolderPathSourceTypeKey := wFolderPathSourceTypeCacheKey(path, sourceType)
	var resp WFolder
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcWFolderPathSourceTypeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `path` = ? and `source_type` = ? limit 1", wFolderRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, path, sourceType); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWFolderModel) Insert(ctx context.Context, data *WFolder) (sql.Result, error) {
	rudyGcWFolderIdKey := fmt.Sprintf("%s%v", cacheRudyGcWFolderIdPrefix, data.Id)
	rudyGcWFolderParentIdNameSourceTypeKey := wFolderParentIdNameSourceTypeCacheKey(data.ParentId, data.Name, data.SourceType)
	rudyGcWFolderPathSourceTypeKey := wFolderPathSourceTypeCacheKey(data.Path, data.SourceType)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, wFolderRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ParentId, data.Name, data.SourceType, data.Depth, data.Path, data.PathHash, data.CreatedOn, data.UpdatedOn)
	}, rudyGcWFolderIdKey, rudyGcWFolderParentIdNameSourceTypeKey, rudyGcWFolderPathSourceTypeKey)
	return ret, err
}

func (m *defaultWFolderModel) Update(ctx context.Context, newData *WFolder) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcWFolderIdKey := fmt.Sprintf("%s%v", cacheRudyGcWFolderIdPrefix, data.Id)
	rudyGcWFolderParentIdNameSourceTypeKey := wFolderParentIdNameSourceTypeCacheKey(data.ParentId, data.Name, data.SourceType)
	rudyGcWFolderPathSourceTypeKey := wFolderPathSourceTypeCacheKey(data.Path, data.SourceType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, wFolderRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ParentId, newData.Name, newData.SourceType, newData.Depth, newData.Path, newData.PathHash, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcWFolderIdKey, rudyGcWFolderParentIdNameSourceTypeKey, rudyGcWFolderPathSourceTypeKey)
	return err
}

func (m *defaultWFolderModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcWFolderIdPrefix, primary)
}

func (m *defaultWFolderModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", wFolderRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultWFolderModel) tableName() string {
	return m.table
}
