// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	wKvFieldNames          = builder.RawFieldNames(&WKv{})
	wKvRows                = strings.Join(wKvFieldNames, ",")
	wKvRowsExpectAutoSet   = strings.Join(stringx.Remove(wKvFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	wKvRowsWithPlaceHolder = strings.Join(stringx.Remove(wKvFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcWKvIdPrefix      = "cache:rudyGc:wKv:id:"
	cacheRudyGcWKvItemKeyPrefix = "cache:rudyGc:wKv:itemKey:"
)

type (
	wKvModel interface {
		Insert(ctx context.Context, data *WKv) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*WKv, error)
		FindOneByItemKey(ctx context.Context, itemKey string) (*WKv, error)
		Update(ctx context.Context, data *WKv) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWKvModel struct {
		sqlc.CachedConn
		table string
	}

	WKv struct {
		Id          int64  `db:"id"`
		ItemKey     string `db:"item_key"`
		ItemValue   string `db:"item_value"`
		CreatedTime int64  `db:"created_time"`
		UpdatedTime int64  `db:"updated_time"`
	}
)

func newWKvModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultWKvModel {
	return &defaultWKvModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`w_kv`",
	}
}

func (m *defaultWKvModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcWKvIdKey := fmt.Sprintf("%s%v", cacheRudyGcWKvIdPrefix, id)
	rudyGcWKvItemKeyKey := fmt.Sprintf("%s%v", cacheRudyGcWKvItemKeyPrefix, data.ItemKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcWKvIdKey, rudyGcWKvItemKeyKey)
	return err
}

func (m *defaultWKvModel) FindOne(ctx context.Context, id int64) (*WKv, error) {
	rudyGcWKvIdKey := fmt.Sprintf("%s%v", cacheRudyGcWKvIdPrefix, id)
	var resp WKv
	err := m.QueryRowCtx(ctx, &resp, rudyGcWKvIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", wKvRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWKvModel) FindOneByItemKey(ctx context.Context, itemKey string) (*WKv, error) {
	rudyGcWKvItemKeyKey := fmt.Sprintf("%s%v", cacheRudyGcWKvItemKeyPrefix, itemKey)
	var resp WKv
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcWKvItemKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (any, error) {
		query := fmt.Sprintf("select %s from %s where `item_key` = ? limit 1", wKvRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, itemKey); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWKvModel) Insert(ctx context.Context, data *WKv) (sql.Result, error) {
	rudyGcWKvIdKey := fmt.Sprintf("%s%v", cacheRudyGcWKvIdPrefix, data.Id)
	rudyGcWKvItemKeyKey := fmt.Sprintf("%s%v", cacheRudyGcWKvItemKeyPrefix, data.ItemKey)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, wKvRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ItemKey, data.ItemValue, data.CreatedTime, data.UpdatedTime)
	}, rudyGcWKvIdKey, rudyGcWKvItemKeyKey)
	return ret, err
}

func (m *defaultWKvModel) Update(ctx context.Context, newData *WKv) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcWKvIdKey := fmt.Sprintf("%s%v", cacheRudyGcWKvIdPrefix, data.Id)
	rudyGcWKvItemKeyKey := fmt.Sprintf("%s%v", cacheRudyGcWKvItemKeyPrefix, data.ItemKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, wKvRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ItemKey, newData.ItemValue, newData.CreatedTime, newData.UpdatedTime, newData.Id)
	}, rudyGcWKvIdKey, rudyGcWKvItemKeyKey)
	return err
}

func (m *defaultWKvModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcWKvIdPrefix, primary)
}

func (m *defaultWKvModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", wKvRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultWKvModel) tableName() string {
	return m.table
}
