DataSource: root:4521822123@tcp(127.0.0.1:3306)/rudy_gc?charset=utf8mb4&parseTime=true&loc=Local

Port: ":5010"


Cache:
  - Host: 127.0.0.1:6379
    Pass: ""
    Type: node
    Weight: 100

BizRedis:
  Host: 127.0.0.1:6378
  Pass:
  Type: node

MovieTypeCache:
  Prefix: "rudy:mt"
  Version: "v1"
  TTL: "24h"

Fetcher:
  UserAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
  Cookie: "timezone=-480; dm=y78k; __utma=110267277.920997940.1724145497.1724145497.1724145497.1; __utmz=110267277.1724145497.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utma=110267277.920997940.1724145497.1724145497.1724145497.1; __utmz=110267277.1724145497.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __qca=P0-871011025-1724145497453; over18=18; cf_clearance=3BdIk0lyMi_btHD3V4fwScat_oUp_vjGL.HDvVSD.uE-1724199230-1.2.1.1-mr0zZw7aXx5vNmBFzHqt8AHgEQTDQX0Cxs1wmtPn5GKcekyZMpILRit5pGEOYL3K9lrteb0ktFttDNfQD.qq4Dlw7vIrvNbD3RvmJCugJNYwPdANw18ayndp.FX5PSo6NIUV2tEH4dzEzoyW_W2B_6HO6wO_oWkfmFBGRg0LESZ.hlf13G2Ca65ZoJdU6cuxsGSCeX_9yYwknWhTIMFiGbdMxgLX9kVSX1M09CgCldAXLWVS7utw5EtrhnP_pyFgPMkQtOJPeKGKGmXNM4ba_ZLyfRVKEsN70liLeWnaStzBrC95f0_e9CsdxHpuwt8qwPJyk.Fq7qSXyDzSOP_ynezAQ0egVDoPNx9CPu9Bp.gQEwZjuW8u4rgFS.kJsjYPYjjwIW4hKxh1kWR8yjSSU.IgZXfAt.nX9LtQWo1Ezktn3EwpMGJXUDpEWNAG8cWps1j0QkPu4zN7C7TqmiB2xTBr.sRnrI.JDTcSc.9I0.3K1vnnHz4LN2N6.RuAwmdIHSiThZA_YoTkhm2r.ixQ1Q"
  Proxy: "http://127.0.0.1:1087/"
  Timeout: 15

Spider:
  JavAddress: "www.y94i.com"
  BusAddress: "www.javbus.com"