// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aItemFieldNames          = builder.RawFieldNames(&AItem{})
	aItemRows                = strings.Join(aItemFieldNames, ",")
	aItemRowsExpectAutoSet   = strings.Join(stringx.Remove(aItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	aItemRowsWithPlaceHolder = strings.Join(stringx.Remove(aItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheZeroGcV2BAItemIdPrefix    = "cache:zeroGcV2B:aItem:id:"
	cacheZeroGcV2BAItemJavIdPrefix = "cache:zeroGcV2B:aItem:javId:"
)

type (
	aItemModel interface {
		Insert(ctx context.Context, data *AItem) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AItem, error)
		FindOneByJavId(ctx context.Context, javId string) (*AItem, error)
		Update(ctx context.Context, data *AItem) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAItemModel struct {
		sqlc.CachedConn
		table string
	}

	AItem struct {
		Id         int64  `db:"id"`
		Name       string `db:"name"`
		JavId      string `db:"jav_id"`
		Prefix     string `db:"prefix"`
		HasDetail  int64  `db:"has_detail"`
		HasBus     int64  `db:"has_bus"`
		SearchType int64  `db:"search_type"`
		SearchBy   string `db:"search_by"`
		CreatedOn  int64  `db:"created_on"`
		UpdatedOn  int64  `db:"updated_on"`
	}
)

func newAItemModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAItemModel {
	return &defaultAItemModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`a__item`",
	}
}

func (m *defaultAItemModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	zeroGcV2BAItemIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BAItemIdPrefix, id)
	zeroGcV2BAItemJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BAItemJavIdPrefix, data.JavId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, zeroGcV2BAItemIdKey, zeroGcV2BAItemJavIdKey)
	return err
}

func (m *defaultAItemModel) FindOne(ctx context.Context, id int64) (*AItem, error) {
	zeroGcV2BAItemIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BAItemIdPrefix, id)
	var resp AItem
	err := m.QueryRowCtx(ctx, &resp, zeroGcV2BAItemIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", aItemRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAItemModel) FindOneByJavId(ctx context.Context, javId string) (*AItem, error) {
	zeroGcV2BAItemJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BAItemJavIdPrefix, javId)
	var resp AItem
	err := m.QueryRowIndexCtx(ctx, &resp, zeroGcV2BAItemJavIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `jav_id` = ? limit 1", aItemRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, javId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAItemModel) Insert(ctx context.Context, data *AItem) (sql.Result, error) {
	zeroGcV2BAItemIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BAItemIdPrefix, data.Id)
	zeroGcV2BAItemJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BAItemJavIdPrefix, data.JavId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, aItemRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.JavId, data.Prefix, data.HasDetail, data.HasBus, data.SearchType, data.SearchBy, data.CreatedOn, data.UpdatedOn)
	}, zeroGcV2BAItemIdKey, zeroGcV2BAItemJavIdKey)
	return ret, err
}

func (m *defaultAItemModel) Update(ctx context.Context, newData *AItem) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	zeroGcV2BAItemIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BAItemIdPrefix, data.Id)
	zeroGcV2BAItemJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BAItemJavIdPrefix, data.JavId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, aItemRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.JavId, newData.Prefix, newData.HasDetail, newData.HasBus, newData.SearchType, newData.SearchBy, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, zeroGcV2BAItemIdKey, zeroGcV2BAItemJavIdKey)
	return err
}

func (m *defaultAItemModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheZeroGcV2BAItemIdPrefix, primary)
}

func (m *defaultAItemModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", aItemRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAItemModel) tableName() string {
	return m.table
}
