// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package spider

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dSeedFieldNames          = builder.RawFieldNames(&DSeed{})
	dSeedRows                = strings.Join(dSeedFieldNames, ",")
	dSeedRowsExpectAutoSet   = strings.Join(stringx.Remove(dSeedFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	dSeedRowsWithPlaceHolder = strings.Join(stringx.Remove(dSeedFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	dSeedModel interface {
		Insert(ctx context.Context, data *DSeed) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*DSeed, error)
		FindOneByName(ctx context.Context, name string) (*DSeed, error)
		Update(ctx context.Context, data *DSeed) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDSeedModel struct {
		conn  sqlx.SqlConn
		table string
	}

	DSeed struct {
		Id            int64  `db:"id"`
		Name          string `db:"name"`            // 查询名(前缀/标签具体值)
		Active        int64  `db:"active"`          // 状态(1=inactive,2=active)
		SearchType    int64  `db:"search_type"`     // 1=Offset,2=StartEnd
		NameType      int64  `db:"name_type"`       // 1=Prefix,2=Label
		PageNow       int64  `db:"page_now"`        // 当前断点页(最近成功处理到的页码)
		Offset        int64  `db:"offset"`          // 仅在SearchType=Offset时有效
		StartPage     int64  `db:"start_page"`      // 仅在SearchType=StartEnd时有效
		EndPage       int64  `db:"end_page"`        // 仅在SearchType=StartEnd时有效
		LastQueryTime int64  `db:"last_query_time"` // 最后一次开始抓取的Unix时间戳(秒,0=未运行)
		LastStatus    int64  `db:"last_status"`     // 0=idle,1=ok,2=empty,3=error
		LastError     string `db:"last_error"`      // 最后一次错误摘要
		CreatedOn     int64  `db:"created_on"`
		UpdatedOn     int64  `db:"updated_on"`
	}
)

func newDSeedModel(conn sqlx.SqlConn) *defaultDSeedModel {
	return &defaultDSeedModel{
		conn:  conn,
		table: "`d_seed`",
	}
}

func (m *defaultDSeedModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDSeedModel) FindOne(ctx context.Context, id int64) (*DSeed, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dSeedRows, m.table)
	var resp DSeed
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDSeedModel) FindOneByName(ctx context.Context, name string) (*DSeed, error) {
	var resp DSeed
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", dSeedRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDSeedModel) Insert(ctx context.Context, data *DSeed) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, dSeedRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Active, data.SearchType, data.NameType, data.PageNow, data.Offset, data.StartPage, data.EndPage, data.LastQueryTime, data.LastStatus, data.LastError, data.CreatedOn, data.UpdatedOn)
	return ret, err
}

func (m *defaultDSeedModel) Update(ctx context.Context, newData *DSeed) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dSeedRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.Active, newData.SearchType, newData.NameType, newData.PageNow, newData.Offset, newData.StartPage, newData.EndPage, newData.LastQueryTime, newData.LastStatus, newData.LastError, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	return err
}

func (m *defaultDSeedModel) tableName() string {
	return m.table
}
