package contracts

type LegacyRoute struct {
	Method string
	Path   string
	Group  string
}

func LegacyAPIRoutes() []LegacyRoute {
	return []LegacyRoute{
		{Method: "POST", Path: "/api/movie/:movie/downloadlater", Group: "movie"},
		{Method: "DELETE", Path: "/api/movie/:movie/downloadlater", Group: "movie"},
		{Method: "POST", Path: "/api/movie/:movie/download-cover", Group: "movie"},
		{Method: "POST", Path: "/api/movie/:movie/move-wmedia-removed", Group: "movie"},
		{Method: "POST", Path: "/api/movie/:movie/add-cast", Group: "movie"},
		{Method: "POST", Path: "/api/movie/:movie/album-item", Group: "album"},
		{Method: "DELETE", Path: "/api/movie/:movie/album-item", Group: "album"},
		{Method: "POST", Path: "/api/albums", Group: "album"},
		{Method: "POST", Path: "/api/albums/:albumID/items/remove", Group: "album"},
		{Method: "POST", Path: "/api/albums/:albumID/items/batch-remove", Group: "album"},
		{Method: "POST", Path: "/api/albums/:albumID/items/batch-move", Group: "album"},
		{Method: "POST", Path: "/api/movie/:movie/movie-album-item", Group: "movie-album"},
		{Method: "POST", Path: "/api/movie-albums", Group: "movie-album"},
		{Method: "POST", Path: "/api/movie-albums/:albumID/items/remove", Group: "movie-album"},
		{Method: "POST", Path: "/api/movie-albums/:albumID/execute-remove", Group: "movie-album"},
		{Method: "POST", Path: "/api/movie-albums/:albumID/remove-downloaded-items-preview", Group: "movie-album"},
		{Method: "POST", Path: "/api/movie-albums/:albumID/remove-downloaded-items", Group: "movie-album"},
		{Method: "POST", Path: "/api/d-seeds", Group: "seed"},
		{Method: "POST", Path: "/api/d-seeds/:id", Group: "seed"},
		{Method: "POST", Path: "/api/sc-events/:name", Group: "sc"},
		{Method: "POST", Path: "/api/medias/:id/probe-meta", Group: "media"},
		{Method: "GET", Path: "/api/persons/:id/merge-candidates", Group: "person"},
		{Method: "POST", Path: "/api/persons/merge-preview", Group: "person"},
		{Method: "POST", Path: "/api/persons/merge", Group: "person"},
		{Method: "POST", Path: "/api/e-items/status/batch", Group: "admin"},
		{Method: "POST", Path: "/api/e-items/:id/status", Group: "admin"},
		{Method: "DELETE", Path: "/api/e-items/:id", Group: "admin"},
		{Method: "POST", Path: "/api/open-finder", Group: "system"},
		{Method: "POST", Path: "/api/w-kv/date", Group: "system"},
		{Method: "POST", Path: "/api/triggers/daily-best", Group: "trigger"},
		{Method: "POST", Path: "/api/triggers/daily-best-sync", Group: "trigger"},
		{Method: "POST", Path: "/api/triggers/rebuild-cast-rank", Group: "trigger"},
		{Method: "POST", Path: "/api/triggers/cast/rebuild-rank", Group: "trigger"},
		{Method: "POST", Path: "/api/triggers/seeds", Group: "trigger"},
		{Method: "POST", Path: "/api/triggers/seed-by-name", Group: "trigger"},
		{Method: "POST", Path: "/api/triggers/refresh-oldest-detail", Group: "trigger"},
		{Method: "GET", Path: "/api/triggers/media/plan", Group: "media"},
		{Method: "POST", Path: "/api/triggers/media/precheck", Group: "media"},
		{Method: "POST", Path: "/api/triggers/media/commit", Group: "media"},
		{Method: "POST", Path: "/api/triggers/media/return", Group: "media"},
		{Method: "POST", Path: "/api/triggers/media/rollback", Group: "media"},
		{Method: "POST", Path: "/api/triggers/media/rescan", Group: "media"},
		{Method: "POST", Path: "/api/agg/w-media/backfill", Group: "agg"},
		{Method: "POST", Path: "/api/agg/movie-release/backfill", Group: "agg"},
		{Method: "GET", Path: "/api/triggers/sc-media/plan", Group: "sc-media"},
		{Method: "POST", Path: "/api/triggers/sc-media/precheck", Group: "sc-media"},
		{Method: "POST", Path: "/api/triggers/sc-media/commit", Group: "sc-media"},
		{Method: "POST", Path: "/api/triggers/sc-media/return", Group: "sc-media"},
		{Method: "POST", Path: "/api/triggers/sc/add-preview", Group: "sc"},
		{Method: "POST", Path: "/api/triggers/sc/add", Group: "sc"},
		{Method: "POST", Path: "/api/triggers/sc/rebuild-stats", Group: "sc"},
		{Method: "POST", Path: "/api/triggers/sc/pick-smart-copy", Group: "sc"},
		{Method: "POST", Path: "/api/triggers/sc/pick-smart-only", Group: "sc"},
		{Method: "GET", Path: "/api/triggers/sc/copy-status", Group: "sc"},
		{Method: "POST", Path: "/api/triggers/sc/copy-stop", Group: "sc"},
		{Method: "POST", Path: "/api/crawler/jobs/start", Group: "crawler"},
		{Method: "POST", Path: "/api/crawler/jobs/fetch-site/preview", Group: "crawler"},
		{Method: "GET", Path: "/api/crawler/jobs", Group: "crawler"},
		{Method: "GET", Path: "/api/crawler/jobs/stream", Group: "crawler"},
		{Method: "GET", Path: "/api/crawler/detail-loop", Group: "crawler"},
		{Method: "POST", Path: "/api/crawler/detail-loop/start", Group: "crawler"},
		{Method: "POST", Path: "/api/crawler/detail-loop/stop", Group: "crawler"},
		{Method: "GET", Path: "/api/crawler/detail-loop/stream", Group: "crawler"},
		{Method: "GET", Path: "/api/crawler/jobs/:jobID", Group: "crawler"},
		{Method: "GET", Path: "/api/crawler/jobs/:jobID/events", Group: "crawler"},
		{Method: "GET", Path: "/api/crawler/jobs/:jobID/stream", Group: "crawler"},
		{Method: "POST", Path: "/api/crawler/jobs/:jobID/pause", Group: "crawler"},
		{Method: "POST", Path: "/api/crawler/jobs/:jobID/resume", Group: "crawler"},
		{Method: "POST", Path: "/api/crawler/jobs/:jobID/stop", Group: "crawler"},
	}
}

func LegacyPageRoutes() []LegacyRoute {
	return []LegacyRoute{
		{Method: "GET", Path: "/cards", Group: "cards"},
		{Method: "GET", Path: "/cardstoday", Group: "cards"},
		{Method: "GET", Path: "/cardshasrank", Group: "cards"},
		{Method: "GET", Path: "/cardsmediamowned", Group: "cards"},
		{Method: "GET", Path: "/cardsneeddownload", Group: "cards"},
		{Method: "GET", Path: "/moviecarddayrank", Group: "rank"},
		{Method: "GET", Path: "/moviecardperiodrank", Group: "rank"},
		{Method: "GET", Path: "/movie/:movie", Group: "movie"},
		{Method: "GET", Path: "/cardsrandom", Group: "cards"},
		{Method: "GET", Path: "/records", Group: "record"},
		{Method: "GET", Path: "/crawl-records", Group: "crawler"},
		{Method: "GET", Path: "/sc-events", Group: "sc"},
		{Method: "GET", Path: "/sc-events-cards", Group: "sc"},
		{Method: "GET", Path: "/sc-events/:name", Group: "sc"},
		{Method: "GET", Path: "/casts", Group: "cast"},
		{Method: "GET", Path: "/cast", Group: "cast"},
		{Method: "GET", Path: "/cast/:id", Group: "cast"},
		{Method: "GET", Path: "/medias", Group: "media"},
		{Method: "GET", Path: "/w-agg-events", Group: "agg"},
		{Method: "GET", Path: "/e-items", Group: "admin"},
		{Method: "GET", Path: "/torrent-albums", Group: "album"},
		{Method: "GET", Path: "/movie-albums", Group: "album"},
		{Method: "GET", Path: "/d-seeds", Group: "seed"},
		{Method: "GET", Path: "/fetch-site-javbus-list", Group: "fetch-site"},
		{Method: "GET", Path: "/fetch-site-sukebei-list", Group: "fetch-site"},
		{Method: "GET", Path: "/fetch-site-sehuatang-list", Group: "fetch-site"},
		{Method: "GET", Path: "/wdir", Group: "wdir"},
		{Method: "GET", Path: "/triggers", Group: "trigger"},
		{Method: "GET", Path: "/triggers/dailybest", Group: "trigger"},
		{Method: "GET", Path: "/triggers/seeds", Group: "trigger"},
		{Method: "GET", Path: "/triggers/post-process", Group: "trigger"},
		{Method: "GET", Path: "/triggers/media", Group: "media"},
		{Method: "GET", Path: "/triggers/sc-media", Group: "sc-media"},
		{Method: "GET", Path: "/triggers/media-rollback", Group: "media"},
		{Method: "GET", Path: "/triggers/media-rescan", Group: "media"},
		{Method: "GET", Path: "/triggers/agg", Group: "agg"},
		{Method: "GET", Path: "/triggers/fetch-site", Group: "fetch-site"},
		{Method: "GET", Path: "/triggers/fetch-site-javbus-filtered", Group: "fetch-site"},
		{Method: "GET", Path: "/triggers/fetch-site-sukebei-filtered", Group: "fetch-site"},
		{Method: "GET", Path: "/triggers/fetch-sehuatang", Group: "fetch-site"},
		{Method: "GET", Path: "/triggers/backfill", Group: "trigger"},
		{Method: "GET", Path: "/crawler/tasks", Group: "crawler"},
		{Method: "GET", Path: "/crawler/detail-loop", Group: "crawler"},
		{Method: "GET", Path: "/triggers/sc", Group: "sc"},
		{Method: "GET", Path: "/sc-pick-smart-media", Group: "sc"},
		{Method: "GET", Path: "/w-media-agg/birth", Group: "agg"},
		{Method: "GET", Path: "/w-media-agg/bucket-list", Group: "agg"},
		{Method: "GET", Path: "/movie-agg-all/release", Group: "agg"},
		{Method: "GET", Path: "/movie-agg-all/release-bucket-list", Group: "agg"},
	}
}
