// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aMovieFieldNames          = builder.RawFieldNames(&AMovie{})
	aMovieRows                = strings.Join(aMovieFieldNames, ",")
	aMovieRowsExpectAutoSet   = strings.Join(stringx.Remove(aMovieFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	aMovieRowsWithPlaceHolder = strings.Join(stringx.Remove(aMovieFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheZeroGcV2BAMovieIdPrefix    = "cache:zeroGcV2B:aMovie:id:"
	cacheZeroGcV2BAMovieJavIdPrefix = "cache:zeroGcV2B:aMovie:javId:"
)

type (
	aMovieModel interface {
		Insert(ctx context.Context, data *AMovie) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AMovie, error)
		FindOneByJavId(ctx context.Context, javId string) (*AMovie, error)
		Update(ctx context.Context, data *AMovie) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAMovieModel struct {
		sqlc.CachedConn
		table string
	}

	AMovie struct {
		Id                   int64   `db:"id"`
		Name                 string  `db:"name"`
		JavId                string  `db:"jav_id"`
		Title                string  `db:"title"`
		ReleasingDate        int64   `db:"releasing_date"`
		Length               int64   `db:"length"`
		Score                int64   `db:"score"`
		ViewersNumberWant    int64   `db:"viewers_number_want"`
		ViewersNumberOwned   int64   `db:"viewers_number_owned"`
		ViewersNumberWatched int64   `db:"viewers_number_watched"`
		PrefixId             int64   `db:"prefix_id"`
		MakerId              int64   `db:"maker_id"`
		LabelId              int64   `db:"label_id"`
		DirectorId           int64   `db:"director_id"`
		CastNumber           int64   `db:"cast_number"`
		LastQueryJavTime     int64   `db:"last_query_jav_time"`
		DetailBirthTime      int64   `db:"detail_birth_time"`
		CastAverageAge       float64 `db:"cast_average_age"`
		FilmBirthTime        int64   `db:"film_birth_time"`
		HasChinese           int64   `db:"has_chinese"`
		Chinese              string  `db:"chinese"`
		FirstRankDayNumber   int64   `db:"first_rank_day_number"`
		HasDownloadedCover   int64   `db:"has_downloaded_cover"`
		NeedDownload         int64   `db:"need_download"`
		CreatedOn            int64   `db:"created_on"`
		UpdatedOn            int64   `db:"updated_on"`
		MovieOwned           int64   `db:"movie_owned"`
		EncodeName           string  `db:"encode_name"`
		ScTimes              int64   `db:"sc_times"`
		LastScTime           int64   `db:"last_sc_time"`
		ComeTimes            int64   `db:"come_times"`
		HighestRank          int64   `db:"highest_rank"`
		DaysInRank           int64   `db:"days_in_rank"`
	}
)

func newAMovieModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAMovieModel {
	return &defaultAMovieModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`a_movie`",
	}
}

func (m *defaultAMovieModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	zeroGcV2BAMovieIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BAMovieIdPrefix, id)
	zeroGcV2BAMovieJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BAMovieJavIdPrefix, data.JavId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, zeroGcV2BAMovieIdKey, zeroGcV2BAMovieJavIdKey)
	return err
}

func (m *defaultAMovieModel) FindOne(ctx context.Context, id int64) (*AMovie, error) {
	zeroGcV2BAMovieIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BAMovieIdPrefix, id)
	var resp AMovie
	err := m.QueryRowCtx(ctx, &resp, zeroGcV2BAMovieIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", aMovieRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAMovieModel) FindOneByJavId(ctx context.Context, javId string) (*AMovie, error) {
	zeroGcV2BAMovieJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BAMovieJavIdPrefix, javId)
	var resp AMovie
	err := m.QueryRowIndexCtx(ctx, &resp, zeroGcV2BAMovieJavIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `jav_id` = ? limit 1", aMovieRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, javId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAMovieModel) Insert(ctx context.Context, data *AMovie) (sql.Result, error) {
	zeroGcV2BAMovieIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BAMovieIdPrefix, data.Id)
	zeroGcV2BAMovieJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BAMovieJavIdPrefix, data.JavId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, aMovieRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.JavId, data.Title, data.ReleasingDate, data.Length, data.Score, data.ViewersNumberWant, data.ViewersNumberOwned, data.ViewersNumberWatched, data.PrefixId, data.MakerId, data.LabelId, data.DirectorId, data.CastNumber, data.LastQueryJavTime, data.DetailBirthTime, data.CastAverageAge, data.FilmBirthTime, data.HasChinese, data.Chinese, data.FirstRankDayNumber, data.HasDownloadedCover, data.NeedDownload, data.CreatedOn, data.UpdatedOn, data.MovieOwned, data.EncodeName, data.ScTimes, data.LastScTime, data.ComeTimes, data.HighestRank, data.DaysInRank)
	}, zeroGcV2BAMovieIdKey, zeroGcV2BAMovieJavIdKey)
	return ret, err
}

func (m *defaultAMovieModel) Update(ctx context.Context, newData *AMovie) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	zeroGcV2BAMovieIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BAMovieIdPrefix, data.Id)
	zeroGcV2BAMovieJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BAMovieJavIdPrefix, data.JavId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, aMovieRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.JavId, newData.Title, newData.ReleasingDate, newData.Length, newData.Score, newData.ViewersNumberWant, newData.ViewersNumberOwned, newData.ViewersNumberWatched, newData.PrefixId, newData.MakerId, newData.LabelId, newData.DirectorId, newData.CastNumber, newData.LastQueryJavTime, newData.DetailBirthTime, newData.CastAverageAge, newData.FilmBirthTime, newData.HasChinese, newData.Chinese, newData.FirstRankDayNumber, newData.HasDownloadedCover, newData.NeedDownload, newData.CreatedOn, newData.UpdatedOn, newData.MovieOwned, newData.EncodeName, newData.ScTimes, newData.LastScTime, newData.ComeTimes, newData.HighestRank, newData.DaysInRank, newData.Id)
	}, zeroGcV2BAMovieIdKey, zeroGcV2BAMovieJavIdKey)
	return err
}

func (m *defaultAMovieModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheZeroGcV2BAMovieIdPrefix, primary)
}

func (m *defaultAMovieModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", aMovieRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAMovieModel) tableName() string {
	return m.table
}
