// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bmCastFieldNames          = builder.RawFieldNames(&BmCast{})
	bmCastRows                = strings.Join(bmCastFieldNames, ",")
	bmCastRowsExpectAutoSet   = strings.Join(stringx.Remove(bmCastFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	bmCastRowsWithPlaceHolder = strings.Join(stringx.Remove(bmCastFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheZeroGcV2BBmCastIdPrefix   = "cache:zeroGcV2B:bmCast:id:"
	cacheZeroGcV2BBmCastNamePrefix = "cache:zeroGcV2B:bmCast:name:"
)

type (
	bmCastModel interface {
		Insert(ctx context.Context, data *BmCast) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BmCast, error)
		FindOneByName(ctx context.Context, name string) (*BmCast, error)
		Update(ctx context.Context, data *BmCast) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBmCastModel struct {
		sqlc.CachedConn
		table string
	}

	BmCast struct {
		Id                 int64  `db:"id"`
		Name               string `db:"name"`
		JavId              string `db:"jav_id"`
		MovieNumber        int64  `db:"movie_number"`
		OwnedMovieNumber   int64  `db:"owned_movie_number"`
		CreatedOn          int64  `db:"created_on"`
		UpdatedOn          int64  `db:"updated_on"`
		ScTimes            int64  `db:"sc_times"`
		ComeTimes          int64  `db:"come_times"`
		LastScTime         int64  `db:"last_sc_time"`
		Rank500MovieNumber int64  `db:"rank500_movie_number"`
		Rank20MovieNumber  int64  `db:"rank20_movie_number"`
		Rank1MovieNumber   int64  `db:"rank1_movie_number"`
		HighestRank        int64  `db:"highest_rank"`
		RankTimes          int64  `db:"rank_times"`
	}
)

func newBmCastModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultBmCastModel {
	return &defaultBmCastModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`bm_cast`",
	}
}

func (m *defaultBmCastModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	zeroGcV2BBmCastIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmCastIdPrefix, id)
	zeroGcV2BBmCastNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmCastNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, zeroGcV2BBmCastIdKey, zeroGcV2BBmCastNameKey)
	return err
}

func (m *defaultBmCastModel) FindOne(ctx context.Context, id int64) (*BmCast, error) {
	zeroGcV2BBmCastIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmCastIdPrefix, id)
	var resp BmCast
	err := m.QueryRowCtx(ctx, &resp, zeroGcV2BBmCastIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bmCastRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmCastModel) FindOneByName(ctx context.Context, name string) (*BmCast, error) {
	zeroGcV2BBmCastNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmCastNamePrefix, name)
	var resp BmCast
	err := m.QueryRowIndexCtx(ctx, &resp, zeroGcV2BBmCastNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", bmCastRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmCastModel) Insert(ctx context.Context, data *BmCast) (sql.Result, error) {
	zeroGcV2BBmCastIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmCastIdPrefix, data.Id)
	zeroGcV2BBmCastNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmCastNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, bmCastRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.JavId, data.MovieNumber, data.OwnedMovieNumber, data.CreatedOn, data.UpdatedOn, data.ScTimes, data.ComeTimes, data.LastScTime, data.Rank500MovieNumber, data.Rank20MovieNumber, data.Rank1MovieNumber, data.HighestRank, data.RankTimes)
	}, zeroGcV2BBmCastIdKey, zeroGcV2BBmCastNameKey)
	return ret, err
}

func (m *defaultBmCastModel) Update(ctx context.Context, newData *BmCast) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	zeroGcV2BBmCastIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmCastIdPrefix, data.Id)
	zeroGcV2BBmCastNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmCastNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, bmCastRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.JavId, newData.MovieNumber, newData.OwnedMovieNumber, newData.CreatedOn, newData.UpdatedOn, newData.ScTimes, newData.ComeTimes, newData.LastScTime, newData.Rank500MovieNumber, newData.Rank20MovieNumber, newData.Rank1MovieNumber, newData.HighestRank, newData.RankTimes, newData.Id)
	}, zeroGcV2BBmCastIdKey, zeroGcV2BBmCastNameKey)
	return err
}

func (m *defaultBmCastModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheZeroGcV2BBmCastIdPrefix, primary)
}

func (m *defaultBmCastModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bmCastRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBmCastModel) tableName() string {
	return m.table
}
