// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bmDirectorFieldNames          = builder.RawFieldNames(&BmDirector{})
	bmDirectorRows                = strings.Join(bmDirectorFieldNames, ",")
	bmDirectorRowsExpectAutoSet   = strings.Join(stringx.Remove(bmDirectorFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	bmDirectorRowsWithPlaceHolder = strings.Join(stringx.Remove(bmDirectorFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheZeroGcV2BBmDirectorIdPrefix    = "cache:zeroGcV2B:bmDirector:id:"
	cacheZeroGcV2BBmDirectorJavIdPrefix = "cache:zeroGcV2B:bmDirector:javId:"
	cacheZeroGcV2BBmDirectorNamePrefix  = "cache:zeroGcV2B:bmDirector:name:"
)

type (
	bmDirectorModel interface {
		Insert(ctx context.Context, data *BmDirector) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BmDirector, error)
		FindOneByJavId(ctx context.Context, javId string) (*BmDirector, error)
		FindOneByName(ctx context.Context, name string) (*BmDirector, error)
		Update(ctx context.Context, data *BmDirector) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBmDirectorModel struct {
		sqlc.CachedConn
		table string
	}

	BmDirector struct {
		Id               int64  `db:"id"`
		Name             string `db:"name"`
		JavId            string `db:"jav_id"`
		MovieNumber      int64  `db:"movie_number"`
		OwnedMovieNumber int64  `db:"owned_movie_number"`
		CreatedOn        int64  `db:"created_on"`
		UpdatedOn        int64  `db:"updated_on"`
	}
)

func newBmDirectorModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultBmDirectorModel {
	return &defaultBmDirectorModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`bm_director`",
	}
}

func (m *defaultBmDirectorModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	zeroGcV2BBmDirectorIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmDirectorIdPrefix, id)
	zeroGcV2BBmDirectorJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmDirectorJavIdPrefix, data.JavId)
	zeroGcV2BBmDirectorNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmDirectorNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, zeroGcV2BBmDirectorIdKey, zeroGcV2BBmDirectorJavIdKey, zeroGcV2BBmDirectorNameKey)
	return err
}

func (m *defaultBmDirectorModel) FindOne(ctx context.Context, id int64) (*BmDirector, error) {
	zeroGcV2BBmDirectorIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmDirectorIdPrefix, id)
	var resp BmDirector
	err := m.QueryRowCtx(ctx, &resp, zeroGcV2BBmDirectorIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bmDirectorRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmDirectorModel) FindOneByJavId(ctx context.Context, javId string) (*BmDirector, error) {
	zeroGcV2BBmDirectorJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmDirectorJavIdPrefix, javId)
	var resp BmDirector
	err := m.QueryRowIndexCtx(ctx, &resp, zeroGcV2BBmDirectorJavIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `jav_id` = ? limit 1", bmDirectorRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, javId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmDirectorModel) FindOneByName(ctx context.Context, name string) (*BmDirector, error) {
	zeroGcV2BBmDirectorNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmDirectorNamePrefix, name)
	var resp BmDirector
	err := m.QueryRowIndexCtx(ctx, &resp, zeroGcV2BBmDirectorNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", bmDirectorRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmDirectorModel) Insert(ctx context.Context, data *BmDirector) (sql.Result, error) {
	zeroGcV2BBmDirectorIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmDirectorIdPrefix, data.Id)
	zeroGcV2BBmDirectorJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmDirectorJavIdPrefix, data.JavId)
	zeroGcV2BBmDirectorNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmDirectorNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, bmDirectorRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.JavId, data.MovieNumber, data.OwnedMovieNumber, data.CreatedOn, data.UpdatedOn)
	}, zeroGcV2BBmDirectorIdKey, zeroGcV2BBmDirectorJavIdKey, zeroGcV2BBmDirectorNameKey)
	return ret, err
}

func (m *defaultBmDirectorModel) Update(ctx context.Context, newData *BmDirector) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	zeroGcV2BBmDirectorIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmDirectorIdPrefix, data.Id)
	zeroGcV2BBmDirectorJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmDirectorJavIdPrefix, data.JavId)
	zeroGcV2BBmDirectorNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmDirectorNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, bmDirectorRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.JavId, newData.MovieNumber, newData.OwnedMovieNumber, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, zeroGcV2BBmDirectorIdKey, zeroGcV2BBmDirectorJavIdKey, zeroGcV2BBmDirectorNameKey)
	return err
}

func (m *defaultBmDirectorModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheZeroGcV2BBmDirectorIdPrefix, primary)
}

func (m *defaultBmDirectorModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bmDirectorRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBmDirectorModel) tableName() string {
	return m.table
}
