// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bmGenreFieldNames          = builder.RawFieldNames(&BmGenre{})
	bmGenreRows                = strings.Join(bmGenreFieldNames, ",")
	bmGenreRowsExpectAutoSet   = strings.Join(stringx.Remove(bmGenreFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	bmGenreRowsWithPlaceHolder = strings.Join(stringx.Remove(bmGenreFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheZeroGcV2BBmGenreIdPrefix    = "cache:zeroGcV2B:bmGenre:id:"
	cacheZeroGcV2BBmGenreJavIdPrefix = "cache:zeroGcV2B:bmGenre:javId:"
	cacheZeroGcV2BBmGenreNamePrefix  = "cache:zeroGcV2B:bmGenre:name:"
)

type (
	bmGenreModel interface {
		Insert(ctx context.Context, data *BmGenre) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BmGenre, error)
		FindOneByJavId(ctx context.Context, javId string) (*BmGenre, error)
		FindOneByName(ctx context.Context, name string) (*BmGenre, error)
		Update(ctx context.Context, data *BmGenre) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBmGenreModel struct {
		sqlc.CachedConn
		table string
	}

	BmGenre struct {
		Id               int64  `db:"id"`
		Name             string `db:"name"`
		JavId            string `db:"jav_id"`
		MovieNumber      int64  `db:"movie_number"`
		OwnedMovieNumber int64  `db:"owned_movie_number"`
		CreatedOn        int64  `db:"created_on"`
		UpdatedOn        int64  `db:"updated_on"`
	}
)

func newBmGenreModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultBmGenreModel {
	return &defaultBmGenreModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`bm_genre`",
	}
}

func (m *defaultBmGenreModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	zeroGcV2BBmGenreIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmGenreIdPrefix, id)
	zeroGcV2BBmGenreJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmGenreJavIdPrefix, data.JavId)
	zeroGcV2BBmGenreNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmGenreNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, zeroGcV2BBmGenreIdKey, zeroGcV2BBmGenreJavIdKey, zeroGcV2BBmGenreNameKey)
	return err
}

func (m *defaultBmGenreModel) FindOne(ctx context.Context, id int64) (*BmGenre, error) {
	zeroGcV2BBmGenreIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmGenreIdPrefix, id)
	var resp BmGenre
	err := m.QueryRowCtx(ctx, &resp, zeroGcV2BBmGenreIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bmGenreRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmGenreModel) FindOneByJavId(ctx context.Context, javId string) (*BmGenre, error) {
	zeroGcV2BBmGenreJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmGenreJavIdPrefix, javId)
	var resp BmGenre
	err := m.QueryRowIndexCtx(ctx, &resp, zeroGcV2BBmGenreJavIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `jav_id` = ? limit 1", bmGenreRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, javId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmGenreModel) FindOneByName(ctx context.Context, name string) (*BmGenre, error) {
	zeroGcV2BBmGenreNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmGenreNamePrefix, name)
	var resp BmGenre
	err := m.QueryRowIndexCtx(ctx, &resp, zeroGcV2BBmGenreNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", bmGenreRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmGenreModel) Insert(ctx context.Context, data *BmGenre) (sql.Result, error) {
	zeroGcV2BBmGenreIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmGenreIdPrefix, data.Id)
	zeroGcV2BBmGenreJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmGenreJavIdPrefix, data.JavId)
	zeroGcV2BBmGenreNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmGenreNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, bmGenreRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.JavId, data.MovieNumber, data.OwnedMovieNumber, data.CreatedOn, data.UpdatedOn)
	}, zeroGcV2BBmGenreIdKey, zeroGcV2BBmGenreJavIdKey, zeroGcV2BBmGenreNameKey)
	return ret, err
}

func (m *defaultBmGenreModel) Update(ctx context.Context, newData *BmGenre) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	zeroGcV2BBmGenreIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmGenreIdPrefix, data.Id)
	zeroGcV2BBmGenreJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmGenreJavIdPrefix, data.JavId)
	zeroGcV2BBmGenreNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmGenreNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, bmGenreRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.JavId, newData.MovieNumber, newData.OwnedMovieNumber, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, zeroGcV2BBmGenreIdKey, zeroGcV2BBmGenreJavIdKey, zeroGcV2BBmGenreNameKey)
	return err
}

func (m *defaultBmGenreModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheZeroGcV2BBmGenreIdPrefix, primary)
}

func (m *defaultBmGenreModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bmGenreRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBmGenreModel) tableName() string {
	return m.table
}
