// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bmLabelFieldNames          = builder.RawFieldNames(&BmLabel{})
	bmLabelRows                = strings.Join(bmLabelFieldNames, ",")
	bmLabelRowsExpectAutoSet   = strings.Join(stringx.Remove(bmLabelFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	bmLabelRowsWithPlaceHolder = strings.Join(stringx.Remove(bmLabelFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheZeroGcV2BBmLabelIdPrefix    = "cache:zeroGcV2B:bmLabel:id:"
	cacheZeroGcV2BBmLabelJavIdPrefix = "cache:zeroGcV2B:bmLabel:javId:"
	cacheZeroGcV2BBmLabelNamePrefix  = "cache:zeroGcV2B:bmLabel:name:"
)

type (
	bmLabelModel interface {
		Insert(ctx context.Context, data *BmLabel) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BmLabel, error)
		FindOneByJavId(ctx context.Context, javId string) (*BmLabel, error)
		FindOneByName(ctx context.Context, name string) (*BmLabel, error)
		Update(ctx context.Context, data *BmLabel) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBmLabelModel struct {
		sqlc.CachedConn
		table string
	}

	BmLabel struct {
		Id               int64  `db:"id"`
		Name             string `db:"name"`
		JavId            string `db:"jav_id"`
		MovieNumber      int64  `db:"movie_number"`
		OwnedMovieNumber int64  `db:"owned_movie_number"`
		CreatedOn        int64  `db:"created_on"`
		UpdatedOn        int64  `db:"updated_on"`
	}
)

func newBmLabelModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultBmLabelModel {
	return &defaultBmLabelModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`bm_label`",
	}
}

func (m *defaultBmLabelModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	zeroGcV2BBmLabelIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmLabelIdPrefix, id)
	zeroGcV2BBmLabelJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmLabelJavIdPrefix, data.JavId)
	zeroGcV2BBmLabelNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmLabelNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, zeroGcV2BBmLabelIdKey, zeroGcV2BBmLabelJavIdKey, zeroGcV2BBmLabelNameKey)
	return err
}

func (m *defaultBmLabelModel) FindOne(ctx context.Context, id int64) (*BmLabel, error) {
	zeroGcV2BBmLabelIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmLabelIdPrefix, id)
	var resp BmLabel
	err := m.QueryRowCtx(ctx, &resp, zeroGcV2BBmLabelIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bmLabelRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmLabelModel) FindOneByJavId(ctx context.Context, javId string) (*BmLabel, error) {
	zeroGcV2BBmLabelJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmLabelJavIdPrefix, javId)
	var resp BmLabel
	err := m.QueryRowIndexCtx(ctx, &resp, zeroGcV2BBmLabelJavIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `jav_id` = ? limit 1", bmLabelRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, javId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmLabelModel) FindOneByName(ctx context.Context, name string) (*BmLabel, error) {
	zeroGcV2BBmLabelNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmLabelNamePrefix, name)
	var resp BmLabel
	err := m.QueryRowIndexCtx(ctx, &resp, zeroGcV2BBmLabelNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", bmLabelRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmLabelModel) Insert(ctx context.Context, data *BmLabel) (sql.Result, error) {
	zeroGcV2BBmLabelIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmLabelIdPrefix, data.Id)
	zeroGcV2BBmLabelJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmLabelJavIdPrefix, data.JavId)
	zeroGcV2BBmLabelNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmLabelNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, bmLabelRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.JavId, data.MovieNumber, data.OwnedMovieNumber, data.CreatedOn, data.UpdatedOn)
	}, zeroGcV2BBmLabelIdKey, zeroGcV2BBmLabelJavIdKey, zeroGcV2BBmLabelNameKey)
	return ret, err
}

func (m *defaultBmLabelModel) Update(ctx context.Context, newData *BmLabel) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	zeroGcV2BBmLabelIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmLabelIdPrefix, data.Id)
	zeroGcV2BBmLabelJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmLabelJavIdPrefix, data.JavId)
	zeroGcV2BBmLabelNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmLabelNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, bmLabelRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.JavId, newData.MovieNumber, newData.OwnedMovieNumber, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, zeroGcV2BBmLabelIdKey, zeroGcV2BBmLabelJavIdKey, zeroGcV2BBmLabelNameKey)
	return err
}

func (m *defaultBmLabelModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheZeroGcV2BBmLabelIdPrefix, primary)
}

func (m *defaultBmLabelModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bmLabelRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBmLabelModel) tableName() string {
	return m.table
}
