// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bmMakerFieldNames          = builder.RawFieldNames(&BmMaker{})
	bmMakerRows                = strings.Join(bmMakerFieldNames, ",")
	bmMakerRowsExpectAutoSet   = strings.Join(stringx.Remove(bmMakerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	bmMakerRowsWithPlaceHolder = strings.Join(stringx.Remove(bmMakerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheZeroGcV2BBmMakerIdPrefix    = "cache:zeroGcV2B:bmMaker:id:"
	cacheZeroGcV2BBmMakerJavIdPrefix = "cache:zeroGcV2B:bmMaker:javId:"
	cacheZeroGcV2BBmMakerNamePrefix  = "cache:zeroGcV2B:bmMaker:name:"
)

type (
	bmMakerModel interface {
		Insert(ctx context.Context, data *BmMaker) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BmMaker, error)
		FindOneByJavId(ctx context.Context, javId string) (*BmMaker, error)
		FindOneByName(ctx context.Context, name string) (*BmMaker, error)
		Update(ctx context.Context, data *BmMaker) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBmMakerModel struct {
		sqlc.CachedConn
		table string
	}

	BmMaker struct {
		Id               int64  `db:"id"`
		Name             string `db:"name"`
		JavId            string `db:"jav_id"`
		MovieNumber      int64  `db:"movie_number"`
		OwnedMovieNumber int64  `db:"owned_movie_number"`
		CreatedOn        int64  `db:"created_on"`
		UpdatedOn        int64  `db:"updated_on"`
	}
)

func newBmMakerModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultBmMakerModel {
	return &defaultBmMakerModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`bm_maker`",
	}
}

func (m *defaultBmMakerModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	zeroGcV2BBmMakerIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmMakerIdPrefix, id)
	zeroGcV2BBmMakerJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmMakerJavIdPrefix, data.JavId)
	zeroGcV2BBmMakerNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmMakerNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, zeroGcV2BBmMakerIdKey, zeroGcV2BBmMakerJavIdKey, zeroGcV2BBmMakerNameKey)
	return err
}

func (m *defaultBmMakerModel) FindOne(ctx context.Context, id int64) (*BmMaker, error) {
	zeroGcV2BBmMakerIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmMakerIdPrefix, id)
	var resp BmMaker
	err := m.QueryRowCtx(ctx, &resp, zeroGcV2BBmMakerIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bmMakerRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmMakerModel) FindOneByJavId(ctx context.Context, javId string) (*BmMaker, error) {
	zeroGcV2BBmMakerJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmMakerJavIdPrefix, javId)
	var resp BmMaker
	err := m.QueryRowIndexCtx(ctx, &resp, zeroGcV2BBmMakerJavIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `jav_id` = ? limit 1", bmMakerRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, javId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmMakerModel) FindOneByName(ctx context.Context, name string) (*BmMaker, error) {
	zeroGcV2BBmMakerNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmMakerNamePrefix, name)
	var resp BmMaker
	err := m.QueryRowIndexCtx(ctx, &resp, zeroGcV2BBmMakerNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", bmMakerRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmMakerModel) Insert(ctx context.Context, data *BmMaker) (sql.Result, error) {
	zeroGcV2BBmMakerIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmMakerIdPrefix, data.Id)
	zeroGcV2BBmMakerJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmMakerJavIdPrefix, data.JavId)
	zeroGcV2BBmMakerNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmMakerNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, bmMakerRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.JavId, data.MovieNumber, data.OwnedMovieNumber, data.CreatedOn, data.UpdatedOn)
	}, zeroGcV2BBmMakerIdKey, zeroGcV2BBmMakerJavIdKey, zeroGcV2BBmMakerNameKey)
	return ret, err
}

func (m *defaultBmMakerModel) Update(ctx context.Context, newData *BmMaker) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	zeroGcV2BBmMakerIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmMakerIdPrefix, data.Id)
	zeroGcV2BBmMakerJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmMakerJavIdPrefix, data.JavId)
	zeroGcV2BBmMakerNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmMakerNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, bmMakerRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.JavId, newData.MovieNumber, newData.OwnedMovieNumber, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, zeroGcV2BBmMakerIdKey, zeroGcV2BBmMakerJavIdKey, zeroGcV2BBmMakerNameKey)
	return err
}

func (m *defaultBmMakerModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheZeroGcV2BBmMakerIdPrefix, primary)
}

func (m *defaultBmMakerModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bmMakerRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBmMakerModel) tableName() string {
	return m.table
}
