// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bmMurlFieldNames          = builder.RawFieldNames(&BmMurl{})
	bmMurlRows                = strings.Join(bmMurlFieldNames, ",")
	bmMurlRowsExpectAutoSet   = strings.Join(stringx.Remove(bmMurlFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	bmMurlRowsWithPlaceHolder = strings.Join(stringx.Remove(bmMurlFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheZeroGcV2BBmMurlIdPrefix    = "cache:zeroGcV2B:bmMurl:id:"
	cacheZeroGcV2BBmMurlJavIdPrefix = "cache:zeroGcV2B:bmMurl:javId:"
)

type (
	bmMurlModel interface {
		Insert(ctx context.Context, data *BmMurl) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BmMurl, error)
		FindOneByJavId(ctx context.Context, javId string) (*BmMurl, error)
		Update(ctx context.Context, data *BmMurl) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBmMurlModel struct {
		sqlc.CachedConn
		table string
	}

	BmMurl struct {
		Id             int64  `db:"id"`
		MurlName       string `db:"murl_name"`
		JavId          string `db:"jav_id"`
		JacketImg      string `db:"jacket_img"`
		JacketImgLocal string `db:"jacket_img_local"`
		SmallImg       string `db:"small_img"`
		SmallImgLocal  string `db:"small_img_local"`
		FilmUrl        string `db:"film_url"`
		EncodeName     string `db:"encode_name"`
		CreatedOn      int64  `db:"created_on"`
		UpdatedOn      int64  `db:"updated_on"`
	}
)

func newBmMurlModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultBmMurlModel {
	return &defaultBmMurlModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`bm_murl`",
	}
}

func (m *defaultBmMurlModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	zeroGcV2BBmMurlIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmMurlIdPrefix, id)
	zeroGcV2BBmMurlJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmMurlJavIdPrefix, data.JavId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, zeroGcV2BBmMurlIdKey, zeroGcV2BBmMurlJavIdKey)
	return err
}

func (m *defaultBmMurlModel) FindOne(ctx context.Context, id int64) (*BmMurl, error) {
	zeroGcV2BBmMurlIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmMurlIdPrefix, id)
	var resp BmMurl
	err := m.QueryRowCtx(ctx, &resp, zeroGcV2BBmMurlIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bmMurlRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmMurlModel) FindOneByJavId(ctx context.Context, javId string) (*BmMurl, error) {
	zeroGcV2BBmMurlJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmMurlJavIdPrefix, javId)
	var resp BmMurl
	err := m.QueryRowIndexCtx(ctx, &resp, zeroGcV2BBmMurlJavIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `jav_id` = ? limit 1", bmMurlRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, javId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmMurlModel) Insert(ctx context.Context, data *BmMurl) (sql.Result, error) {
	zeroGcV2BBmMurlIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmMurlIdPrefix, data.Id)
	zeroGcV2BBmMurlJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmMurlJavIdPrefix, data.JavId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, bmMurlRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MurlName, data.JavId, data.JacketImg, data.JacketImgLocal, data.SmallImg, data.SmallImgLocal, data.FilmUrl, data.EncodeName, data.CreatedOn, data.UpdatedOn)
	}, zeroGcV2BBmMurlIdKey, zeroGcV2BBmMurlJavIdKey)
	return ret, err
}

func (m *defaultBmMurlModel) Update(ctx context.Context, newData *BmMurl) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	zeroGcV2BBmMurlIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmMurlIdPrefix, data.Id)
	zeroGcV2BBmMurlJavIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmMurlJavIdPrefix, data.JavId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, bmMurlRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MurlName, newData.JavId, newData.JacketImg, newData.JacketImgLocal, newData.SmallImg, newData.SmallImgLocal, newData.FilmUrl, newData.EncodeName, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, zeroGcV2BBmMurlIdKey, zeroGcV2BBmMurlJavIdKey)
	return err
}

func (m *defaultBmMurlModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheZeroGcV2BBmMurlIdPrefix, primary)
}

func (m *defaultBmMurlModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bmMurlRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBmMurlModel) tableName() string {
	return m.table
}
