// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bmPrefixFieldNames          = builder.RawFieldNames(&BmPrefix{})
	bmPrefixRows                = strings.Join(bmPrefixFieldNames, ",")
	bmPrefixRowsExpectAutoSet   = strings.Join(stringx.Remove(bmPrefixFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	bmPrefixRowsWithPlaceHolder = strings.Join(stringx.Remove(bmPrefixFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheZeroGcV2BBmPrefixIdPrefix   = "cache:zeroGcV2B:bmPrefix:id:"
	cacheZeroGcV2BBmPrefixNamePrefix = "cache:zeroGcV2B:bmPrefix:name:"
)

type (
	bmPrefixModel interface {
		Insert(ctx context.Context, data *BmPrefix) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BmPrefix, error)
		FindOneByName(ctx context.Context, name string) (*BmPrefix, error)
		Update(ctx context.Context, data *BmPrefix) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBmPrefixModel struct {
		sqlc.CachedConn
		table string
	}

	BmPrefix struct {
		Id               int64  `db:"id"`
		Name             string `db:"name"`
		MovieNumber      int64  `db:"movie_number"`
		OwnedMovieNumber int64  `db:"owned_movie_number"`
		CreatedOn        int64  `db:"created_on"`
		UpdatedOn        int64  `db:"updated_on"`
	}
)

func newBmPrefixModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultBmPrefixModel {
	return &defaultBmPrefixModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`bm_prefix`",
	}
}

func (m *defaultBmPrefixModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	zeroGcV2BBmPrefixIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmPrefixIdPrefix, id)
	zeroGcV2BBmPrefixNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmPrefixNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, zeroGcV2BBmPrefixIdKey, zeroGcV2BBmPrefixNameKey)
	return err
}

func (m *defaultBmPrefixModel) FindOne(ctx context.Context, id int64) (*BmPrefix, error) {
	zeroGcV2BBmPrefixIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmPrefixIdPrefix, id)
	var resp BmPrefix
	err := m.QueryRowCtx(ctx, &resp, zeroGcV2BBmPrefixIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bmPrefixRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmPrefixModel) FindOneByName(ctx context.Context, name string) (*BmPrefix, error) {
	zeroGcV2BBmPrefixNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmPrefixNamePrefix, name)
	var resp BmPrefix
	err := m.QueryRowIndexCtx(ctx, &resp, zeroGcV2BBmPrefixNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", bmPrefixRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmPrefixModel) Insert(ctx context.Context, data *BmPrefix) (sql.Result, error) {
	zeroGcV2BBmPrefixIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmPrefixIdPrefix, data.Id)
	zeroGcV2BBmPrefixNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmPrefixNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, bmPrefixRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.MovieNumber, data.OwnedMovieNumber, data.CreatedOn, data.UpdatedOn)
	}, zeroGcV2BBmPrefixIdKey, zeroGcV2BBmPrefixNameKey)
	return ret, err
}

func (m *defaultBmPrefixModel) Update(ctx context.Context, newData *BmPrefix) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	zeroGcV2BBmPrefixIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmPrefixIdPrefix, data.Id)
	zeroGcV2BBmPrefixNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmPrefixNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, bmPrefixRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.MovieNumber, newData.OwnedMovieNumber, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, zeroGcV2BBmPrefixIdKey, zeroGcV2BBmPrefixNameKey)
	return err
}

func (m *defaultBmPrefixModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheZeroGcV2BBmPrefixIdPrefix, primary)
}

func (m *defaultBmPrefixModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bmPrefixRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBmPrefixModel) tableName() string {
	return m.table
}
