// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bmrMovieCastFieldNames          = builder.RawFieldNames(&BmrMovieCast{})
	bmrMovieCastRows                = strings.Join(bmrMovieCastFieldNames, ",")
	bmrMovieCastRowsExpectAutoSet   = strings.Join(stringx.Remove(bmrMovieCastFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	bmrMovieCastRowsWithPlaceHolder = strings.Join(stringx.Remove(bmrMovieCastFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheZeroGcV2BBmrMovieCastIdPrefix            = "cache:zeroGcV2B:bmrMovieCast:id:"
	cacheZeroGcV2BBmrMovieCastMovieIdCastIdPrefix = "cache:zeroGcV2B:bmrMovieCast:movieId:castId:"
)

type (
	bmrMovieCastModel interface {
		Insert(ctx context.Context, data *BmrMovieCast) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BmrMovieCast, error)
		FindOneByMovieIdCastId(ctx context.Context, movieId int64, castId int64) (*BmrMovieCast, error)
		Update(ctx context.Context, data *BmrMovieCast) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBmrMovieCastModel struct {
		sqlc.CachedConn
		table string
	}

	BmrMovieCast struct {
		Id        int64 `db:"id"`
		MovieId   int64 `db:"movie_id"`
		CastId    int64 `db:"cast_id"`
		CreatedOn int64 `db:"created_on"`
		UpdatedOn int64 `db:"updated_on"`
	}
)

func newBmrMovieCastModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultBmrMovieCastModel {
	return &defaultBmrMovieCastModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`bmr_movie_cast`",
	}
}

func (m *defaultBmrMovieCastModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	zeroGcV2BBmrMovieCastIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmrMovieCastIdPrefix, id)
	zeroGcV2BBmrMovieCastMovieIdCastIdKey := fmt.Sprintf("%s%v:%v", cacheZeroGcV2BBmrMovieCastMovieIdCastIdPrefix, data.MovieId, data.CastId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, zeroGcV2BBmrMovieCastIdKey, zeroGcV2BBmrMovieCastMovieIdCastIdKey)
	return err
}

func (m *defaultBmrMovieCastModel) FindOne(ctx context.Context, id int64) (*BmrMovieCast, error) {
	zeroGcV2BBmrMovieCastIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmrMovieCastIdPrefix, id)
	var resp BmrMovieCast
	err := m.QueryRowCtx(ctx, &resp, zeroGcV2BBmrMovieCastIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bmrMovieCastRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmrMovieCastModel) FindOneByMovieIdCastId(ctx context.Context, movieId int64, castId int64) (*BmrMovieCast, error) {
	zeroGcV2BBmrMovieCastMovieIdCastIdKey := fmt.Sprintf("%s%v:%v", cacheZeroGcV2BBmrMovieCastMovieIdCastIdPrefix, movieId, castId)
	var resp BmrMovieCast
	err := m.QueryRowIndexCtx(ctx, &resp, zeroGcV2BBmrMovieCastMovieIdCastIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `movie_id` = ? and `cast_id` = ? limit 1", bmrMovieCastRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, movieId, castId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmrMovieCastModel) Insert(ctx context.Context, data *BmrMovieCast) (sql.Result, error) {
	zeroGcV2BBmrMovieCastIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmrMovieCastIdPrefix, data.Id)
	zeroGcV2BBmrMovieCastMovieIdCastIdKey := fmt.Sprintf("%s%v:%v", cacheZeroGcV2BBmrMovieCastMovieIdCastIdPrefix, data.MovieId, data.CastId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, bmrMovieCastRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MovieId, data.CastId, data.CreatedOn, data.UpdatedOn)
	}, zeroGcV2BBmrMovieCastIdKey, zeroGcV2BBmrMovieCastMovieIdCastIdKey)
	return ret, err
}

func (m *defaultBmrMovieCastModel) Update(ctx context.Context, newData *BmrMovieCast) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	zeroGcV2BBmrMovieCastIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmrMovieCastIdPrefix, data.Id)
	zeroGcV2BBmrMovieCastMovieIdCastIdKey := fmt.Sprintf("%s%v:%v", cacheZeroGcV2BBmrMovieCastMovieIdCastIdPrefix, data.MovieId, data.CastId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, bmrMovieCastRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MovieId, newData.CastId, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, zeroGcV2BBmrMovieCastIdKey, zeroGcV2BBmrMovieCastMovieIdCastIdKey)
	return err
}

func (m *defaultBmrMovieCastModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheZeroGcV2BBmrMovieCastIdPrefix, primary)
}

func (m *defaultBmrMovieCastModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bmrMovieCastRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBmrMovieCastModel) tableName() string {
	return m.table
}
