// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bmrMovieGenreFieldNames          = builder.RawFieldNames(&BmrMovieGenre{})
	bmrMovieGenreRows                = strings.Join(bmrMovieGenreFieldNames, ",")
	bmrMovieGenreRowsExpectAutoSet   = strings.Join(stringx.Remove(bmrMovieGenreFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	bmrMovieGenreRowsWithPlaceHolder = strings.Join(stringx.Remove(bmrMovieGenreFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheZeroGcV2BBmrMovieGenreIdPrefix             = "cache:zeroGcV2B:bmrMovieGenre:id:"
	cacheZeroGcV2BBmrMovieGenreMovieIdGenreIdPrefix = "cache:zeroGcV2B:bmrMovieGenre:movieId:genreId:"
)

type (
	bmrMovieGenreModel interface {
		Insert(ctx context.Context, data *BmrMovieGenre) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BmrMovieGenre, error)
		FindOneByMovieIdGenreId(ctx context.Context, movieId int64, genreId int64) (*BmrMovieGenre, error)
		Update(ctx context.Context, data *BmrMovieGenre) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBmrMovieGenreModel struct {
		sqlc.CachedConn
		table string
	}

	BmrMovieGenre struct {
		Id        int64 `db:"id"`
		MovieId   int64 `db:"movie_id"`
		GenreId   int64 `db:"genre_id"`
		CreatedOn int64 `db:"created_on"`
		UpdatedOn int64 `db:"updated_on"`
	}
)

func newBmrMovieGenreModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultBmrMovieGenreModel {
	return &defaultBmrMovieGenreModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`bmr_movie_genre`",
	}
}

func (m *defaultBmrMovieGenreModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	zeroGcV2BBmrMovieGenreIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmrMovieGenreIdPrefix, id)
	zeroGcV2BBmrMovieGenreMovieIdGenreIdKey := fmt.Sprintf("%s%v:%v", cacheZeroGcV2BBmrMovieGenreMovieIdGenreIdPrefix, data.MovieId, data.GenreId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, zeroGcV2BBmrMovieGenreIdKey, zeroGcV2BBmrMovieGenreMovieIdGenreIdKey)
	return err
}

func (m *defaultBmrMovieGenreModel) FindOne(ctx context.Context, id int64) (*BmrMovieGenre, error) {
	zeroGcV2BBmrMovieGenreIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmrMovieGenreIdPrefix, id)
	var resp BmrMovieGenre
	err := m.QueryRowCtx(ctx, &resp, zeroGcV2BBmrMovieGenreIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bmrMovieGenreRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmrMovieGenreModel) FindOneByMovieIdGenreId(ctx context.Context, movieId int64, genreId int64) (*BmrMovieGenre, error) {
	zeroGcV2BBmrMovieGenreMovieIdGenreIdKey := fmt.Sprintf("%s%v:%v", cacheZeroGcV2BBmrMovieGenreMovieIdGenreIdPrefix, movieId, genreId)
	var resp BmrMovieGenre
	err := m.QueryRowIndexCtx(ctx, &resp, zeroGcV2BBmrMovieGenreMovieIdGenreIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `movie_id` = ? and `genre_id` = ? limit 1", bmrMovieGenreRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, movieId, genreId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBmrMovieGenreModel) Insert(ctx context.Context, data *BmrMovieGenre) (sql.Result, error) {
	zeroGcV2BBmrMovieGenreIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmrMovieGenreIdPrefix, data.Id)
	zeroGcV2BBmrMovieGenreMovieIdGenreIdKey := fmt.Sprintf("%s%v:%v", cacheZeroGcV2BBmrMovieGenreMovieIdGenreIdPrefix, data.MovieId, data.GenreId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, bmrMovieGenreRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MovieId, data.GenreId, data.CreatedOn, data.UpdatedOn)
	}, zeroGcV2BBmrMovieGenreIdKey, zeroGcV2BBmrMovieGenreMovieIdGenreIdKey)
	return ret, err
}

func (m *defaultBmrMovieGenreModel) Update(ctx context.Context, newData *BmrMovieGenre) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	zeroGcV2BBmrMovieGenreIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BBmrMovieGenreIdPrefix, data.Id)
	zeroGcV2BBmrMovieGenreMovieIdGenreIdKey := fmt.Sprintf("%s%v:%v", cacheZeroGcV2BBmrMovieGenreMovieIdGenreIdPrefix, data.MovieId, data.GenreId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, bmrMovieGenreRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MovieId, newData.GenreId, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, zeroGcV2BBmrMovieGenreIdKey, zeroGcV2BBmrMovieGenreMovieIdGenreIdKey)
	return err
}

func (m *defaultBmrMovieGenreModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheZeroGcV2BBmrMovieGenreIdPrefix, primary)
}

func (m *defaultBmrMovieGenreModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bmrMovieGenreRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBmrMovieGenreModel) tableName() string {
	return m.table
}
