// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cRankFieldNames          = builder.RawFieldNames(&CRank{})
	cRankRows                = strings.Join(cRankFieldNames, ",")
	cRankRowsExpectAutoSet   = strings.Join(stringx.Remove(cRankFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cRankRowsWithPlaceHolder = strings.Join(stringx.Remove(cRankFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheZeroGcV2BCRankIdPrefix   = "cache:zeroGcV2B:cRank:id:"
	cacheZeroGcV2BCRankNamePrefix = "cache:zeroGcV2B:cRank:name:"
)

type (
	cRankModel interface {
		Insert(ctx context.Context, data *CRank) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CRank, error)
		FindOneByName(ctx context.Context, name string) (*CRank, error)
		Update(ctx context.Context, data *CRank) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCRankModel struct {
		sqlc.CachedConn
		table string
	}

	CRank struct {
		Id         int64  `db:"id"`
		Name       string `db:"name"`
		MovieJavId string `db:"movie_jav_id"`
		DayNumber  int64  `db:"day_number"`
		Number     int64  `db:"number"`
		Category   int64  `db:"category"`
		CreatedOn  int64  `db:"created_on"`
		UpdatedOn  int64  `db:"updated_on"`
	}
)

func newCRankModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCRankModel {
	return &defaultCRankModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`c_rank`",
	}
}

func (m *defaultCRankModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	zeroGcV2BCRankIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BCRankIdPrefix, id)
	zeroGcV2BCRankNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BCRankNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, zeroGcV2BCRankIdKey, zeroGcV2BCRankNameKey)
	return err
}

func (m *defaultCRankModel) FindOne(ctx context.Context, id int64) (*CRank, error) {
	zeroGcV2BCRankIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BCRankIdPrefix, id)
	var resp CRank
	err := m.QueryRowCtx(ctx, &resp, zeroGcV2BCRankIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cRankRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCRankModel) FindOneByName(ctx context.Context, name string) (*CRank, error) {
	zeroGcV2BCRankNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BCRankNamePrefix, name)
	var resp CRank
	err := m.QueryRowIndexCtx(ctx, &resp, zeroGcV2BCRankNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", cRankRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCRankModel) Insert(ctx context.Context, data *CRank) (sql.Result, error) {
	zeroGcV2BCRankIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BCRankIdPrefix, data.Id)
	zeroGcV2BCRankNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BCRankNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, cRankRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.MovieJavId, data.DayNumber, data.Number, data.Category, data.CreatedOn, data.UpdatedOn)
	}, zeroGcV2BCRankIdKey, zeroGcV2BCRankNameKey)
	return ret, err
}

func (m *defaultCRankModel) Update(ctx context.Context, newData *CRank) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	zeroGcV2BCRankIdKey := fmt.Sprintf("%s%v", cacheZeroGcV2BCRankIdPrefix, data.Id)
	zeroGcV2BCRankNameKey := fmt.Sprintf("%s%v", cacheZeroGcV2BCRankNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cRankRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.MovieJavId, newData.DayNumber, newData.Number, newData.Category, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, zeroGcV2BCRankIdKey, zeroGcV2BCRankNameKey)
	return err
}

func (m *defaultCRankModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheZeroGcV2BCRankIdPrefix, primary)
}

func (m *defaultCRankModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cRankRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCRankModel) tableName() string {
	return m.table
}
