// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dQueryFieldNames          = builder.RawFieldNames(&DQuery{})
	dQueryRows                = strings.Join(dQueryFieldNames, ",")
	dQueryRowsExpectAutoSet   = strings.Join(stringx.Remove(dQueryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	dQueryRowsWithPlaceHolder = strings.Join(stringx.Remove(dQueryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	dQueryModel interface {
		Insert(ctx context.Context, data *DQuery) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*DQuery, error)
		FindOneByName(ctx context.Context, name string) (*DQuery, error)
		Update(ctx context.Context, data *DQuery) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDQueryModel struct {
		conn  sqlx.SqlConn
		table string
	}

	DQuery struct {
		Id            int64  `db:"id"`
		Name          string `db:"name"`
		Active        int64  `db:"active"`
		SearchType    int64  `db:"search_type"`
		NameType      int64  `db:"name_type"`
		PageNow       int64  `db:"page_now"`
		Offset        int64  `db:"offset"`
		StartPage     int64  `db:"start_page"`
		EndPage       int64  `db:"end_page"`
		LastQueryTime int64  `db:"last_query_time"`
		CreatedOn     int64  `db:"created_on"`
		UpdatedOn     int64  `db:"updated_on"`
	}
)

func newDQueryModel(conn sqlx.SqlConn) *defaultDQueryModel {
	return &defaultDQueryModel{
		conn:  conn,
		table: "`d_query`",
	}
}

func (m *defaultDQueryModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDQueryModel) FindOne(ctx context.Context, id int64) (*DQuery, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dQueryRows, m.table)
	var resp DQuery
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDQueryModel) FindOneByName(ctx context.Context, name string) (*DQuery, error) {
	var resp DQuery
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", dQueryRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDQueryModel) Insert(ctx context.Context, data *DQuery) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, dQueryRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Active, data.SearchType, data.NameType, data.PageNow, data.Offset, data.StartPage, data.EndPage, data.LastQueryTime, data.CreatedOn, data.UpdatedOn)
	return ret, err
}

func (m *defaultDQueryModel) Update(ctx context.Context, newData *DQuery) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dQueryRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.Active, newData.SearchType, newData.NameType, newData.PageNow, newData.Offset, newData.StartPage, newData.EndPage, newData.LastQueryTime, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	return err
}

func (m *defaultDQueryModel) tableName() string {
	return m.table
}
