// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dRecordFieldNames          = builder.RawFieldNames(&DRecord{})
	dRecordRows                = strings.Join(dRecordFieldNames, ",")
	dRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(dRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	dRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(dRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	dRecordModel interface {
		Insert(ctx context.Context, data *DRecord) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*DRecord, error)
		FindOneByName(ctx context.Context, name string) (*DRecord, error)
		Update(ctx context.Context, data *DRecord) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDRecordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	DRecord struct {
		Id           int64  `db:"id"`
		Name         string `db:"name"`
		StartTime    int64  `db:"start_time"`
		EndTime      int64  `db:"end_time"`
		Type         string `db:"type"`
		DetailNumber int64  `db:"detail_number"`
		CreatedOn    int64  `db:"created_on"`
		UpdatedOn    int64  `db:"updated_on"`
	}
)

func newDRecordModel(conn sqlx.SqlConn) *defaultDRecordModel {
	return &defaultDRecordModel{
		conn:  conn,
		table: "`d_record`",
	}
}

func (m *defaultDRecordModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDRecordModel) FindOne(ctx context.Context, id int64) (*DRecord, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dRecordRows, m.table)
	var resp DRecord
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDRecordModel) FindOneByName(ctx context.Context, name string) (*DRecord, error) {
	var resp DRecord
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", dRecordRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDRecordModel) Insert(ctx context.Context, data *DRecord) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, dRecordRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.StartTime, data.EndTime, data.Type, data.DetailNumber, data.CreatedOn, data.UpdatedOn)
	return ret, err
}

func (m *defaultDRecordModel) Update(ctx context.Context, newData *DRecord) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dRecordRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.StartTime, newData.EndTime, newData.Type, newData.DetailNumber, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	return err
}

func (m *defaultDRecordModel) tableName() string {
	return m.table
}
