// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gListFieldNames          = builder.RawFieldNames(&GList{})
	gListRows                = strings.Join(gListFieldNames, ",")
	gListRowsExpectAutoSet   = strings.Join(stringx.Remove(gListFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gListRowsWithPlaceHolder = strings.Join(stringx.Remove(gListFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	gListModel interface {
		Insert(ctx context.Context, data *GList) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GList, error)
		FindOneByName(ctx context.Context, name string) (*GList, error)
		Update(ctx context.Context, data *GList) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGListModel struct {
		conn  sqlx.SqlConn
		table string
	}

	GList struct {
		Id         int64  `db:"id"`
		Name       string `db:"name"`
		ScName     string `db:"sc_name"`
		MovieJavId string `db:"movie_jav_id"`
		IsCome     int64  `db:"is_come"`
		CreatedOn  int64  `db:"created_on"`
		UpdatedOn  int64  `db:"updated_on"`
	}
)

func newGListModel(conn sqlx.SqlConn) *defaultGListModel {
	return &defaultGListModel{
		conn:  conn,
		table: "`g_list`",
	}
}

func (m *defaultGListModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGListModel) FindOne(ctx context.Context, id int64) (*GList, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gListRows, m.table)
	var resp GList
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGListModel) FindOneByName(ctx context.Context, name string) (*GList, error) {
	var resp GList
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", gListRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGListModel) Insert(ctx context.Context, data *GList) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, gListRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.ScName, data.MovieJavId, data.IsCome, data.CreatedOn, data.UpdatedOn)
	return ret, err
}

func (m *defaultGListModel) Update(ctx context.Context, newData *GList) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gListRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.ScName, newData.MovieJavId, newData.IsCome, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	return err
}

func (m *defaultGListModel) tableName() string {
	return m.table
}
