// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gScFieldNames          = builder.RawFieldNames(&GSc{})
	gScRows                = strings.Join(gScFieldNames, ",")
	gScRowsExpectAutoSet   = strings.Join(stringx.Remove(gScFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gScRowsWithPlaceHolder = strings.Join(stringx.Remove(gScFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	gScModel interface {
		Insert(ctx context.Context, data *GSc) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GSc, error)
		FindOneByName(ctx context.Context, name string) (*GSc, error)
		Update(ctx context.Context, data *GSc) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGScModel struct {
		conn  sqlx.SqlConn
		table string
	}

	GSc struct {
		Id            int64  `db:"id"`
		Name          string `db:"name"`
		MovieNumber   int64  `db:"movie_number"`
		ScTime        int64  `db:"sc_time"`
		ComeMovieName string `db:"come_movie_name"`
		CreatedOn     int64  `db:"created_on"`
		UpdatedOn     int64  `db:"updated_on"`
	}
)

func newGScModel(conn sqlx.SqlConn) *defaultGScModel {
	return &defaultGScModel{
		conn:  conn,
		table: "`g_sc`",
	}
}

func (m *defaultGScModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGScModel) FindOne(ctx context.Context, id int64) (*GSc, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gScRows, m.table)
	var resp GSc
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGScModel) FindOneByName(ctx context.Context, name string) (*GSc, error) {
	var resp GSc
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", gScRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGScModel) Insert(ctx context.Context, data *GSc) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, gScRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.MovieNumber, data.ScTime, data.ComeMovieName, data.CreatedOn, data.UpdatedOn)
	return ret, err
}

func (m *defaultGScModel) Update(ctx context.Context, newData *GSc) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gScRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.MovieNumber, newData.ScTime, newData.ComeMovieName, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	return err
}

func (m *defaultGScModel) tableName() string {
	return m.table
}
