// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	rawBestinvFieldNames          = builder.RawFieldNames(&RawBestinv{})
	rawBestinvRows                = strings.Join(rawBestinvFieldNames, ",")
	rawBestinvRowsExpectAutoSet   = strings.Join(stringx.Remove(rawBestinvFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	rawBestinvRowsWithPlaceHolder = strings.Join(stringx.Remove(rawBestinvFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	rawBestinvModel interface {
		Insert(ctx context.Context, data *RawBestinv) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*RawBestinv, error)
		FindOneByName(ctx context.Context, name string) (*RawBestinv, error)
		Update(ctx context.Context, data *RawBestinv) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRawBestinvModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RawBestinv struct {
		Id            int64  `db:"id"`
		Name          string `db:"name"`
		NeedScan      int64  `db:"need_scan"`
		NeedRankCheck int64  `db:"need_rank_check"`
		Category      int64  `db:"category"`
		Page          int64  `db:"page"`
		DayNumber     int64  `db:"day_number"`
		Content       string `db:"content"`
		LastQueryTime int64  `db:"last_query_time"`
		Date          string `db:"date"`
		CreatedOn     int64  `db:"created_on"`
		UpdatedOn     int64  `db:"updated_on"`
	}
)

func newRawBestinvModel(conn sqlx.SqlConn) *defaultRawBestinvModel {
	return &defaultRawBestinvModel{
		conn:  conn,
		table: "`raw_bestinv`",
	}
}

func (m *defaultRawBestinvModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRawBestinvModel) FindOne(ctx context.Context, id int64) (*RawBestinv, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", rawBestinvRows, m.table)
	var resp RawBestinv
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRawBestinvModel) FindOneByName(ctx context.Context, name string) (*RawBestinv, error) {
	var resp RawBestinv
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", rawBestinvRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRawBestinvModel) Insert(ctx context.Context, data *RawBestinv) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, rawBestinvRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.NeedScan, data.NeedRankCheck, data.Category, data.Page, data.DayNumber, data.Content, data.LastQueryTime, data.Date, data.CreatedOn, data.UpdatedOn)
	return ret, err
}

func (m *defaultRawBestinvModel) Update(ctx context.Context, newData *RawBestinv) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, rawBestinvRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.NeedScan, newData.NeedRankCheck, newData.Category, newData.Page, newData.DayNumber, newData.Content, newData.LastQueryTime, newData.Date, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	return err
}

func (m *defaultRawBestinvModel) tableName() string {
	return m.table
}
