// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	rawDetailFieldNames          = builder.RawFieldNames(&RawDetail{})
	rawDetailRows                = strings.Join(rawDetailFieldNames, ",")
	rawDetailRowsExpectAutoSet   = strings.Join(stringx.Remove(rawDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	rawDetailRowsWithPlaceHolder = strings.Join(stringx.Remove(rawDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	rawDetailModel interface {
		Insert(ctx context.Context, data *RawDetail) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*RawDetail, error)
		FindOneByJavId(ctx context.Context, javId string) (*RawDetail, error)
		Update(ctx context.Context, data *RawDetail) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRawDetailModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RawDetail struct {
		Id            int64  `db:"id"`
		Name          string `db:"name"`
		JavId         string `db:"jav_id"`
		Prefix        string `db:"prefix"`
		LastQueryTime int64  `db:"last_query_time"`
		QueryUrl      string `db:"query_url"`
		NeedScan      int64  `db:"need_scan"`
		Content       string `db:"content"`
		CreatedOn     int64  `db:"created_on"`
		UpdatedOn     int64  `db:"updated_on"`
	}
)

func newRawDetailModel(conn sqlx.SqlConn) *defaultRawDetailModel {
	return &defaultRawDetailModel{
		conn:  conn,
		table: "`raw_detail`",
	}
}

func (m *defaultRawDetailModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRawDetailModel) FindOne(ctx context.Context, id int64) (*RawDetail, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", rawDetailRows, m.table)
	var resp RawDetail
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRawDetailModel) FindOneByJavId(ctx context.Context, javId string) (*RawDetail, error) {
	var resp RawDetail
	query := fmt.Sprintf("select %s from %s where `jav_id` = ? limit 1", rawDetailRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, javId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRawDetailModel) Insert(ctx context.Context, data *RawDetail) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, rawDetailRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.JavId, data.Prefix, data.LastQueryTime, data.QueryUrl, data.NeedScan, data.Content, data.CreatedOn, data.UpdatedOn)
	return ret, err
}

func (m *defaultRawDetailModel) Update(ctx context.Context, newData *RawDetail) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, rawDetailRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.JavId, newData.Prefix, newData.LastQueryTime, newData.QueryUrl, newData.NeedScan, newData.Content, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	return err
}

func (m *defaultRawDetailModel) tableName() string {
	return m.table
}
