// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	rawInventoryFieldNames          = builder.RawFieldNames(&RawInventory{})
	rawInventoryRows                = strings.Join(rawInventoryFieldNames, ",")
	rawInventoryRowsExpectAutoSet   = strings.Join(stringx.Remove(rawInventoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	rawInventoryRowsWithPlaceHolder = strings.Join(stringx.Remove(rawInventoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	rawInventoryModel interface {
		Insert(ctx context.Context, data *RawInventory) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*RawInventory, error)
		FindOneByName(ctx context.Context, name string) (*RawInventory, error)
		Update(ctx context.Context, data *RawInventory) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRawInventoryModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RawInventory struct {
		Id            int64  `db:"id"`
		Name          string `db:"name"`
		NeedScan      int64  `db:"need_scan"`
		Keyword       string `db:"keyword"`
		Parent        string `db:"parent"`
		Page          int64  `db:"page"`
		Content       string `db:"content"`
		Category      int64  `db:"category"`
		LastQueryTime int64  `db:"last_query_time"`
		CreatedOn     int64  `db:"created_on"`
		UpdatedOn     int64  `db:"updated_on"`
	}
)

func newRawInventoryModel(conn sqlx.SqlConn) *defaultRawInventoryModel {
	return &defaultRawInventoryModel{
		conn:  conn,
		table: "`raw_inventory`",
	}
}

func (m *defaultRawInventoryModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRawInventoryModel) FindOne(ctx context.Context, id int64) (*RawInventory, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", rawInventoryRows, m.table)
	var resp RawInventory
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRawInventoryModel) FindOneByName(ctx context.Context, name string) (*RawInventory, error) {
	var resp RawInventory
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", rawInventoryRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRawInventoryModel) Insert(ctx context.Context, data *RawInventory) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, rawInventoryRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.NeedScan, data.Keyword, data.Parent, data.Page, data.Content, data.Category, data.LastQueryTime, data.CreatedOn, data.UpdatedOn)
	return ret, err
}

func (m *defaultRawInventoryModel) Update(ctx context.Context, newData *RawInventory) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, rawInventoryRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.NeedScan, newData.Keyword, newData.Parent, newData.Page, newData.Content, newData.Category, newData.LastQueryTime, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	return err
}

func (m *defaultRawInventoryModel) tableName() string {
	return m.table
}
