// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	vAlbumFieldNames          = builder.RawFieldNames(&VAlbum{})
	vAlbumRows                = strings.Join(vAlbumFieldNames, ",")
	vAlbumRowsExpectAutoSet   = strings.Join(stringx.Remove(vAlbumFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	vAlbumRowsWithPlaceHolder = strings.Join(stringx.Remove(vAlbumFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	vAlbumModel interface {
		Insert(ctx context.Context, data *VAlbum) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*VAlbum, error)
		FindOneByName(ctx context.Context, name string) (*VAlbum, error)
		Update(ctx context.Context, data *VAlbum) error
		Delete(ctx context.Context, id int64) error
	}

	defaultVAlbumModel struct {
		conn  sqlx.SqlConn
		table string
	}

	VAlbum struct {
		Id          int64  `db:"id"`
		Name        string `db:"name"`
		FilmNumber  int64  `db:"film_number"`
		HasUploaded int64  `db:"has_uploaded"`
		Size        int64  `db:"size"`
		CreatedOn   int64  `db:"created_on"`
		UpdatedOn   int64  `db:"updated_on"`
	}
)

func newVAlbumModel(conn sqlx.SqlConn) *defaultVAlbumModel {
	return &defaultVAlbumModel{
		conn:  conn,
		table: "`v_album`",
	}
}

func (m *defaultVAlbumModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultVAlbumModel) FindOne(ctx context.Context, id int64) (*VAlbum, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", vAlbumRows, m.table)
	var resp VAlbum
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVAlbumModel) FindOneByName(ctx context.Context, name string) (*VAlbum, error) {
	var resp VAlbum
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", vAlbumRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVAlbumModel) Insert(ctx context.Context, data *VAlbum) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, vAlbumRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.FilmNumber, data.HasUploaded, data.Size, data.CreatedOn, data.UpdatedOn)
	return ret, err
}

func (m *defaultVAlbumModel) Update(ctx context.Context, newData *VAlbum) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, vAlbumRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.FilmNumber, newData.HasUploaded, newData.Size, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	return err
}

func (m *defaultVAlbumModel) tableName() string {
	return m.table
}
