// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	vFilmFieldNames          = builder.RawFieldNames(&VFilm{})
	vFilmRows                = strings.Join(vFilmFieldNames, ",")
	vFilmRowsExpectAutoSet   = strings.Join(stringx.Remove(vFilmFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	vFilmRowsWithPlaceHolder = strings.Join(stringx.Remove(vFilmFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	vFilmModel interface {
		Insert(ctx context.Context, data *VFilm) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*VFilm, error)
		FindOneByFilePath(ctx context.Context, filePath string) (*VFilm, error)
		FindOneByMovieJavId(ctx context.Context, movieJavId string) (*VFilm, error)
		FindOneByName(ctx context.Context, name string) (*VFilm, error)
		Update(ctx context.Context, data *VFilm) error
		Delete(ctx context.Context, id int64) error
	}

	defaultVFilmModel struct {
		conn  sqlx.SqlConn
		table string
	}

	VFilm struct {
		Id           int64   `db:"id"`
		MovieJavId   string  `db:"movie_jav_id"`
		Name         string  `db:"name"`
		Dir4         string  `db:"dir4"`
		Dir3         string  `db:"dir3"`
		Dir2         string  `db:"dir2"`
		Dir1         string  `db:"dir1"`
		FilePath     string  `db:"file_path"`
		Dir          string  `db:"dir"`
		Size         int64   `db:"size"`
		BirthTime    int64   `db:"birth_time"`
		Prefix       string  `db:"prefix"`
		Alias        string  `db:"alias"`
		AlbumId      int64   `db:"album_id"`
		Width        int64   `db:"width"`
		Height       int64   `db:"height"`
		BitRate      int64   `db:"bit_rate"`
		Duration     int64   `db:"duration"`
		FrameAverage float64 `db:"frame_average"`
		RawProbe     string  `db:"raw_probe"`
		HasSub       int64   `db:"has_sub"`
		SelfMake     int64   `db:"self_make"`
		Erased       int64   `db:"erased"`
		NeedScanBase int64   `db:"need_scan_base"`
		NeedScanMeta int64   `db:"need_scan_meta"`
		IsRemoved    int64   `db:"is_removed"`
		RemoveTime   int64   `db:"remove_time"`
		CreatedOn    int64   `db:"created_on"`
		UpdatedOn    int64   `db:"updated_on"`
		ScTimes      int64   `db:"sc_times"`
		ComeTimes    int64   `db:"come_times"`
		LastScTime   int64   `db:"last_sc_time"`
	}
)

func newVFilmModel(conn sqlx.SqlConn) *defaultVFilmModel {
	return &defaultVFilmModel{
		conn:  conn,
		table: "`v_film`",
	}
}

func (m *defaultVFilmModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultVFilmModel) FindOne(ctx context.Context, id int64) (*VFilm, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", vFilmRows, m.table)
	var resp VFilm
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVFilmModel) FindOneByFilePath(ctx context.Context, filePath string) (*VFilm, error) {
	var resp VFilm
	query := fmt.Sprintf("select %s from %s where `file_path` = ? limit 1", vFilmRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, filePath)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVFilmModel) FindOneByMovieJavId(ctx context.Context, movieJavId string) (*VFilm, error) {
	var resp VFilm
	query := fmt.Sprintf("select %s from %s where `movie_jav_id` = ? limit 1", vFilmRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, movieJavId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVFilmModel) FindOneByName(ctx context.Context, name string) (*VFilm, error) {
	var resp VFilm
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", vFilmRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVFilmModel) Insert(ctx context.Context, data *VFilm) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, vFilmRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.MovieJavId, data.Name, data.Dir4, data.Dir3, data.Dir2, data.Dir1, data.FilePath, data.Dir, data.Size, data.BirthTime, data.Prefix, data.Alias, data.AlbumId, data.Width, data.Height, data.BitRate, data.Duration, data.FrameAverage, data.RawProbe, data.HasSub, data.SelfMake, data.Erased, data.NeedScanBase, data.NeedScanMeta, data.IsRemoved, data.RemoveTime, data.CreatedOn, data.UpdatedOn, data.ScTimes, data.ComeTimes, data.LastScTime)
	return ret, err
}

func (m *defaultVFilmModel) Update(ctx context.Context, newData *VFilm) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, vFilmRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.MovieJavId, newData.Name, newData.Dir4, newData.Dir3, newData.Dir2, newData.Dir1, newData.FilePath, newData.Dir, newData.Size, newData.BirthTime, newData.Prefix, newData.Alias, newData.AlbumId, newData.Width, newData.Height, newData.BitRate, newData.Duration, newData.FrameAverage, newData.RawProbe, newData.HasSub, newData.SelfMake, newData.Erased, newData.NeedScanBase, newData.NeedScanMeta, newData.IsRemoved, newData.RemoveTime, newData.CreatedOn, newData.UpdatedOn, newData.ScTimes, newData.ComeTimes, newData.LastScTime, newData.Id)
	return err
}

func (m *defaultVFilmModel) tableName() string {
	return m.table
}
