// Code generated by goctl. DO NOT EDIT.

package modelx

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	vVideoFieldNames          = builder.RawFieldNames(&VVideo{})
	vVideoRows                = strings.Join(vVideoFieldNames, ",")
	vVideoRowsExpectAutoSet   = strings.Join(stringx.Remove(vVideoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	vVideoRowsWithPlaceHolder = strings.Join(stringx.Remove(vVideoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	vVideoModel interface {
		Insert(ctx context.Context, data *VVideo) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*VVideo, error)
		FindOneByBaseName(ctx context.Context, baseName string) (*VVideo, error)
		FindOneByFilePath(ctx context.Context, filePath string) (*VVideo, error)
		Update(ctx context.Context, data *VVideo) error
		Delete(ctx context.Context, id int64) error
	}

	defaultVVideoModel struct {
		conn  sqlx.SqlConn
		table string
	}

	VVideo struct {
		Id           int64   `db:"id"`
		FilePath     string  `db:"file_path"`
		BaseName     string  `db:"base_name"`
		DirRoot      string  `db:"dir_root"`
		Dir1         string  `db:"dir1"`
		Dir2         string  `db:"dir2"`
		Dir3         string  `db:"dir3"`
		Size         int64   `db:"size"`
		BirthTime    int64   `db:"birth_time"`
		Label        string  `db:"label"`
		Code         string  `db:"code"`
		Alias        string  `db:"alias"`
		Width        int64   `db:"width"`
		Height       int64   `db:"height"`
		BitRate      int64   `db:"bit_rate"`
		Duration     int64   `db:"duration"`
		FrameAverage float64 `db:"frame_average"`
		RawProbe     string  `db:"raw_probe"`
		HasSub       int64   `db:"has_sub"`
		SelfMake     int64   `db:"self_make"`
		NeedScanBase int64   `db:"need_scan_base"`
		NeedScanMeta int64   `db:"need_scan_meta"`
		IsRemoved    int64   `db:"is_removed"`
		RemoveTime   int64   `db:"remove_time"`
		CreatedOn    int64   `db:"created_on"`
		UpdatedOn    int64   `db:"updated_on"`
		ScTimes      int64   `db:"sc_times"`
		ComeTimes    int64   `db:"come_times"`
		LastScTime   int64   `db:"last_sc_time"`
	}
)

func newVVideoModel(conn sqlx.SqlConn) *defaultVVideoModel {
	return &defaultVVideoModel{
		conn:  conn,
		table: "`v_video`",
	}
}

func (m *defaultVVideoModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultVVideoModel) FindOne(ctx context.Context, id int64) (*VVideo, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", vVideoRows, m.table)
	var resp VVideo
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVVideoModel) FindOneByBaseName(ctx context.Context, baseName string) (*VVideo, error) {
	var resp VVideo
	query := fmt.Sprintf("select %s from %s where `base_name` = ? limit 1", vVideoRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, baseName)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVVideoModel) FindOneByFilePath(ctx context.Context, filePath string) (*VVideo, error) {
	var resp VVideo
	query := fmt.Sprintf("select %s from %s where `file_path` = ? limit 1", vVideoRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, filePath)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVVideoModel) Insert(ctx context.Context, data *VVideo) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, vVideoRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.FilePath, data.BaseName, data.DirRoot, data.Dir1, data.Dir2, data.Dir3, data.Size, data.BirthTime, data.Label, data.Code, data.Alias, data.Width, data.Height, data.BitRate, data.Duration, data.FrameAverage, data.RawProbe, data.HasSub, data.SelfMake, data.NeedScanBase, data.NeedScanMeta, data.IsRemoved, data.RemoveTime, data.CreatedOn, data.UpdatedOn, data.ScTimes, data.ComeTimes, data.LastScTime)
	return ret, err
}

func (m *defaultVVideoModel) Update(ctx context.Context, newData *VVideo) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, vVideoRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.FilePath, newData.BaseName, newData.DirRoot, newData.Dir1, newData.Dir2, newData.Dir3, newData.Size, newData.BirthTime, newData.Label, newData.Code, newData.Alias, newData.Width, newData.Height, newData.BitRate, newData.Duration, newData.FrameAverage, newData.RawProbe, newData.HasSub, newData.SelfMake, newData.NeedScanBase, newData.NeedScanMeta, newData.IsRemoved, newData.RemoveTime, newData.CreatedOn, newData.UpdatedOn, newData.ScTimes, newData.ComeTimes, newData.LastScTime, newData.Id)
	return err
}

func (m *defaultVVideoModel) tableName() string {
	return m.table
}
