// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	amGenreFieldNames          = builder.RawFieldNames(&AmGenre{})
	amGenreRows                = strings.Join(amGenreFieldNames, ",")
	amGenreRowsExpectAutoSet   = strings.Join(stringx.Remove(amGenreFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	amGenreRowsWithPlaceHolder = strings.Join(stringx.Remove(amGenreFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcAmGenreIdPrefix   = "bizcache:rudyGc:amGenre:id:"
	cacheRudyGcAmGenreNamePrefix = "bizcache:rudyGc:amGenre:name:"
)

type (
	amGenreModel interface {
		Insert(ctx context.Context, data *AmGenre) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AmGenre, error)
		FindOneByName(ctx context.Context, name string) (*AmGenre, error)
		Update(ctx context.Context, data *AmGenre) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAmGenreModel struct {
		sqlc.CachedConn
		table string
	}

	AmGenre struct {
		Id               int64  `db:"id"`
		Name             string `db:"name"`
		JavId            string `db:"jav_id"`
		MovieNumber      int64  `db:"movie_number"`
		OwnedMovieNumber int64  `db:"owned_movie_number"`
		CreatedOn        int64  `db:"created_on"`
		UpdatedOn        int64  `db:"updated_on"`
	}
)

func newAmGenreModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAmGenreModel {
	return &defaultAmGenreModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`am_genre`",
	}
}

func (m *defaultAmGenreModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcAmGenreIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmGenreIdPrefix, id)
	rudyGcAmGenreNameKey := fmt.Sprintf("%s%v", cacheRudyGcAmGenreNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcAmGenreIdKey, rudyGcAmGenreNameKey)
	return err
}

func (m *defaultAmGenreModel) FindOne(ctx context.Context, id int64) (*AmGenre, error) {
	rudyGcAmGenreIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmGenreIdPrefix, id)
	var resp AmGenre
	err := m.QueryRowCtx(ctx, &resp, rudyGcAmGenreIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amGenreRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmGenreModel) FindOneByName(ctx context.Context, name string) (*AmGenre, error) {
	rudyGcAmGenreNameKey := fmt.Sprintf("%s%v", cacheRudyGcAmGenreNamePrefix, name)
	var resp AmGenre
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcAmGenreNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", amGenreRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmGenreModel) Insert(ctx context.Context, data *AmGenre) (sql.Result, error) {
	rudyGcAmGenreIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmGenreIdPrefix, data.Id)
	rudyGcAmGenreNameKey := fmt.Sprintf("%s%v", cacheRudyGcAmGenreNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, amGenreRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.JavId, data.MovieNumber, data.OwnedMovieNumber, data.CreatedOn, data.UpdatedOn)
	}, rudyGcAmGenreIdKey, rudyGcAmGenreNameKey)
	return ret, err
}

func (m *defaultAmGenreModel) Update(ctx context.Context, newData *AmGenre) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcAmGenreIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmGenreIdPrefix, data.Id)
	rudyGcAmGenreNameKey := fmt.Sprintf("%s%v", cacheRudyGcAmGenreNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, amGenreRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.JavId, newData.MovieNumber, newData.OwnedMovieNumber, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcAmGenreIdKey, rudyGcAmGenreNameKey)
	return err
}

func (m *defaultAmGenreModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcAmGenreIdPrefix, primary)
}

func (m *defaultAmGenreModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amGenreRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAmGenreModel) tableName() string {
	return m.table
}
