// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	amLabelFieldNames          = builder.RawFieldNames(&AmLabel{})
	amLabelRows                = strings.Join(amLabelFieldNames, ",")
	amLabelRowsExpectAutoSet   = strings.Join(stringx.Remove(amLabelFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	amLabelRowsWithPlaceHolder = strings.Join(stringx.Remove(amLabelFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcAmLabelIdPrefix   = "bizcache:rudyGc:amLabel:id:"
	cacheRudyGcAmLabelNamePrefix = "bizcache:rudyGc:amLabel:name:"
)

type (
	amLabelModel interface {
		Insert(ctx context.Context, data *AmLabel) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AmLabel, error)
		FindOneByName(ctx context.Context, name string) (*AmLabel, error)
		Update(ctx context.Context, data *AmLabel) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAmLabelModel struct {
		sqlc.CachedConn
		table string
	}

	AmLabel struct {
		Id               int64  `db:"id"`
		Name             string `db:"name"`
		JavId            string `db:"jav_id"`
		MovieNumber      int64  `db:"movie_number"`
		OwnedMovieNumber int64  `db:"owned_movie_number"`
		CreatedOn        int64  `db:"created_on"`
		UpdatedOn        int64  `db:"updated_on"`
	}
)

func newAmLabelModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAmLabelModel {
	return &defaultAmLabelModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`am_label`",
	}
}

func (m *defaultAmLabelModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcAmLabelIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmLabelIdPrefix, id)
	rudyGcAmLabelNameKey := fmt.Sprintf("%s%v", cacheRudyGcAmLabelNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcAmLabelIdKey, rudyGcAmLabelNameKey)
	return err
}

func (m *defaultAmLabelModel) FindOne(ctx context.Context, id int64) (*AmLabel, error) {
	rudyGcAmLabelIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmLabelIdPrefix, id)
	var resp AmLabel
	err := m.QueryRowCtx(ctx, &resp, rudyGcAmLabelIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amLabelRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmLabelModel) FindOneByName(ctx context.Context, name string) (*AmLabel, error) {
	rudyGcAmLabelNameKey := fmt.Sprintf("%s%v", cacheRudyGcAmLabelNamePrefix, name)
	var resp AmLabel
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcAmLabelNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", amLabelRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmLabelModel) Insert(ctx context.Context, data *AmLabel) (sql.Result, error) {
	rudyGcAmLabelIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmLabelIdPrefix, data.Id)
	rudyGcAmLabelNameKey := fmt.Sprintf("%s%v", cacheRudyGcAmLabelNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, amLabelRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.JavId, data.MovieNumber, data.OwnedMovieNumber, data.CreatedOn, data.UpdatedOn)
	}, rudyGcAmLabelIdKey, rudyGcAmLabelNameKey)
	return ret, err
}

func (m *defaultAmLabelModel) Update(ctx context.Context, newData *AmLabel) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcAmLabelIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmLabelIdPrefix, data.Id)
	rudyGcAmLabelNameKey := fmt.Sprintf("%s%v", cacheRudyGcAmLabelNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, amLabelRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.JavId, newData.MovieNumber, newData.OwnedMovieNumber, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcAmLabelIdKey, rudyGcAmLabelNameKey)
	return err
}

func (m *defaultAmLabelModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcAmLabelIdPrefix, primary)
}

func (m *defaultAmLabelModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amLabelRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAmLabelModel) tableName() string {
	return m.table
}
