// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	amMakerFieldNames          = builder.RawFieldNames(&AmMaker{})
	amMakerRows                = strings.Join(amMakerFieldNames, ",")
	amMakerRowsExpectAutoSet   = strings.Join(stringx.Remove(amMakerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	amMakerRowsWithPlaceHolder = strings.Join(stringx.Remove(amMakerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcAmMakerIdPrefix   = "bizcache:rudyGc:amMaker:id:"
	cacheRudyGcAmMakerNamePrefix = "bizcache:rudyGc:amMaker:name:"
)

type (
	amMakerModel interface {
		Insert(ctx context.Context, data *AmMaker) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AmMaker, error)
		FindOneByName(ctx context.Context, name string) (*AmMaker, error)
		Update(ctx context.Context, data *AmMaker) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAmMakerModel struct {
		sqlc.CachedConn
		table string
	}

	AmMaker struct {
		Id               int64  `db:"id"`
		Name             string `db:"name"`
		JavId            string `db:"jav_id"`
		MovieNumber      int64  `db:"movie_number"`
		OwnedMovieNumber int64  `db:"owned_movie_number"`
		CreatedOn        int64  `db:"created_on"`
		UpdatedOn        int64  `db:"updated_on"`
	}
)

func newAmMakerModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAmMakerModel {
	return &defaultAmMakerModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`am_maker`",
	}
}

func (m *defaultAmMakerModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcAmMakerIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmMakerIdPrefix, id)
	rudyGcAmMakerNameKey := fmt.Sprintf("%s%v", cacheRudyGcAmMakerNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcAmMakerIdKey, rudyGcAmMakerNameKey)
	return err
}

func (m *defaultAmMakerModel) FindOne(ctx context.Context, id int64) (*AmMaker, error) {
	rudyGcAmMakerIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmMakerIdPrefix, id)
	var resp AmMaker
	err := m.QueryRowCtx(ctx, &resp, rudyGcAmMakerIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amMakerRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmMakerModel) FindOneByName(ctx context.Context, name string) (*AmMaker, error) {
	rudyGcAmMakerNameKey := fmt.Sprintf("%s%v", cacheRudyGcAmMakerNamePrefix, name)
	var resp AmMaker
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcAmMakerNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", amMakerRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmMakerModel) Insert(ctx context.Context, data *AmMaker) (sql.Result, error) {
	rudyGcAmMakerIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmMakerIdPrefix, data.Id)
	rudyGcAmMakerNameKey := fmt.Sprintf("%s%v", cacheRudyGcAmMakerNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, amMakerRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.JavId, data.MovieNumber, data.OwnedMovieNumber, data.CreatedOn, data.UpdatedOn)
	}, rudyGcAmMakerIdKey, rudyGcAmMakerNameKey)
	return ret, err
}

func (m *defaultAmMakerModel) Update(ctx context.Context, newData *AmMaker) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcAmMakerIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmMakerIdPrefix, data.Id)
	rudyGcAmMakerNameKey := fmt.Sprintf("%s%v", cacheRudyGcAmMakerNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, amMakerRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.JavId, newData.MovieNumber, newData.OwnedMovieNumber, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcAmMakerIdKey, rudyGcAmMakerNameKey)
	return err
}

func (m *defaultAmMakerModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcAmMakerIdPrefix, primary)
}

func (m *defaultAmMakerModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amMakerRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAmMakerModel) tableName() string {
	return m.table
}
