// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	amrMovieCastFieldNames          = builder.RawFieldNames(&AmrMovieCast{})
	amrMovieCastRows                = strings.Join(amrMovieCastFieldNames, ",")
	amrMovieCastRowsExpectAutoSet   = strings.Join(stringx.Remove(amrMovieCastFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	amrMovieCastRowsWithPlaceHolder = strings.Join(stringx.Remove(amrMovieCastFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcAmrMovieCastIdPrefix            = "bizcache:rudyGc:amrMovieCast:id:"
	cacheRudyGcAmrMovieCastMovieIdCastIdPrefix = "bizcache:rudyGc:amrMovieCast:movieId:castId:"
)

type (
	amrMovieCastModel interface {
		Insert(ctx context.Context, data *AmrMovieCast) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AmrMovieCast, error)
		FindOneByMovieIdCastId(ctx context.Context, movieId int64, castId int64) (*AmrMovieCast, error)
		Update(ctx context.Context, data *AmrMovieCast) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAmrMovieCastModel struct {
		sqlc.CachedConn
		table string
	}

	AmrMovieCast struct {
		Id        int64 `db:"id"`
		MovieId   int64 `db:"movie_id"`
		CastId    int64 `db:"cast_id"`
		CreatedOn int64 `db:"created_on"`
		UpdatedOn int64 `db:"updated_on"`
	}
)

func newAmrMovieCastModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAmrMovieCastModel {
	return &defaultAmrMovieCastModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`amr_movie_cast`",
	}
}

func (m *defaultAmrMovieCastModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcAmrMovieCastIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmrMovieCastIdPrefix, id)
	rudyGcAmrMovieCastMovieIdCastIdKey := fmt.Sprintf("%s%v:%v", cacheRudyGcAmrMovieCastMovieIdCastIdPrefix, data.MovieId, data.CastId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcAmrMovieCastIdKey, rudyGcAmrMovieCastMovieIdCastIdKey)
	return err
}

func (m *defaultAmrMovieCastModel) FindOne(ctx context.Context, id int64) (*AmrMovieCast, error) {
	rudyGcAmrMovieCastIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmrMovieCastIdPrefix, id)
	var resp AmrMovieCast
	err := m.QueryRowCtx(ctx, &resp, rudyGcAmrMovieCastIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amrMovieCastRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmrMovieCastModel) FindOneByMovieIdCastId(ctx context.Context, movieId int64, castId int64) (*AmrMovieCast, error) {
	rudyGcAmrMovieCastMovieIdCastIdKey := fmt.Sprintf("%s%v:%v", cacheRudyGcAmrMovieCastMovieIdCastIdPrefix, movieId, castId)
	var resp AmrMovieCast
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcAmrMovieCastMovieIdCastIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `movie_id` = ? and `cast_id` = ? limit 1", amrMovieCastRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, movieId, castId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAmrMovieCastModel) Insert(ctx context.Context, data *AmrMovieCast) (sql.Result, error) {
	rudyGcAmrMovieCastIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmrMovieCastIdPrefix, data.Id)
	rudyGcAmrMovieCastMovieIdCastIdKey := fmt.Sprintf("%s%v:%v", cacheRudyGcAmrMovieCastMovieIdCastIdPrefix, data.MovieId, data.CastId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, amrMovieCastRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MovieId, data.CastId, data.CreatedOn, data.UpdatedOn)
	}, rudyGcAmrMovieCastIdKey, rudyGcAmrMovieCastMovieIdCastIdKey)
	return ret, err
}

func (m *defaultAmrMovieCastModel) Update(ctx context.Context, newData *AmrMovieCast) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcAmrMovieCastIdKey := fmt.Sprintf("%s%v", cacheRudyGcAmrMovieCastIdPrefix, data.Id)
	rudyGcAmrMovieCastMovieIdCastIdKey := fmt.Sprintf("%s%v:%v", cacheRudyGcAmrMovieCastMovieIdCastIdPrefix, data.MovieId, data.CastId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, amrMovieCastRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MovieId, newData.CastId, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcAmrMovieCastIdKey, rudyGcAmrMovieCastMovieIdCastIdKey)
	return err
}

func (m *defaultAmrMovieCastModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcAmrMovieCastIdPrefix, primary)
}

func (m *defaultAmrMovieCastModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", amrMovieCastRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAmrMovieCastModel) tableName() string {
	return m.table
}
