// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cRankFieldNames          = builder.RawFieldNames(&CRank{})
	cRankRows                = strings.Join(cRankFieldNames, ",")
	cRankRowsExpectAutoSet   = strings.Join(stringx.Remove(cRankFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cRankRowsWithPlaceHolder = strings.Join(stringx.Remove(cRankFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcCRankIdPrefix      = "cache:rudyGc:cRank:id:"
	cacheRudyGcCRankRankKeyPrefix = "cache:rudyGc:cRank:rankKey:"
)

type (
	cRankModel interface {
		Insert(ctx context.Context, data *CRank) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CRank, error)
		FindOneByRankKey(ctx context.Context, rankKey string) (*CRank, error)
		Update(ctx context.Context, data *CRank) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCRankModel struct {
		sqlc.CachedConn
		table string
	}

	CRank struct {
		Id         int64  `db:"id"`
		RankKey    string `db:"rank_key"` // 唯一键(防重复)
		MovieJavId string `db:"movie_jav_id"`
		DayNumber  int64  `db:"day_number"` // 第几天
		RankPos    int64  `db:"rank_pos"`   // 当天排名
		Category   int64  `db:"category"`   // 榜单类别(月榜/总榜等)
		CreatedOn  int64  `db:"created_on"`
		UpdatedOn  int64  `db:"updated_on"`
	}
)

func newCRankModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCRankModel {
	return &defaultCRankModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`c_rank`",
	}
}

func (m *defaultCRankModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcCRankIdKey := fmt.Sprintf("%s%v", cacheRudyGcCRankIdPrefix, id)
	rudyGcCRankRankKeyKey := fmt.Sprintf("%s%v", cacheRudyGcCRankRankKeyPrefix, data.RankKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcCRankIdKey, rudyGcCRankRankKeyKey)
	return err
}

func (m *defaultCRankModel) FindOne(ctx context.Context, id int64) (*CRank, error) {
	rudyGcCRankIdKey := fmt.Sprintf("%s%v", cacheRudyGcCRankIdPrefix, id)
	var resp CRank
	err := m.QueryRowCtx(ctx, &resp, rudyGcCRankIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cRankRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCRankModel) FindOneByRankKey(ctx context.Context, rankKey string) (*CRank, error) {
	rudyGcCRankRankKeyKey := fmt.Sprintf("%s%v", cacheRudyGcCRankRankKeyPrefix, rankKey)
	var resp CRank
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcCRankRankKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `rank_key` = ? limit 1", cRankRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, rankKey); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCRankModel) Insert(ctx context.Context, data *CRank) (sql.Result, error) {
	rudyGcCRankIdKey := fmt.Sprintf("%s%v", cacheRudyGcCRankIdPrefix, data.Id)
	rudyGcCRankRankKeyKey := fmt.Sprintf("%s%v", cacheRudyGcCRankRankKeyPrefix, data.RankKey)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, cRankRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RankKey, data.MovieJavId, data.DayNumber, data.RankPos, data.Category, data.CreatedOn, data.UpdatedOn)
	}, rudyGcCRankIdKey, rudyGcCRankRankKeyKey)
	return ret, err
}

func (m *defaultCRankModel) Update(ctx context.Context, newData *CRank) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcCRankIdKey := fmt.Sprintf("%s%v", cacheRudyGcCRankIdPrefix, data.Id)
	rudyGcCRankRankKeyKey := fmt.Sprintf("%s%v", cacheRudyGcCRankRankKeyPrefix, data.RankKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cRankRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.RankKey, newData.MovieJavId, newData.DayNumber, newData.RankPos, newData.Category, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcCRankIdKey, rudyGcCRankRankKeyKey)
	return err
}

func (m *defaultCRankModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcCRankIdPrefix, primary)
}

func (m *defaultCRankModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cRankRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCRankModel) tableName() string {
	return m.table
}
