// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"rudy_gc/data/modelx/spiderx"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	eItemFieldNames          = builder.RawFieldNames(&EItem{})
	eItemRows                = strings.Join(eItemFieldNames, ",")
	eItemRowsExpectAutoSet   = strings.Join(stringx.Remove(eItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	eItemRowsWithPlaceHolder = strings.Join(stringx.Remove(eItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	eItemModel interface {
		Insert(ctx context.Context, data *EItem) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*EItem, error)
		FindOneByJavId(ctx context.Context, javId string) (*EItem, error)
		Update(ctx context.Context, data *EItem) error
		Delete(ctx context.Context, id int64) error
	}

	defaultEItemModel struct {
		conn  sqlx.SqlConn
		table string
	}

	EItem struct {
		Id               int64  `db:"id"`
		JavId            string `db:"jav_id"`
		Name             string `db:"name"`
		Prefix           string `db:"prefix"`
		SearchType       int64  `db:"search_type"`
		CoverUrl         string `db:"cover_url"`
		SearchBy         string `db:"search_by"`
		HasDetail        int64  `db:"has_detail"`
		HasDownloadCover int64  `db:"has_download_cover"`
		HasChinese       int64  `db:"has_chinese"`
		DetailNeedScan   int64  `db:"detail_need_scan"`
		DetailBirthTime  int64  `db:"detail_birth_time"`
		DetailUpdateTime int64  `db:"detail_update_time"`
		CreatedOn        int64  `db:"created_on"`
		UpdatedOn        int64  `db:"updated_on"`
	}
)

func newEItemModel(conn sqlx.SqlConn) *defaultEItemModel {
	return &defaultEItemModel{
		conn:  conn,
		table: "`e_item`",
	}
}

func (m *defaultEItemModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultEItemModel) FindOne(ctx context.Context, id int64) (*EItem, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", eItemRows, m.table)
	var resp EItem
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, spiderx.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEItemModel) FindOneByJavId(ctx context.Context, javId string) (*EItem, error) {
	var resp EItem
	query := fmt.Sprintf("select %s from %s where `jav_id` = ? limit 1", eItemRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, javId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, spiderx.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEItemModel) Insert(ctx context.Context, data *EItem) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, eItemRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.JavId, data.Name, data.Prefix, data.SearchType, data.CoverUrl, data.SearchBy, data.HasDetail, data.HasDownloadCover, data.HasChinese, data.DetailNeedScan, data.DetailBirthTime, data.DetailUpdateTime, data.CreatedOn, data.UpdatedOn)
	return ret, err
}

func (m *defaultEItemModel) Update(ctx context.Context, newData *EItem) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, eItemRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.JavId, newData.Name, newData.Prefix, newData.SearchType, newData.CoverUrl, newData.SearchBy, newData.HasDetail, newData.HasDownloadCover, newData.HasChinese, newData.DetailNeedScan, newData.DetailBirthTime, newData.DetailUpdateTime, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	return err
}

func (m *defaultEItemModel) tableName() string {
	return m.table
}
