// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gScFieldNames          = builder.RawFieldNames(&GSc{})
	gScRows                = strings.Join(gScFieldNames, ",")
	gScRowsExpectAutoSet   = strings.Join(stringx.Remove(gScFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gScRowsWithPlaceHolder = strings.Join(stringx.Remove(gScFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcGScIdPrefix   = "cache:rudyGc:gSc:id:"
	cacheRudyGcGScNamePrefix = "cache:rudyGc:gSc:name:"
)

type (
	gScModel interface {
		Insert(ctx context.Context, data *GSc) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GSc, error)
		FindOneByName(ctx context.Context, name string) (*GSc, error)
		Update(ctx context.Context, data *GSc) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGScModel struct {
		sqlc.CachedConn
		table string
	}

	GSc struct {
		Id            int64  `db:"id"`
		Name          string `db:"name"`
		MovieNumber   int64  `db:"movie_number"`
		ScTime        int64  `db:"sc_time"`
		ComeMovieName string `db:"come_movie_name"`
		Cooldown      int64  `db:"cooldown"`
		Duration      int64  `db:"duration"`
		Fg            string `db:"fg"`
		Vessel        string `db:"vessel"`
		MovieCast     string `db:"movie_cast"`
		CreatedOn     int64  `db:"created_on"`
		UpdatedOn     int64  `db:"updated_on"`
	}
)

func newGScModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGScModel {
	return &defaultGScModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`g_sc`",
	}
}

func (m *defaultGScModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcGScIdKey := fmt.Sprintf("%s%v", cacheRudyGcGScIdPrefix, id)
	rudyGcGScNameKey := fmt.Sprintf("%s%v", cacheRudyGcGScNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcGScIdKey, rudyGcGScNameKey)
	return err
}

func (m *defaultGScModel) FindOne(ctx context.Context, id int64) (*GSc, error) {
	rudyGcGScIdKey := fmt.Sprintf("%s%v", cacheRudyGcGScIdPrefix, id)
	var resp GSc
	err := m.QueryRowCtx(ctx, &resp, rudyGcGScIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gScRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGScModel) FindOneByName(ctx context.Context, name string) (*GSc, error) {
	rudyGcGScNameKey := fmt.Sprintf("%s%v", cacheRudyGcGScNamePrefix, name)
	var resp GSc
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcGScNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", gScRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGScModel) Insert(ctx context.Context, data *GSc) (sql.Result, error) {
	rudyGcGScIdKey := fmt.Sprintf("%s%v", cacheRudyGcGScIdPrefix, data.Id)
	rudyGcGScNameKey := fmt.Sprintf("%s%v", cacheRudyGcGScNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, gScRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.MovieNumber, data.ScTime, data.ComeMovieName, data.Cooldown, data.Duration, data.Fg, data.Vessel, data.MovieCast, data.CreatedOn, data.UpdatedOn)
	}, rudyGcGScIdKey, rudyGcGScNameKey)
	return ret, err
}

func (m *defaultGScModel) Update(ctx context.Context, newData *GSc) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcGScIdKey := fmt.Sprintf("%s%v", cacheRudyGcGScIdPrefix, data.Id)
	rudyGcGScNameKey := fmt.Sprintf("%s%v", cacheRudyGcGScNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gScRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.MovieNumber, newData.ScTime, newData.ComeMovieName, newData.Cooldown, newData.Duration, newData.Fg, newData.Vessel, newData.MovieCast, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcGScIdKey, rudyGcGScNameKey)
	return err
}

func (m *defaultGScModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcGScIdPrefix, primary)
}

func (m *defaultGScModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gScRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGScModel) tableName() string {
	return m.table
}
