// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	vDirectoryFieldNames          = builder.RawFieldNames(&VDirectory{})
	vDirectoryRows                = strings.Join(vDirectoryFieldNames, ",")
	vDirectoryRowsExpectAutoSet   = strings.Join(stringx.Remove(vDirectoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	vDirectoryRowsWithPlaceHolder = strings.Join(stringx.Remove(vDirectoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcVDirectoryIdPrefix           = "cache:rudyGc:vDirectory:id:"
	cacheRudyGcVDirectoryParentIdNamePrefix = "cache:rudyGc:vDirectory:parentId:name:"
	cacheRudyGcVDirectoryPathPrefix         = "cache:rudyGc:vDirectory:path:"
)

type (
	vDirectoryModel interface {
		Insert(ctx context.Context, data *VDirectory) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*VDirectory, error)
		FindOneByParentIdName(ctx context.Context, parentId int64, name string) (*VDirectory, error)
		FindOneByPath(ctx context.Context, path string) (*VDirectory, error)
		Update(ctx context.Context, data *VDirectory) error
		Delete(ctx context.Context, id int64) error
	}

	defaultVDirectoryModel struct {
		sqlc.CachedConn
		table string
	}

	VDirectory struct {
		Id        int64  `db:"id"`
		ParentId  int64  `db:"parent_id"`
		Name      string `db:"name"`
		Depth     int64  `db:"depth"`
		Path      string `db:"path"`
		PathHash  string `db:"path_hash"`
		CreatedOn int64  `db:"created_on"`
		UpdatedOn int64  `db:"updated_on"`
	}
)

func newVDirectoryModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultVDirectoryModel {
	return &defaultVDirectoryModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`v_directory`",
	}
}

func (m *defaultVDirectoryModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcVDirectoryIdKey := fmt.Sprintf("%s%v", cacheRudyGcVDirectoryIdPrefix, id)
	rudyGcVDirectoryParentIdNameKey := fmt.Sprintf("%s%v:%v", cacheRudyGcVDirectoryParentIdNamePrefix, data.ParentId, data.Name)
	rudyGcVDirectoryPathKey := fmt.Sprintf("%s%v", cacheRudyGcVDirectoryPathPrefix, data.Path)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcVDirectoryIdKey, rudyGcVDirectoryParentIdNameKey, rudyGcVDirectoryPathKey)
	return err
}

func (m *defaultVDirectoryModel) FindOne(ctx context.Context, id int64) (*VDirectory, error) {
	rudyGcVDirectoryIdKey := fmt.Sprintf("%s%v", cacheRudyGcVDirectoryIdPrefix, id)
	var resp VDirectory
	err := m.QueryRowCtx(ctx, &resp, rudyGcVDirectoryIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", vDirectoryRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVDirectoryModel) FindOneByParentIdName(ctx context.Context, parentId int64, name string) (*VDirectory, error) {
	rudyGcVDirectoryParentIdNameKey := fmt.Sprintf("%s%v:%v", cacheRudyGcVDirectoryParentIdNamePrefix, parentId, name)
	var resp VDirectory
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcVDirectoryParentIdNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `parent_id` = ? and `name` = ? limit 1", vDirectoryRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, parentId, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVDirectoryModel) FindOneByPath(ctx context.Context, path string) (*VDirectory, error) {
	rudyGcVDirectoryPathKey := fmt.Sprintf("%s%v", cacheRudyGcVDirectoryPathPrefix, path)
	var resp VDirectory
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcVDirectoryPathKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `path` = ? limit 1", vDirectoryRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, path); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVDirectoryModel) Insert(ctx context.Context, data *VDirectory) (sql.Result, error) {
	rudyGcVDirectoryIdKey := fmt.Sprintf("%s%v", cacheRudyGcVDirectoryIdPrefix, data.Id)
	rudyGcVDirectoryParentIdNameKey := fmt.Sprintf("%s%v:%v", cacheRudyGcVDirectoryParentIdNamePrefix, data.ParentId, data.Name)
	rudyGcVDirectoryPathKey := fmt.Sprintf("%s%v", cacheRudyGcVDirectoryPathPrefix, data.Path)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, vDirectoryRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ParentId, data.Name, data.Depth, data.Path, data.PathHash, data.CreatedOn, data.UpdatedOn)
	}, rudyGcVDirectoryIdKey, rudyGcVDirectoryParentIdNameKey, rudyGcVDirectoryPathKey)
	return ret, err
}

func (m *defaultVDirectoryModel) Update(ctx context.Context, newData *VDirectory) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcVDirectoryIdKey := fmt.Sprintf("%s%v", cacheRudyGcVDirectoryIdPrefix, data.Id)
	rudyGcVDirectoryParentIdNameKey := fmt.Sprintf("%s%v:%v", cacheRudyGcVDirectoryParentIdNamePrefix, data.ParentId, data.Name)
	rudyGcVDirectoryPathKey := fmt.Sprintf("%s%v", cacheRudyGcVDirectoryPathPrefix, data.Path)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, vDirectoryRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ParentId, newData.Name, newData.Depth, newData.Path, newData.PathHash, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcVDirectoryIdKey, rudyGcVDirectoryParentIdNameKey, rudyGcVDirectoryPathKey)
	return err
}

func (m *defaultVDirectoryModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcVDirectoryIdPrefix, primary)
}

func (m *defaultVDirectoryModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", vDirectoryRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultVDirectoryModel) tableName() string {
	return m.table
}
