// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package moviex

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	vFilmFieldNames          = builder.RawFieldNames(&VFilm{})
	vFilmRows                = strings.Join(vFilmFieldNames, ",")
	vFilmRowsExpectAutoSet   = strings.Join(stringx.Remove(vFilmFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	vFilmRowsWithPlaceHolder = strings.Join(stringx.Remove(vFilmFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRudyGcVFilmIdPrefix         = "cache:rudyGc:vFilm:id:"
	cacheRudyGcVFilmFileNamePrefix   = "cache:rudyGc:vFilm:fileName:"
	cacheRudyGcVFilmMovieJavIdPrefix = "cache:rudyGc:vFilm:movieJavId:"
	cacheRudyGcVFilmMovieNamePrefix  = "cache:rudyGc:vFilm:movieName:"
)

type (
	vFilmModel interface {
		Insert(ctx context.Context, data *VFilm) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*VFilm, error)
		FindOneByFileName(ctx context.Context, fileName string) (*VFilm, error)
		FindOneByMovieJavId(ctx context.Context, movieJavId string) (*VFilm, error)
		FindOneByMovieName(ctx context.Context, movieName string) (*VFilm, error)
		Update(ctx context.Context, data *VFilm) error
		Delete(ctx context.Context, id int64) error
	}

	defaultVFilmModel struct {
		sqlc.CachedConn
		table string
	}

	VFilm struct {
		Id           int64   `db:"id"`
		MovieJavId   string  `db:"movie_jav_id"`
		MovieName    string  `db:"movie_name"`
		FileName     string  `db:"file_name"`
		DirectoryId  int64   `db:"directory_id"`
		RootDir      string  `db:"root_dir"`
		Dir1Id       int64   `db:"dir1_id"`
		Dir2Id       int64   `db:"dir2_id"`
		Dir3Id       int64   `db:"dir3_id"`
		Dir4Id       int64   `db:"dir4_id"`
		Alias        string  `db:"alias"`
		Size         int64   `db:"size"`
		Width        int64   `db:"width"`
		Height       int64   `db:"height"`
		BitRate      int64   `db:"bit_rate"`
		Duration     int64   `db:"duration"`
		FrameAverage float64 `db:"frame_average"`
		HasSub       int64   `db:"has_sub"`
		SelfMake     int64   `db:"self_make"`
		HasMask      int64   `db:"has_mask"`
		NeedScanMeta int64   `db:"need_scan_meta"`
		IsRemoved    int64   `db:"is_removed"`
		RemoveTime   int64   `db:"remove_time"`
		ScTimes      int64   `db:"sc_times"`
		ComeTimes    int64   `db:"come_times"`
		LastScTime   int64   `db:"last_sc_time"`
		BirthTime    int64   `db:"birth_time"`
		CreatedOn    int64   `db:"created_on"`
		UpdatedOn    int64   `db:"updated_on"`
	}
)

func newVFilmModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultVFilmModel {
	return &defaultVFilmModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`v_film`",
	}
}

func (m *defaultVFilmModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rudyGcVFilmFileNameKey := fmt.Sprintf("%s%v", cacheRudyGcVFilmFileNamePrefix, data.FileName)
	rudyGcVFilmIdKey := fmt.Sprintf("%s%v", cacheRudyGcVFilmIdPrefix, id)
	rudyGcVFilmMovieJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcVFilmMovieJavIdPrefix, data.MovieJavId)
	rudyGcVFilmMovieNameKey := fmt.Sprintf("%s%v", cacheRudyGcVFilmMovieNamePrefix, data.MovieName)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rudyGcVFilmFileNameKey, rudyGcVFilmIdKey, rudyGcVFilmMovieJavIdKey, rudyGcVFilmMovieNameKey)
	return err
}

func (m *defaultVFilmModel) FindOne(ctx context.Context, id int64) (*VFilm, error) {
	rudyGcVFilmIdKey := fmt.Sprintf("%s%v", cacheRudyGcVFilmIdPrefix, id)
	var resp VFilm
	err := m.QueryRowCtx(ctx, &resp, rudyGcVFilmIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", vFilmRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVFilmModel) FindOneByFileName(ctx context.Context, fileName string) (*VFilm, error) {
	rudyGcVFilmFileNameKey := fmt.Sprintf("%s%v", cacheRudyGcVFilmFileNamePrefix, fileName)
	var resp VFilm
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcVFilmFileNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `file_name` = ? limit 1", vFilmRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, fileName); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVFilmModel) FindOneByMovieJavId(ctx context.Context, movieJavId string) (*VFilm, error) {
	rudyGcVFilmMovieJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcVFilmMovieJavIdPrefix, movieJavId)
	var resp VFilm
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcVFilmMovieJavIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `movie_jav_id` = ? limit 1", vFilmRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, movieJavId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVFilmModel) FindOneByMovieName(ctx context.Context, movieName string) (*VFilm, error) {
	rudyGcVFilmMovieNameKey := fmt.Sprintf("%s%v", cacheRudyGcVFilmMovieNamePrefix, movieName)
	var resp VFilm
	err := m.QueryRowIndexCtx(ctx, &resp, rudyGcVFilmMovieNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `movie_name` = ? limit 1", vFilmRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, movieName); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVFilmModel) Insert(ctx context.Context, data *VFilm) (sql.Result, error) {
	rudyGcVFilmFileNameKey := fmt.Sprintf("%s%v", cacheRudyGcVFilmFileNamePrefix, data.FileName)
	rudyGcVFilmIdKey := fmt.Sprintf("%s%v", cacheRudyGcVFilmIdPrefix, data.Id)
	rudyGcVFilmMovieJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcVFilmMovieJavIdPrefix, data.MovieJavId)
	rudyGcVFilmMovieNameKey := fmt.Sprintf("%s%v", cacheRudyGcVFilmMovieNamePrefix, data.MovieName)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, vFilmRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MovieJavId, data.MovieName, data.FileName, data.DirectoryId, data.RootDir, data.Dir1Id, data.Dir2Id, data.Dir3Id, data.Dir4Id, data.Alias, data.Size, data.Width, data.Height, data.BitRate, data.Duration, data.FrameAverage, data.HasSub, data.SelfMake, data.HasMask, data.NeedScanMeta, data.IsRemoved, data.RemoveTime, data.ScTimes, data.ComeTimes, data.LastScTime, data.BirthTime, data.CreatedOn, data.UpdatedOn)
	}, rudyGcVFilmFileNameKey, rudyGcVFilmIdKey, rudyGcVFilmMovieJavIdKey, rudyGcVFilmMovieNameKey)
	return ret, err
}

func (m *defaultVFilmModel) Update(ctx context.Context, newData *VFilm) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rudyGcVFilmFileNameKey := fmt.Sprintf("%s%v", cacheRudyGcVFilmFileNamePrefix, data.FileName)
	rudyGcVFilmIdKey := fmt.Sprintf("%s%v", cacheRudyGcVFilmIdPrefix, data.Id)
	rudyGcVFilmMovieJavIdKey := fmt.Sprintf("%s%v", cacheRudyGcVFilmMovieJavIdPrefix, data.MovieJavId)
	rudyGcVFilmMovieNameKey := fmt.Sprintf("%s%v", cacheRudyGcVFilmMovieNamePrefix, data.MovieName)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, vFilmRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MovieJavId, newData.MovieName, newData.FileName, newData.DirectoryId, newData.RootDir, newData.Dir1Id, newData.Dir2Id, newData.Dir3Id, newData.Dir4Id, newData.Alias, newData.Size, newData.Width, newData.Height, newData.BitRate, newData.Duration, newData.FrameAverage, newData.HasSub, newData.SelfMake, newData.HasMask, newData.NeedScanMeta, newData.IsRemoved, newData.RemoveTime, newData.ScTimes, newData.ComeTimes, newData.LastScTime, newData.BirthTime, newData.CreatedOn, newData.UpdatedOn, newData.Id)
	}, rudyGcVFilmFileNameKey, rudyGcVFilmIdKey, rudyGcVFilmMovieJavIdKey, rudyGcVFilmMovieNameKey)
	return err
}

func (m *defaultVFilmModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRudyGcVFilmIdPrefix, primary)
}

func (m *defaultVFilmModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", vFilmRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultVFilmModel) tableName() string {
	return m.table
}
